// <auto-generated>
/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AsanaApiClient.Client;

namespace AsanaApiClient.Model
{
    /// <summary>
    /// The context from which this event originated.
    /// </summary>
    public partial class AuditLogEventContext : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuditLogEventContext" /> class.
        /// </summary>
        /// <param name="contextType">The type of context. Can be one of &#x60;web&#x60;, &#x60;desktop&#x60;, &#x60;mobile&#x60;, &#x60;asana_support&#x60;, &#x60;asana&#x60;, &#x60;email&#x60;, or &#x60;api&#x60;.</param>
        /// <param name="apiAuthenticationMethod">The authentication method used in the context of an API request. Only present if the &#x60;context_type&#x60; is &#x60;api&#x60;. Can be one of &#x60;cookie&#x60;, &#x60;oauth&#x60;, &#x60;personal_access_token&#x60;, or &#x60;service_account&#x60;.</param>
        /// <param name="clientIpAddress">The IP address of the client that initiated the event, if applicable.</param>
        /// <param name="userAgent">The user agent of the client that initiated the event, if applicable.</param>
        /// <param name="oauthAppName">The name of the OAuth App that initiated the event. Only present if the &#x60;api_authentication_method&#x60; is &#x60;oauth&#x60;.</param>
        /// <param name="ruleName">The name of the automation rule that initiated the event.</param>
        /// <param name="onBehalfOfUserId">The ID of the user who requested a change via support.</param>
        [JsonConstructor]
        public AuditLogEventContext(Option<ContextTypeEnum?> contextType = default, Option<ApiAuthenticationMethodEnum?> apiAuthenticationMethod = default, Option<string?> clientIpAddress = default, Option<string?> userAgent = default, Option<string?> oauthAppName = default, Option<string?> ruleName = default, Option<int?> onBehalfOfUserId = default)
        {
            ContextTypeOption = contextType;
            ApiAuthenticationMethodOption = apiAuthenticationMethod;
            ClientIpAddressOption = clientIpAddress;
            UserAgentOption = userAgent;
            OauthAppNameOption = oauthAppName;
            RuleNameOption = ruleName;
            OnBehalfOfUserIdOption = onBehalfOfUserId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The type of context. Can be one of &#x60;web&#x60;, &#x60;desktop&#x60;, &#x60;mobile&#x60;, &#x60;asana_support&#x60;, &#x60;asana&#x60;, &#x60;email&#x60;, or &#x60;api&#x60;.
        /// </summary>
        /// <value>The type of context. Can be one of &#x60;web&#x60;, &#x60;desktop&#x60;, &#x60;mobile&#x60;, &#x60;asana_support&#x60;, &#x60;asana&#x60;, &#x60;email&#x60;, or &#x60;api&#x60;.</value>
        public enum ContextTypeEnum
        {
            /// <summary>
            /// Enum Web for value: web
            /// </summary>
            Web = 1,

            /// <summary>
            /// Enum Desktop for value: desktop
            /// </summary>
            Desktop = 2,

            /// <summary>
            /// Enum Mobile for value: mobile
            /// </summary>
            Mobile = 3,

            /// <summary>
            /// Enum AsanaSupport for value: asana_support
            /// </summary>
            AsanaSupport = 4,

            /// <summary>
            /// Enum Asana for value: asana
            /// </summary>
            Asana = 5,

            /// <summary>
            /// Enum Email for value: email
            /// </summary>
            Email = 6,

            /// <summary>
            /// Enum Api for value: api
            /// </summary>
            Api = 7
        }

        /// <summary>
        /// Returns a <see cref="ContextTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ContextTypeEnum ContextTypeEnumFromString(string value)
        {
            if (value.Equals("web"))
                return ContextTypeEnum.Web;

            if (value.Equals("desktop"))
                return ContextTypeEnum.Desktop;

            if (value.Equals("mobile"))
                return ContextTypeEnum.Mobile;

            if (value.Equals("asana_support"))
                return ContextTypeEnum.AsanaSupport;

            if (value.Equals("asana"))
                return ContextTypeEnum.Asana;

            if (value.Equals("email"))
                return ContextTypeEnum.Email;

            if (value.Equals("api"))
                return ContextTypeEnum.Api;

            throw new NotImplementedException($"Could not convert value to type ContextTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ContextTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ContextTypeEnum? ContextTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("web"))
                return ContextTypeEnum.Web;

            if (value.Equals("desktop"))
                return ContextTypeEnum.Desktop;

            if (value.Equals("mobile"))
                return ContextTypeEnum.Mobile;

            if (value.Equals("asana_support"))
                return ContextTypeEnum.AsanaSupport;

            if (value.Equals("asana"))
                return ContextTypeEnum.Asana;

            if (value.Equals("email"))
                return ContextTypeEnum.Email;

            if (value.Equals("api"))
                return ContextTypeEnum.Api;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ContextTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ContextTypeEnumToJsonValue(ContextTypeEnum? value)
        {
            if (value == ContextTypeEnum.Web)
                return "web";

            if (value == ContextTypeEnum.Desktop)
                return "desktop";

            if (value == ContextTypeEnum.Mobile)
                return "mobile";

            if (value == ContextTypeEnum.AsanaSupport)
                return "asana_support";

            if (value == ContextTypeEnum.Asana)
                return "asana";

            if (value == ContextTypeEnum.Email)
                return "email";

            if (value == ContextTypeEnum.Api)
                return "api";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of ContextType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ContextTypeEnum?> ContextTypeOption { get; private set; }

        /// <summary>
        /// The type of context. Can be one of &#x60;web&#x60;, &#x60;desktop&#x60;, &#x60;mobile&#x60;, &#x60;asana_support&#x60;, &#x60;asana&#x60;, &#x60;email&#x60;, or &#x60;api&#x60;.
        /// </summary>
        /// <value>The type of context. Can be one of &#x60;web&#x60;, &#x60;desktop&#x60;, &#x60;mobile&#x60;, &#x60;asana_support&#x60;, &#x60;asana&#x60;, &#x60;email&#x60;, or &#x60;api&#x60;.</value>
        /* <example>web</example> */
        [JsonPropertyName("context_type")]
        public ContextTypeEnum? ContextType { get { return this.ContextTypeOption; } set { this.ContextTypeOption = new(value); } }

        /// <summary>
        /// The authentication method used in the context of an API request. Only present if the &#x60;context_type&#x60; is &#x60;api&#x60;. Can be one of &#x60;cookie&#x60;, &#x60;oauth&#x60;, &#x60;personal_access_token&#x60;, or &#x60;service_account&#x60;.
        /// </summary>
        /// <value>The authentication method used in the context of an API request. Only present if the &#x60;context_type&#x60; is &#x60;api&#x60;. Can be one of &#x60;cookie&#x60;, &#x60;oauth&#x60;, &#x60;personal_access_token&#x60;, or &#x60;service_account&#x60;.</value>
        public enum ApiAuthenticationMethodEnum
        {
            /// <summary>
            /// Enum Cookie for value: cookie
            /// </summary>
            Cookie = 1,

            /// <summary>
            /// Enum Oauth for value: oauth
            /// </summary>
            Oauth = 2,

            /// <summary>
            /// Enum PersonalAccessToken for value: personal_access_token
            /// </summary>
            PersonalAccessToken = 3,

            /// <summary>
            /// Enum ServiceAccount for value: service_account
            /// </summary>
            ServiceAccount = 4
        }

        /// <summary>
        /// Returns a <see cref="ApiAuthenticationMethodEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ApiAuthenticationMethodEnum ApiAuthenticationMethodEnumFromString(string value)
        {
            if (value.Equals("cookie"))
                return ApiAuthenticationMethodEnum.Cookie;

            if (value.Equals("oauth"))
                return ApiAuthenticationMethodEnum.Oauth;

            if (value.Equals("personal_access_token"))
                return ApiAuthenticationMethodEnum.PersonalAccessToken;

            if (value.Equals("service_account"))
                return ApiAuthenticationMethodEnum.ServiceAccount;

            throw new NotImplementedException($"Could not convert value to type ApiAuthenticationMethodEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ApiAuthenticationMethodEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ApiAuthenticationMethodEnum? ApiAuthenticationMethodEnumFromStringOrDefault(string value)
        {
            if (value.Equals("cookie"))
                return ApiAuthenticationMethodEnum.Cookie;

            if (value.Equals("oauth"))
                return ApiAuthenticationMethodEnum.Oauth;

            if (value.Equals("personal_access_token"))
                return ApiAuthenticationMethodEnum.PersonalAccessToken;

            if (value.Equals("service_account"))
                return ApiAuthenticationMethodEnum.ServiceAccount;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ApiAuthenticationMethodEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ApiAuthenticationMethodEnumToJsonValue(ApiAuthenticationMethodEnum? value)
        {
            if (value == ApiAuthenticationMethodEnum.Cookie)
                return "cookie";

            if (value == ApiAuthenticationMethodEnum.Oauth)
                return "oauth";

            if (value == ApiAuthenticationMethodEnum.PersonalAccessToken)
                return "personal_access_token";

            if (value == ApiAuthenticationMethodEnum.ServiceAccount)
                return "service_account";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of ApiAuthenticationMethod
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ApiAuthenticationMethodEnum?> ApiAuthenticationMethodOption { get; private set; }

        /// <summary>
        /// The authentication method used in the context of an API request. Only present if the &#x60;context_type&#x60; is &#x60;api&#x60;. Can be one of &#x60;cookie&#x60;, &#x60;oauth&#x60;, &#x60;personal_access_token&#x60;, or &#x60;service_account&#x60;.
        /// </summary>
        /// <value>The authentication method used in the context of an API request. Only present if the &#x60;context_type&#x60; is &#x60;api&#x60;. Can be one of &#x60;cookie&#x60;, &#x60;oauth&#x60;, &#x60;personal_access_token&#x60;, or &#x60;service_account&#x60;.</value>
        [JsonPropertyName("api_authentication_method")]
        public ApiAuthenticationMethodEnum? ApiAuthenticationMethod { get { return this.ApiAuthenticationMethodOption; } set { this.ApiAuthenticationMethodOption = new(value); } }

        /// <summary>
        /// Used to track the state of ClientIpAddress
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ClientIpAddressOption { get; private set; }

        /// <summary>
        /// The IP address of the client that initiated the event, if applicable.
        /// </summary>
        /// <value>The IP address of the client that initiated the event, if applicable.</value>
        /* <example>1.1.1.1</example> */
        [JsonPropertyName("client_ip_address")]
        public string? ClientIpAddress { get { return this.ClientIpAddressOption; } set { this.ClientIpAddressOption = new(value); } }

        /// <summary>
        /// Used to track the state of UserAgent
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UserAgentOption { get; private set; }

        /// <summary>
        /// The user agent of the client that initiated the event, if applicable.
        /// </summary>
        /// <value>The user agent of the client that initiated the event, if applicable.</value>
        /* <example>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</example> */
        [JsonPropertyName("user_agent")]
        public string? UserAgent { get { return this.UserAgentOption; } set { this.UserAgentOption = new(value); } }

        /// <summary>
        /// Used to track the state of OauthAppName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OauthAppNameOption { get; private set; }

        /// <summary>
        /// The name of the OAuth App that initiated the event. Only present if the &#x60;api_authentication_method&#x60; is &#x60;oauth&#x60;.
        /// </summary>
        /// <value>The name of the OAuth App that initiated the event. Only present if the &#x60;api_authentication_method&#x60; is &#x60;oauth&#x60;.</value>
        [JsonPropertyName("oauth_app_name")]
        public string? OauthAppName { get { return this.OauthAppNameOption; } set { this.OauthAppNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of RuleName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RuleNameOption { get; private set; }

        /// <summary>
        /// The name of the automation rule that initiated the event.
        /// </summary>
        /// <value>The name of the automation rule that initiated the event.</value>
        /* <example>When Task is added to this project</example> */
        [JsonPropertyName("rule_name")]
        public string? RuleName { get { return this.RuleNameOption; } set { this.RuleNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of OnBehalfOfUserId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> OnBehalfOfUserIdOption { get; private set; }

        /// <summary>
        /// The ID of the user who requested a change via support.
        /// </summary>
        /// <value>The ID of the user who requested a change via support.</value>
        /* <example>12345</example> */
        [JsonPropertyName("on_behalf_of_user_id")]
        public int? OnBehalfOfUserId { get { return this.OnBehalfOfUserIdOption; } set { this.OnBehalfOfUserIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuditLogEventContext {\n");
            sb.Append("  ContextType: ").Append(ContextType).Append("\n");
            sb.Append("  ApiAuthenticationMethod: ").Append(ApiAuthenticationMethod).Append("\n");
            sb.Append("  ClientIpAddress: ").Append(ClientIpAddress).Append("\n");
            sb.Append("  UserAgent: ").Append(UserAgent).Append("\n");
            sb.Append("  OauthAppName: ").Append(OauthAppName).Append("\n");
            sb.Append("  RuleName: ").Append(RuleName).Append("\n");
            sb.Append("  OnBehalfOfUserId: ").Append(OnBehalfOfUserId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AuditLogEventContext" />
    /// </summary>
    public class AuditLogEventContextJsonConverter : JsonConverter<AuditLogEventContext>
    {
        /// <summary>
        /// Deserializes json to <see cref="AuditLogEventContext" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AuditLogEventContext Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<AuditLogEventContext.ContextTypeEnum?> contextType = default;
            Option<AuditLogEventContext.ApiAuthenticationMethodEnum?> apiAuthenticationMethod = default;
            Option<string?> clientIpAddress = default;
            Option<string?> userAgent = default;
            Option<string?> oauthAppName = default;
            Option<string?> ruleName = default;
            Option<int?> onBehalfOfUserId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "context_type":
                            string? contextTypeRawValue = utf8JsonReader.GetString();
                            if (contextTypeRawValue != null)
                                contextType = new Option<AuditLogEventContext.ContextTypeEnum?>(AuditLogEventContext.ContextTypeEnumFromStringOrDefault(contextTypeRawValue));
                            break;
                        case "api_authentication_method":
                            string? apiAuthenticationMethodRawValue = utf8JsonReader.GetString();
                            if (apiAuthenticationMethodRawValue != null)
                                apiAuthenticationMethod = new Option<AuditLogEventContext.ApiAuthenticationMethodEnum?>(AuditLogEventContext.ApiAuthenticationMethodEnumFromStringOrDefault(apiAuthenticationMethodRawValue));
                            break;
                        case "client_ip_address":
                            clientIpAddress = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "user_agent":
                            userAgent = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "oauth_app_name":
                            oauthAppName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "rule_name":
                            ruleName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "on_behalf_of_user_id":
                            onBehalfOfUserId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (contextType.IsSet && contextType.Value == null)
                throw new ArgumentNullException(nameof(contextType), "Property is not nullable for class AuditLogEventContext.");

            if (apiAuthenticationMethod.IsSet && apiAuthenticationMethod.Value == null)
                throw new ArgumentNullException(nameof(apiAuthenticationMethod), "Property is not nullable for class AuditLogEventContext.");

            if (clientIpAddress.IsSet && clientIpAddress.Value == null)
                throw new ArgumentNullException(nameof(clientIpAddress), "Property is not nullable for class AuditLogEventContext.");

            if (userAgent.IsSet && userAgent.Value == null)
                throw new ArgumentNullException(nameof(userAgent), "Property is not nullable for class AuditLogEventContext.");

            if (oauthAppName.IsSet && oauthAppName.Value == null)
                throw new ArgumentNullException(nameof(oauthAppName), "Property is not nullable for class AuditLogEventContext.");

            if (ruleName.IsSet && ruleName.Value == null)
                throw new ArgumentNullException(nameof(ruleName), "Property is not nullable for class AuditLogEventContext.");

            if (onBehalfOfUserId.IsSet && onBehalfOfUserId.Value == null)
                throw new ArgumentNullException(nameof(onBehalfOfUserId), "Property is not nullable for class AuditLogEventContext.");

            return new AuditLogEventContext(contextType, apiAuthenticationMethod, clientIpAddress, userAgent, oauthAppName, ruleName, onBehalfOfUserId);
        }

        /// <summary>
        /// Serializes a <see cref="AuditLogEventContext" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="auditLogEventContext"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AuditLogEventContext auditLogEventContext, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, auditLogEventContext, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AuditLogEventContext" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="auditLogEventContext"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AuditLogEventContext auditLogEventContext, JsonSerializerOptions jsonSerializerOptions)
        {
            if (auditLogEventContext.ClientIpAddressOption.IsSet && auditLogEventContext.ClientIpAddress == null)
                throw new ArgumentNullException(nameof(auditLogEventContext.ClientIpAddress), "Property is required for class AuditLogEventContext.");

            if (auditLogEventContext.UserAgentOption.IsSet && auditLogEventContext.UserAgent == null)
                throw new ArgumentNullException(nameof(auditLogEventContext.UserAgent), "Property is required for class AuditLogEventContext.");

            if (auditLogEventContext.OauthAppNameOption.IsSet && auditLogEventContext.OauthAppName == null)
                throw new ArgumentNullException(nameof(auditLogEventContext.OauthAppName), "Property is required for class AuditLogEventContext.");

            if (auditLogEventContext.RuleNameOption.IsSet && auditLogEventContext.RuleName == null)
                throw new ArgumentNullException(nameof(auditLogEventContext.RuleName), "Property is required for class AuditLogEventContext.");

            var contextTypeRawValue = AuditLogEventContext.ContextTypeEnumToJsonValue(auditLogEventContext.ContextTypeOption.Value!.Value);
            writer.WriteString("context_type", contextTypeRawValue);
            var apiAuthenticationMethodRawValue = AuditLogEventContext.ApiAuthenticationMethodEnumToJsonValue(auditLogEventContext.ApiAuthenticationMethodOption.Value!.Value);
            writer.WriteString("api_authentication_method", apiAuthenticationMethodRawValue);
            if (auditLogEventContext.ClientIpAddressOption.IsSet)
                writer.WriteString("client_ip_address", auditLogEventContext.ClientIpAddress);

            if (auditLogEventContext.UserAgentOption.IsSet)
                writer.WriteString("user_agent", auditLogEventContext.UserAgent);

            if (auditLogEventContext.OauthAppNameOption.IsSet)
                writer.WriteString("oauth_app_name", auditLogEventContext.OauthAppName);

            if (auditLogEventContext.RuleNameOption.IsSet)
                writer.WriteString("rule_name", auditLogEventContext.RuleName);

            if (auditLogEventContext.OnBehalfOfUserIdOption.IsSet)
                writer.WriteNumber("on_behalf_of_user_id", auditLogEventContext.OnBehalfOfUserIdOption.Value!.Value);
        }
    }
}
