// <auto-generated>
/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AsanaApiClient.Client;

namespace AsanaApiClient.Model
{
    /// <summary>
    /// Event specific details. The schema will vary depending on the &#x60;event_type&#x60;.
    /// </summary>
    public partial class AuditLogEventDetails : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuditLogEventDetails" /> class.
        /// </summary>
        /// <param name="oldValue">The previous value of the field that was modified in the audited event.</param>
        /// <param name="newValue">The new value after the modification in the audited event.</param>
        /// <param name="group">The division or organizational unit where the event occurred. Primarily used to scope role change events (e.g., &#x60;user_division_admin_role_changed&#x60;), but may appear in other contexts involving group-level changes.</param>
        /// <param name="samlResponse">The response received from the IdP when a user logs in with SAML SSO. Present on &#x60;user_login_failed&#x60; and &#x60;user_login_succeeded&#x60; events.</param>
        [JsonConstructor]
        public AuditLogEventDetails(Option<string?> oldValue = default, Option<string?> newValue = default, Option<Dictionary<string, Object>?> group = default, Option<string?> samlResponse = default)
        {
            OldValueOption = oldValue;
            NewValueOption = newValue;
            GroupOption = group;
            SamlResponseOption = samlResponse;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of OldValue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OldValueOption { get; private set; }

        /// <summary>
        /// The previous value of the field that was modified in the audited event.
        /// </summary>
        /// <value>The previous value of the field that was modified in the audited event.</value>
        [JsonPropertyName("old_value")]
        public string? OldValue { get { return this.OldValueOption; } set { this.OldValueOption = new(value); } }

        /// <summary>
        /// Used to track the state of NewValue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NewValueOption { get; private set; }

        /// <summary>
        /// The new value after the modification in the audited event.
        /// </summary>
        /// <value>The new value after the modification in the audited event.</value>
        [JsonPropertyName("new_value")]
        public string? NewValue { get { return this.NewValueOption; } set { this.NewValueOption = new(value); } }

        /// <summary>
        /// Used to track the state of Group
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, Object>?> GroupOption { get; private set; }

        /// <summary>
        /// The division or organizational unit where the event occurred. Primarily used to scope role change events (e.g., &#x60;user_division_admin_role_changed&#x60;), but may appear in other contexts involving group-level changes.
        /// </summary>
        /// <value>The division or organizational unit where the event occurred. Primarily used to scope role change events (e.g., &#x60;user_division_admin_role_changed&#x60;), but may appear in other contexts involving group-level changes.</value>
        [JsonPropertyName("group")]
        public Dictionary<string, Object>? Group { get { return this.GroupOption; } set { this.GroupOption = new(value); } }

        /// <summary>
        /// Used to track the state of SamlResponse
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SamlResponseOption { get; private set; }

        /// <summary>
        /// The response received from the IdP when a user logs in with SAML SSO. Present on &#x60;user_login_failed&#x60; and &#x60;user_login_succeeded&#x60; events.
        /// </summary>
        /// <value>The response received from the IdP when a user logs in with SAML SSO. Present on &#x60;user_login_failed&#x60; and &#x60;user_login_succeeded&#x60; events.</value>
        [JsonPropertyName("saml_response")]
        public string? SamlResponse { get { return this.SamlResponseOption; } set { this.SamlResponseOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuditLogEventDetails {\n");
            sb.Append("  OldValue: ").Append(OldValue).Append("\n");
            sb.Append("  NewValue: ").Append(NewValue).Append("\n");
            sb.Append("  Group: ").Append(Group).Append("\n");
            sb.Append("  SamlResponse: ").Append(SamlResponse).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AuditLogEventDetails" />
    /// </summary>
    public class AuditLogEventDetailsJsonConverter : JsonConverter<AuditLogEventDetails>
    {
        /// <summary>
        /// Deserializes json to <see cref="AuditLogEventDetails" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AuditLogEventDetails Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> oldValue = default;
            Option<string?> newValue = default;
            Option<Dictionary<string, Object>?> group = default;
            Option<string?> samlResponse = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "old_value":
                            oldValue = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "new_value":
                            newValue = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "group":
                            group = new Option<Dictionary<string, Object>?>(JsonSerializer.Deserialize<Dictionary<string, Object>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "saml_response":
                            samlResponse = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (group.IsSet && group.Value == null)
                throw new ArgumentNullException(nameof(group), "Property is not nullable for class AuditLogEventDetails.");

            return new AuditLogEventDetails(oldValue, newValue, group, samlResponse);
        }

        /// <summary>
        /// Serializes a <see cref="AuditLogEventDetails" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="auditLogEventDetails"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AuditLogEventDetails auditLogEventDetails, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, auditLogEventDetails, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AuditLogEventDetails" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="auditLogEventDetails"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AuditLogEventDetails auditLogEventDetails, JsonSerializerOptions jsonSerializerOptions)
        {
            if (auditLogEventDetails.GroupOption.IsSet && auditLogEventDetails.Group == null)
                throw new ArgumentNullException(nameof(auditLogEventDetails.Group), "Property is required for class AuditLogEventDetails.");

            if (auditLogEventDetails.OldValueOption.IsSet)
                if (auditLogEventDetails.OldValueOption.Value != null)
                    writer.WriteString("old_value", auditLogEventDetails.OldValue);
                else
                    writer.WriteNull("old_value");

            if (auditLogEventDetails.NewValueOption.IsSet)
                if (auditLogEventDetails.NewValueOption.Value != null)
                    writer.WriteString("new_value", auditLogEventDetails.NewValue);
                else
                    writer.WriteNull("new_value");

            if (auditLogEventDetails.GroupOption.IsSet)
            {
                writer.WritePropertyName("group");
                JsonSerializer.Serialize(writer, auditLogEventDetails.Group, jsonSerializerOptions);
            }
            if (auditLogEventDetails.SamlResponseOption.IsSet)
                if (auditLogEventDetails.SamlResponseOption.Value != null)
                    writer.WriteString("saml_response", auditLogEventDetails.SamlResponse);
                else
                    writer.WriteNull("saml_response");
        }
    }
}
