// <auto-generated>
/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AsanaApiClient.Client;

namespace AsanaApiClient.Model
{
    /// <summary>
    /// A *budget* object represents a budget for a given parent.
    /// </summary>
    public partial class BudgetCompact : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BudgetCompact" /> class.
        /// </summary>
        /// <param name="gid">Globally unique identifier of the resource, as a string.</param>
        /// <param name="resourceType">The base type of this resource.</param>
        /// <param name="budgetType">The type of the budget, in \&quot;cost\&quot; or \&quot;time\&quot;. The value of this property will dictate how the corresponding values for actual, estimate, and total are interpreted.</param>
        [JsonConstructor]
        public BudgetCompact(Option<string?> gid = default, Option<string?> resourceType = default, Option<BudgetTypeEnum?> budgetType = default)
        {
            GidOption = gid;
            ResourceTypeOption = resourceType;
            BudgetTypeOption = budgetType;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The type of the budget, in \&quot;cost\&quot; or \&quot;time\&quot;. The value of this property will dictate how the corresponding values for actual, estimate, and total are interpreted.
        /// </summary>
        /// <value>The type of the budget, in \&quot;cost\&quot; or \&quot;time\&quot;. The value of this property will dictate how the corresponding values for actual, estimate, and total are interpreted.</value>
        public enum BudgetTypeEnum
        {
            /// <summary>
            /// Enum Cost for value: cost
            /// </summary>
            Cost = 1,

            /// <summary>
            /// Enum Time for value: time
            /// </summary>
            Time = 2
        }

        /// <summary>
        /// Returns a <see cref="BudgetTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static BudgetTypeEnum BudgetTypeEnumFromString(string value)
        {
            if (value.Equals("cost"))
                return BudgetTypeEnum.Cost;

            if (value.Equals("time"))
                return BudgetTypeEnum.Time;

            throw new NotImplementedException($"Could not convert value to type BudgetTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="BudgetTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static BudgetTypeEnum? BudgetTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("cost"))
                return BudgetTypeEnum.Cost;

            if (value.Equals("time"))
                return BudgetTypeEnum.Time;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="BudgetTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string BudgetTypeEnumToJsonValue(BudgetTypeEnum? value)
        {
            if (value == BudgetTypeEnum.Cost)
                return "cost";

            if (value == BudgetTypeEnum.Time)
                return "time";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of BudgetType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<BudgetTypeEnum?> BudgetTypeOption { get; private set; }

        /// <summary>
        /// The type of the budget, in \&quot;cost\&quot; or \&quot;time\&quot;. The value of this property will dictate how the corresponding values for actual, estimate, and total are interpreted.
        /// </summary>
        /// <value>The type of the budget, in \&quot;cost\&quot; or \&quot;time\&quot;. The value of this property will dictate how the corresponding values for actual, estimate, and total are interpreted.</value>
        [JsonPropertyName("budget_type")]
        public BudgetTypeEnum? BudgetType { get { return this.BudgetTypeOption; } set { this.BudgetTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Gid
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> GidOption { get; }

        /// <summary>
        /// Globally unique identifier of the resource, as a string.
        /// </summary>
        /// <value>Globally unique identifier of the resource, as a string.</value>
        /* <example>12345</example> */
        [JsonPropertyName("gid")]
        public string? Gid { get { return this.GidOption; } }

        /// <summary>
        /// Used to track the state of ResourceType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ResourceTypeOption { get; }

        /// <summary>
        /// The base type of this resource.
        /// </summary>
        /// <value>The base type of this resource.</value>
        /* <example>budget</example> */
        [JsonPropertyName("resource_type")]
        public string? ResourceType { get { return this.ResourceTypeOption; } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BudgetCompact {\n");
            sb.Append("  Gid: ").Append(Gid).Append("\n");
            sb.Append("  ResourceType: ").Append(ResourceType).Append("\n");
            sb.Append("  BudgetType: ").Append(BudgetType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BudgetCompact" />
    /// </summary>
    public class BudgetCompactJsonConverter : JsonConverter<BudgetCompact>
    {
        /// <summary>
        /// Deserializes json to <see cref="BudgetCompact" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BudgetCompact Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> gid = default;
            Option<string?> resourceType = default;
            Option<BudgetCompact.BudgetTypeEnum?> budgetType = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "gid":
                            gid = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "resource_type":
                            resourceType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "budget_type":
                            string? budgetTypeRawValue = utf8JsonReader.GetString();
                            if (budgetTypeRawValue != null)
                                budgetType = new Option<BudgetCompact.BudgetTypeEnum?>(BudgetCompact.BudgetTypeEnumFromStringOrDefault(budgetTypeRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (gid.IsSet && gid.Value == null)
                throw new ArgumentNullException(nameof(gid), "Property is not nullable for class BudgetCompact.");

            if (resourceType.IsSet && resourceType.Value == null)
                throw new ArgumentNullException(nameof(resourceType), "Property is not nullable for class BudgetCompact.");

            if (budgetType.IsSet && budgetType.Value == null)
                throw new ArgumentNullException(nameof(budgetType), "Property is not nullable for class BudgetCompact.");

            return new BudgetCompact(gid, resourceType, budgetType);
        }

        /// <summary>
        /// Serializes a <see cref="BudgetCompact" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="budgetCompact"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BudgetCompact budgetCompact, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, budgetCompact, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BudgetCompact" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="budgetCompact"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, BudgetCompact budgetCompact, JsonSerializerOptions jsonSerializerOptions)
        {
            if (budgetCompact.GidOption.IsSet && budgetCompact.Gid == null)
                throw new ArgumentNullException(nameof(budgetCompact.Gid), "Property is required for class BudgetCompact.");

            if (budgetCompact.ResourceTypeOption.IsSet && budgetCompact.ResourceType == null)
                throw new ArgumentNullException(nameof(budgetCompact.ResourceType), "Property is required for class BudgetCompact.");

            if (budgetCompact.GidOption.IsSet)
                writer.WriteString("gid", budgetCompact.Gid);

            if (budgetCompact.ResourceTypeOption.IsSet)
                writer.WriteString("resource_type", budgetCompact.ResourceType);

            var budgetTypeRawValue = BudgetCompact.BudgetTypeEnumToJsonValue(budgetCompact.BudgetTypeOption.Value!.Value);
            writer.WriteString("budget_type", budgetTypeRawValue);
        }
    }
}
