// <auto-generated>
/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AsanaApiClient.Client;

namespace AsanaApiClient.Model
{
    /// <summary>
    /// Defines how the total portion of a budget is configured. The total represents a user-defined target value, not an aggregated one. This object specifies whether the total is displayed and the current value for the selected budget_type.
    /// </summary>
    public partial class BudgetTotalRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BudgetTotalRequest" /> class.
        /// </summary>
        /// <param name="enabled">Indicates whether the total value is active and should be displayed in the budget. This flag primarily affects UI presentation and the response payload.</param>
        /// <param name="value">The user-set value for the total budget. When &#x60;budget_type&#x60; is &#x60;time&#x60;, represents minutes. When &#x60;budget_type&#x60; is &#x60;cost&#x60;, represents the monetary amount in the domain&#39;s currency. This value is stored separately for each &#x60;budget_type&#x60;, so switching between types preserves each value.</param>
        [JsonConstructor]
        public BudgetTotalRequest(Option<bool?> enabled = default, Option<decimal?> value = default)
        {
            EnabledOption = enabled;
            ValueOption = value;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Enabled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EnabledOption { get; private set; }

        /// <summary>
        /// Indicates whether the total value is active and should be displayed in the budget. This flag primarily affects UI presentation and the response payload.
        /// </summary>
        /// <value>Indicates whether the total value is active and should be displayed in the budget. This flag primarily affects UI presentation and the response payload.</value>
        /* <example>true</example> */
        [JsonPropertyName("enabled")]
        public bool? Enabled { get { return this.EnabledOption; } set { this.EnabledOption = new(value); } }

        /// <summary>
        /// Used to track the state of Value
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> ValueOption { get; private set; }

        /// <summary>
        /// The user-set value for the total budget. When &#x60;budget_type&#x60; is &#x60;time&#x60;, represents minutes. When &#x60;budget_type&#x60; is &#x60;cost&#x60;, represents the monetary amount in the domain&#39;s currency. This value is stored separately for each &#x60;budget_type&#x60;, so switching between types preserves each value.
        /// </summary>
        /// <value>The user-set value for the total budget. When &#x60;budget_type&#x60; is &#x60;time&#x60;, represents minutes. When &#x60;budget_type&#x60; is &#x60;cost&#x60;, represents the monetary amount in the domain&#39;s currency. This value is stored separately for each &#x60;budget_type&#x60;, so switching between types preserves each value.</value>
        /* <example>100</example> */
        [JsonPropertyName("value")]
        public decimal? Value { get { return this.ValueOption; } set { this.ValueOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BudgetTotalRequest {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BudgetTotalRequest" />
    /// </summary>
    public class BudgetTotalRequestJsonConverter : JsonConverter<BudgetTotalRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="BudgetTotalRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BudgetTotalRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> enabled = default;
            Option<decimal?> value = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "enabled":
                            enabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "value":
                            value = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (enabled.IsSet && enabled.Value == null)
                throw new ArgumentNullException(nameof(enabled), "Property is not nullable for class BudgetTotalRequest.");

            if (value.IsSet && value.Value == null)
                throw new ArgumentNullException(nameof(value), "Property is not nullable for class BudgetTotalRequest.");

            return new BudgetTotalRequest(enabled, value);
        }

        /// <summary>
        /// Serializes a <see cref="BudgetTotalRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="budgetTotalRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BudgetTotalRequest budgetTotalRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, budgetTotalRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BudgetTotalRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="budgetTotalRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, BudgetTotalRequest budgetTotalRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (budgetTotalRequest.EnabledOption.IsSet)
                writer.WriteBoolean("enabled", budgetTotalRequest.EnabledOption.Value!.Value);

            if (budgetTotalRequest.ValueOption.IsSet)
                writer.WriteNumber("value", budgetTotalRequest.ValueOption.Value!.Value);
        }
    }
}
