// <auto-generated>
/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AsanaApiClient.Client;

namespace AsanaApiClient.Model
{
    /// <summary>
    /// Defines the configuration of the actual portion of a budget. The actual value represents aggregated time tracking data attributed to the budget’s parent. This object controls which time entries are included based on their billable status. When no entries match the selected filter, the value will be 0.
    /// </summary>
    public partial class BudgetActualRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BudgetActualRequest" /> class.
        /// </summary>
        /// <param name="billableStatusFilter">Billable status filter applied to time tracking entries contributing to the actual value. Determines which entries are included in aggregation. When not provided, defaults to &#x60;billable&#x60;.</param>
        [JsonConstructor]
        public BudgetActualRequest(Option<BillableStatusFilterEnum?> billableStatusFilter = default)
        {
            BillableStatusFilterOption = billableStatusFilter;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Billable status filter applied to time tracking entries contributing to the actual value. Determines which entries are included in aggregation. When not provided, defaults to &#x60;billable&#x60;.
        /// </summary>
        /// <value>Billable status filter applied to time tracking entries contributing to the actual value. Determines which entries are included in aggregation. When not provided, defaults to &#x60;billable&#x60;.</value>
        public enum BillableStatusFilterEnum
        {
            /// <summary>
            /// Enum Billable for value: billable
            /// </summary>
            Billable = 1,

            /// <summary>
            /// Enum NonBillable for value: non_billable
            /// </summary>
            NonBillable = 2,

            /// <summary>
            /// Enum Any for value: any
            /// </summary>
            Any = 3
        }

        /// <summary>
        /// Returns a <see cref="BillableStatusFilterEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static BillableStatusFilterEnum BillableStatusFilterEnumFromString(string value)
        {
            if (value.Equals("billable"))
                return BillableStatusFilterEnum.Billable;

            if (value.Equals("non_billable"))
                return BillableStatusFilterEnum.NonBillable;

            if (value.Equals("any"))
                return BillableStatusFilterEnum.Any;

            throw new NotImplementedException($"Could not convert value to type BillableStatusFilterEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="BillableStatusFilterEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static BillableStatusFilterEnum? BillableStatusFilterEnumFromStringOrDefault(string value)
        {
            if (value.Equals("billable"))
                return BillableStatusFilterEnum.Billable;

            if (value.Equals("non_billable"))
                return BillableStatusFilterEnum.NonBillable;

            if (value.Equals("any"))
                return BillableStatusFilterEnum.Any;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="BillableStatusFilterEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string BillableStatusFilterEnumToJsonValue(BillableStatusFilterEnum? value)
        {
            if (value == BillableStatusFilterEnum.Billable)
                return "billable";

            if (value == BillableStatusFilterEnum.NonBillable)
                return "non_billable";

            if (value == BillableStatusFilterEnum.Any)
                return "any";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of BillableStatusFilter
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<BillableStatusFilterEnum?> BillableStatusFilterOption { get; private set; }

        /// <summary>
        /// Billable status filter applied to time tracking entries contributing to the actual value. Determines which entries are included in aggregation. When not provided, defaults to &#x60;billable&#x60;.
        /// </summary>
        /// <value>Billable status filter applied to time tracking entries contributing to the actual value. Determines which entries are included in aggregation. When not provided, defaults to &#x60;billable&#x60;.</value>
        /* <example>billable</example> */
        [JsonPropertyName("billable_status_filter")]
        public BillableStatusFilterEnum? BillableStatusFilter { get { return this.BillableStatusFilterOption; } set { this.BillableStatusFilterOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BudgetActualRequest {\n");
            sb.Append("  BillableStatusFilter: ").Append(BillableStatusFilter).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BudgetActualRequest" />
    /// </summary>
    public class BudgetActualRequestJsonConverter : JsonConverter<BudgetActualRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="BudgetActualRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BudgetActualRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<BudgetActualRequest.BillableStatusFilterEnum?> billableStatusFilter = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "billable_status_filter":
                            string? billableStatusFilterRawValue = utf8JsonReader.GetString();
                            if (billableStatusFilterRawValue != null)
                                billableStatusFilter = new Option<BudgetActualRequest.BillableStatusFilterEnum?>(BudgetActualRequest.BillableStatusFilterEnumFromStringOrDefault(billableStatusFilterRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (billableStatusFilter.IsSet && billableStatusFilter.Value == null)
                throw new ArgumentNullException(nameof(billableStatusFilter), "Property is not nullable for class BudgetActualRequest.");

            return new BudgetActualRequest(billableStatusFilter);
        }

        /// <summary>
        /// Serializes a <see cref="BudgetActualRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="budgetActualRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BudgetActualRequest budgetActualRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, budgetActualRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BudgetActualRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="budgetActualRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, BudgetActualRequest budgetActualRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            var billableStatusFilterRawValue = BudgetActualRequest.BillableStatusFilterEnumToJsonValue(budgetActualRequest.BillableStatusFilterOption.Value!.Value);
            writer.WriteString("billable_status_filter", billableStatusFilterRawValue);
        }
    }
}
