// <auto-generated>
/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AsanaApiClient.Client;

namespace AsanaApiClient.Model
{
    /// <summary>
    /// *Conditional*. Only relevant for custom fields of type &#x60;date&#x60;. This object reflects the chosen date (and optionally, time) value of a &#x60;date&#x60; custom field. If no date is selected, the value of &#x60;date_value&#x60; will be &#x60;null&#x60;.
    /// </summary>
    public partial class CustomFieldCompactDateValue : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomFieldCompactDateValue" /> class.
        /// </summary>
        /// <param name="date">A string representing the date in YYYY-MM-DD format.</param>
        /// <param name="dateTime">A string representing the date in ISO 8601 format. If no time value is selected, the value of &#x60;date-time&#x60; will be &#x60;null&#x60;.</param>
        [JsonConstructor]
        public CustomFieldCompactDateValue(Option<string?> date = default, Option<string?> dateTime = default)
        {
            DateOption = date;
            DateTimeOption = dateTime;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Date
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DateOption { get; private set; }

        /// <summary>
        /// A string representing the date in YYYY-MM-DD format.
        /// </summary>
        /// <value>A string representing the date in YYYY-MM-DD format.</value>
        /* <example>2024-08-23</example> */
        [JsonPropertyName("date")]
        public string? Date { get { return this.DateOption; } set { this.DateOption = new(value); } }

        /// <summary>
        /// Used to track the state of DateTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DateTimeOption { get; private set; }

        /// <summary>
        /// A string representing the date in ISO 8601 format. If no time value is selected, the value of &#x60;date-time&#x60; will be &#x60;null&#x60;.
        /// </summary>
        /// <value>A string representing the date in ISO 8601 format. If no time value is selected, the value of &#x60;date-time&#x60; will be &#x60;null&#x60;.</value>
        /* <example>2024-08-23T22:00:00.000Z</example> */
        [JsonPropertyName("date_time")]
        public string? DateTime { get { return this.DateTimeOption; } set { this.DateTimeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CustomFieldCompactDateValue {\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  DateTime: ").Append(DateTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CustomFieldCompactDateValue" />
    /// </summary>
    public class CustomFieldCompactDateValueJsonConverter : JsonConverter<CustomFieldCompactDateValue>
    {
        /// <summary>
        /// Deserializes json to <see cref="CustomFieldCompactDateValue" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CustomFieldCompactDateValue Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> date = default;
            Option<string?> dateTime = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "date":
                            date = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "date_time":
                            dateTime = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (date.IsSet && date.Value == null)
                throw new ArgumentNullException(nameof(date), "Property is not nullable for class CustomFieldCompactDateValue.");

            if (dateTime.IsSet && dateTime.Value == null)
                throw new ArgumentNullException(nameof(dateTime), "Property is not nullable for class CustomFieldCompactDateValue.");

            return new CustomFieldCompactDateValue(date, dateTime);
        }

        /// <summary>
        /// Serializes a <see cref="CustomFieldCompactDateValue" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="customFieldCompactDateValue"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CustomFieldCompactDateValue customFieldCompactDateValue, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, customFieldCompactDateValue, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CustomFieldCompactDateValue" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="customFieldCompactDateValue"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CustomFieldCompactDateValue customFieldCompactDateValue, JsonSerializerOptions jsonSerializerOptions)
        {
            if (customFieldCompactDateValue.DateOption.IsSet && customFieldCompactDateValue.Date == null)
                throw new ArgumentNullException(nameof(customFieldCompactDateValue.Date), "Property is required for class CustomFieldCompactDateValue.");

            if (customFieldCompactDateValue.DateTimeOption.IsSet && customFieldCompactDateValue.DateTime == null)
                throw new ArgumentNullException(nameof(customFieldCompactDateValue.DateTime), "Property is required for class CustomFieldCompactDateValue.");

            if (customFieldCompactDateValue.DateOption.IsSet)
                writer.WriteString("date", customFieldCompactDateValue.Date);

            if (customFieldCompactDateValue.DateTimeOption.IsSet)
                writer.WriteString("date_time", customFieldCompactDateValue.DateTime);
        }
    }
}
