// <auto-generated>
/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AsanaApiClient.Client;

namespace AsanaApiClient.Model
{
    /// <summary>
    /// GoalRelationshipRequest
    /// </summary>
    public partial class GoalRelationshipRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GoalRelationshipRequest" /> class.
        /// </summary>
        /// <param name="gid">Globally unique identifier of the resource, as a string.</param>
        /// <param name="resourceType">The base type of this resource.</param>
        /// <param name="resourceSubtype">The subtype of this resource. Different subtypes retain many of the same fields and behavior, but may render differently in Asana or represent resources with different semantic meaning.</param>
        /// <param name="supportingResource">supportingResource</param>
        /// <param name="contributionWeight">The weight that the supporting resource&#39;s progress contributes to the supported goal&#39;s progress. This can be 0, 1, or any value in between.</param>
        /// <param name="supportedGoal">supportedGoal</param>
        [JsonConstructor]
        public GoalRelationshipRequest(Option<string?> gid = default, Option<string?> resourceType = default, Option<ResourceSubtypeEnum?> resourceSubtype = default, Option<GoalRelationshipCompactSupportingResource?> supportingResource = default, Option<decimal?> contributionWeight = default, Option<GoalRelationshipBaseAllOfSupportedGoal?> supportedGoal = default)
        {
            GidOption = gid;
            ResourceTypeOption = resourceType;
            ResourceSubtypeOption = resourceSubtype;
            SupportingResourceOption = supportingResource;
            ContributionWeightOption = contributionWeight;
            SupportedGoalOption = supportedGoal;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The subtype of this resource. Different subtypes retain many of the same fields and behavior, but may render differently in Asana or represent resources with different semantic meaning.
        /// </summary>
        /// <value>The subtype of this resource. Different subtypes retain many of the same fields and behavior, but may render differently in Asana or represent resources with different semantic meaning.</value>
        public enum ResourceSubtypeEnum
        {
            /// <summary>
            /// Enum Subgoal for value: subgoal
            /// </summary>
            Subgoal = 1,

            /// <summary>
            /// Enum SupportingWork for value: supporting_work
            /// </summary>
            SupportingWork = 2
        }

        /// <summary>
        /// Returns a <see cref="ResourceSubtypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ResourceSubtypeEnum ResourceSubtypeEnumFromString(string value)
        {
            if (value.Equals("subgoal"))
                return ResourceSubtypeEnum.Subgoal;

            if (value.Equals("supporting_work"))
                return ResourceSubtypeEnum.SupportingWork;

            throw new NotImplementedException($"Could not convert value to type ResourceSubtypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ResourceSubtypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ResourceSubtypeEnum? ResourceSubtypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("subgoal"))
                return ResourceSubtypeEnum.Subgoal;

            if (value.Equals("supporting_work"))
                return ResourceSubtypeEnum.SupportingWork;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ResourceSubtypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ResourceSubtypeEnumToJsonValue(ResourceSubtypeEnum? value)
        {
            if (value == ResourceSubtypeEnum.Subgoal)
                return "subgoal";

            if (value == ResourceSubtypeEnum.SupportingWork)
                return "supporting_work";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of ResourceSubtype
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ResourceSubtypeEnum?> ResourceSubtypeOption { get; }

        /// <summary>
        /// The subtype of this resource. Different subtypes retain many of the same fields and behavior, but may render differently in Asana or represent resources with different semantic meaning.
        /// </summary>
        /// <value>The subtype of this resource. Different subtypes retain many of the same fields and behavior, but may render differently in Asana or represent resources with different semantic meaning.</value>
        /* <example>subgoal</example> */
        [JsonPropertyName("resource_subtype")]
        public ResourceSubtypeEnum? ResourceSubtype { get { return this.ResourceSubtypeOption; } }

        /// <summary>
        /// Used to track the state of Gid
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> GidOption { get; }

        /// <summary>
        /// Globally unique identifier of the resource, as a string.
        /// </summary>
        /// <value>Globally unique identifier of the resource, as a string.</value>
        /* <example>12345</example> */
        [JsonPropertyName("gid")]
        public string? Gid { get { return this.GidOption; } }

        /// <summary>
        /// Used to track the state of ResourceType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ResourceTypeOption { get; }

        /// <summary>
        /// The base type of this resource.
        /// </summary>
        /// <value>The base type of this resource.</value>
        /* <example>goal_relationship</example> */
        [JsonPropertyName("resource_type")]
        public string? ResourceType { get { return this.ResourceTypeOption; } }

        /// <summary>
        /// Used to track the state of SupportingResource
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<GoalRelationshipCompactSupportingResource?> SupportingResourceOption { get; private set; }

        /// <summary>
        /// Gets or Sets SupportingResource
        /// </summary>
        [JsonPropertyName("supporting_resource")]
        public GoalRelationshipCompactSupportingResource? SupportingResource { get { return this.SupportingResourceOption; } set { this.SupportingResourceOption = new(value); } }

        /// <summary>
        /// Used to track the state of ContributionWeight
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> ContributionWeightOption { get; private set; }

        /// <summary>
        /// The weight that the supporting resource&#39;s progress contributes to the supported goal&#39;s progress. This can be 0, 1, or any value in between.
        /// </summary>
        /// <value>The weight that the supporting resource&#39;s progress contributes to the supported goal&#39;s progress. This can be 0, 1, or any value in between.</value>
        /* <example>1.0</example> */
        [JsonPropertyName("contribution_weight")]
        public decimal? ContributionWeight { get { return this.ContributionWeightOption; } set { this.ContributionWeightOption = new(value); } }

        /// <summary>
        /// Used to track the state of SupportedGoal
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<GoalRelationshipBaseAllOfSupportedGoal?> SupportedGoalOption { get; private set; }

        /// <summary>
        /// Gets or Sets SupportedGoal
        /// </summary>
        [JsonPropertyName("supported_goal")]
        public GoalRelationshipBaseAllOfSupportedGoal? SupportedGoal { get { return this.SupportedGoalOption; } set { this.SupportedGoalOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GoalRelationshipRequest {\n");
            sb.Append("  Gid: ").Append(Gid).Append("\n");
            sb.Append("  ResourceType: ").Append(ResourceType).Append("\n");
            sb.Append("  ResourceSubtype: ").Append(ResourceSubtype).Append("\n");
            sb.Append("  SupportingResource: ").Append(SupportingResource).Append("\n");
            sb.Append("  ContributionWeight: ").Append(ContributionWeight).Append("\n");
            sb.Append("  SupportedGoal: ").Append(SupportedGoal).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GoalRelationshipRequest" />
    /// </summary>
    public class GoalRelationshipRequestJsonConverter : JsonConverter<GoalRelationshipRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="GoalRelationshipRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GoalRelationshipRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> gid = default;
            Option<string?> resourceType = default;
            Option<GoalRelationshipRequest.ResourceSubtypeEnum?> resourceSubtype = default;
            Option<GoalRelationshipCompactSupportingResource?> supportingResource = default;
            Option<decimal?> contributionWeight = default;
            Option<GoalRelationshipBaseAllOfSupportedGoal?> supportedGoal = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "gid":
                            gid = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "resource_type":
                            resourceType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "resource_subtype":
                            string? resourceSubtypeRawValue = utf8JsonReader.GetString();
                            if (resourceSubtypeRawValue != null)
                                resourceSubtype = new Option<GoalRelationshipRequest.ResourceSubtypeEnum?>(GoalRelationshipRequest.ResourceSubtypeEnumFromStringOrDefault(resourceSubtypeRawValue));
                            break;
                        case "supporting_resource":
                            supportingResource = new Option<GoalRelationshipCompactSupportingResource?>(JsonSerializer.Deserialize<GoalRelationshipCompactSupportingResource>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "contribution_weight":
                            contributionWeight = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "supported_goal":
                            supportedGoal = new Option<GoalRelationshipBaseAllOfSupportedGoal?>(JsonSerializer.Deserialize<GoalRelationshipBaseAllOfSupportedGoal>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (gid.IsSet && gid.Value == null)
                throw new ArgumentNullException(nameof(gid), "Property is not nullable for class GoalRelationshipRequest.");

            if (resourceType.IsSet && resourceType.Value == null)
                throw new ArgumentNullException(nameof(resourceType), "Property is not nullable for class GoalRelationshipRequest.");

            if (resourceSubtype.IsSet && resourceSubtype.Value == null)
                throw new ArgumentNullException(nameof(resourceSubtype), "Property is not nullable for class GoalRelationshipRequest.");

            if (supportingResource.IsSet && supportingResource.Value == null)
                throw new ArgumentNullException(nameof(supportingResource), "Property is not nullable for class GoalRelationshipRequest.");

            if (contributionWeight.IsSet && contributionWeight.Value == null)
                throw new ArgumentNullException(nameof(contributionWeight), "Property is not nullable for class GoalRelationshipRequest.");

            if (supportedGoal.IsSet && supportedGoal.Value == null)
                throw new ArgumentNullException(nameof(supportedGoal), "Property is not nullable for class GoalRelationshipRequest.");

            return new GoalRelationshipRequest(gid, resourceType, resourceSubtype, supportingResource, contributionWeight, supportedGoal);
        }

        /// <summary>
        /// Serializes a <see cref="GoalRelationshipRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="goalRelationshipRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GoalRelationshipRequest goalRelationshipRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, goalRelationshipRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GoalRelationshipRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="goalRelationshipRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GoalRelationshipRequest goalRelationshipRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (goalRelationshipRequest.GidOption.IsSet && goalRelationshipRequest.Gid == null)
                throw new ArgumentNullException(nameof(goalRelationshipRequest.Gid), "Property is required for class GoalRelationshipRequest.");

            if (goalRelationshipRequest.ResourceTypeOption.IsSet && goalRelationshipRequest.ResourceType == null)
                throw new ArgumentNullException(nameof(goalRelationshipRequest.ResourceType), "Property is required for class GoalRelationshipRequest.");

            if (goalRelationshipRequest.SupportingResourceOption.IsSet && goalRelationshipRequest.SupportingResource == null)
                throw new ArgumentNullException(nameof(goalRelationshipRequest.SupportingResource), "Property is required for class GoalRelationshipRequest.");

            if (goalRelationshipRequest.SupportedGoalOption.IsSet && goalRelationshipRequest.SupportedGoal == null)
                throw new ArgumentNullException(nameof(goalRelationshipRequest.SupportedGoal), "Property is required for class GoalRelationshipRequest.");

            if (goalRelationshipRequest.GidOption.IsSet)
                writer.WriteString("gid", goalRelationshipRequest.Gid);

            if (goalRelationshipRequest.ResourceTypeOption.IsSet)
                writer.WriteString("resource_type", goalRelationshipRequest.ResourceType);

            var resourceSubtypeRawValue = GoalRelationshipRequest.ResourceSubtypeEnumToJsonValue(goalRelationshipRequest.ResourceSubtypeOption.Value!.Value);
            writer.WriteString("resource_subtype", resourceSubtypeRawValue);
            if (goalRelationshipRequest.SupportingResourceOption.IsSet)
            {
                writer.WritePropertyName("supporting_resource");
                JsonSerializer.Serialize(writer, goalRelationshipRequest.SupportingResource, jsonSerializerOptions);
            }
            if (goalRelationshipRequest.ContributionWeightOption.IsSet)
                writer.WriteNumber("contribution_weight", goalRelationshipRequest.ContributionWeightOption.Value!.Value);

            if (goalRelationshipRequest.SupportedGoalOption.IsSet)
            {
                writer.WritePropertyName("supported_goal");
                JsonSerializer.Serialize(writer, goalRelationshipRequest.SupportedGoal, jsonSerializerOptions);
            }
        }
    }
}
