// <auto-generated>
/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AsanaApiClient.Client;

namespace AsanaApiClient.Model
{
    /// <summary>
    /// GoalRequest
    /// </summary>
    public partial class GoalRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GoalRequest" /> class.
        /// </summary>
        /// <param name="gid">Globally unique identifier of the resource, as a string.</param>
        /// <param name="resourceType">The base type of this resource.</param>
        /// <param name="name">The name of the goal.</param>
        /// <param name="htmlNotes">The notes of the goal with formatting as HTML.</param>
        /// <param name="notes">Free-form textual information associated with the goal (i.e. its description).</param>
        /// <param name="dueOn">The localized day on which this goal is due. This takes a date with format &#x60;YYYY-MM-DD&#x60;.</param>
        /// <param name="startOn">The day on which work for this goal begins, or null if the goal has no start date. This takes a date with &#x60;YYYY-MM-DD&#x60; format, and cannot be set unless there is an accompanying due date.</param>
        /// <param name="isWorkspaceLevel">*Conditional*. This property is only present when the &#x60;workspace&#x60; provided is an organization. Whether the goal belongs to the &#x60;workspace&#x60; (and is listed as part of the workspace’s goals) or not. If it isn’t a workspace-level goal, it is a team-level goal, and is associated with the goal’s team.</param>
        /// <param name="liked">True if the goal is liked by the authorized user, false if not.</param>
        /// <param name="team">*Conditional*. This property is only present when the &#x60;workspace&#x60; provided is an organization.</param>
        /// <param name="workspace">The &#x60;gid&#x60; of a workspace.</param>
        /// <param name="timePeriod">The &#x60;gid&#x60; of a time period.</param>
        /// <param name="owner">The &#x60;gid&#x60; of a user.</param>
        /// <param name="followers">followers</param>
        [JsonConstructor]
        public GoalRequest(Option<string?> gid = default, Option<string?> resourceType = default, Option<string?> name = default, Option<string?> htmlNotes = default, Option<string?> notes = default, Option<string?> dueOn = default, Option<string?> startOn = default, Option<bool?> isWorkspaceLevel = default, Option<bool?> liked = default, Option<string?> team = default, Option<string?> workspace = default, Option<string?> timePeriod = default, Option<string?> owner = default, Option<List<string>?> followers = default)
        {
            GidOption = gid;
            ResourceTypeOption = resourceType;
            NameOption = name;
            HtmlNotesOption = htmlNotes;
            NotesOption = notes;
            DueOnOption = dueOn;
            StartOnOption = startOn;
            IsWorkspaceLevelOption = isWorkspaceLevel;
            LikedOption = liked;
            TeamOption = team;
            WorkspaceOption = workspace;
            TimePeriodOption = timePeriod;
            OwnerOption = owner;
            FollowersOption = followers;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Gid
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> GidOption { get; }

        /// <summary>
        /// Globally unique identifier of the resource, as a string.
        /// </summary>
        /// <value>Globally unique identifier of the resource, as a string.</value>
        /* <example>12345</example> */
        [JsonPropertyName("gid")]
        public string? Gid { get { return this.GidOption; } }

        /// <summary>
        /// Used to track the state of ResourceType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ResourceTypeOption { get; }

        /// <summary>
        /// The base type of this resource.
        /// </summary>
        /// <value>The base type of this resource.</value>
        /* <example>goal</example> */
        [JsonPropertyName("resource_type")]
        public string? ResourceType { get { return this.ResourceTypeOption; } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// The name of the goal.
        /// </summary>
        /// <value>The name of the goal.</value>
        /* <example>Grow web traffic by 30%</example> */
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of HtmlNotes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> HtmlNotesOption { get; private set; }

        /// <summary>
        /// The notes of the goal with formatting as HTML.
        /// </summary>
        /// <value>The notes of the goal with formatting as HTML.</value>
        /* <example>&lt;body&gt;Start building brand awareness.&lt;/body&gt;</example> */
        [JsonPropertyName("html_notes")]
        public string? HtmlNotes { get { return this.HtmlNotesOption; } set { this.HtmlNotesOption = new(value); } }

        /// <summary>
        /// Used to track the state of Notes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NotesOption { get; private set; }

        /// <summary>
        /// Free-form textual information associated with the goal (i.e. its description).
        /// </summary>
        /// <value>Free-form textual information associated with the goal (i.e. its description).</value>
        /* <example>Start building brand awareness.</example> */
        [JsonPropertyName("notes")]
        public string? Notes { get { return this.NotesOption; } set { this.NotesOption = new(value); } }

        /// <summary>
        /// Used to track the state of DueOn
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DueOnOption { get; private set; }

        /// <summary>
        /// The localized day on which this goal is due. This takes a date with format &#x60;YYYY-MM-DD&#x60;.
        /// </summary>
        /// <value>The localized day on which this goal is due. This takes a date with format &#x60;YYYY-MM-DD&#x60;.</value>
        /* <example>2019-09-15</example> */
        [JsonPropertyName("due_on")]
        public string? DueOn { get { return this.DueOnOption; } set { this.DueOnOption = new(value); } }

        /// <summary>
        /// Used to track the state of StartOn
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StartOnOption { get; private set; }

        /// <summary>
        /// The day on which work for this goal begins, or null if the goal has no start date. This takes a date with &#x60;YYYY-MM-DD&#x60; format, and cannot be set unless there is an accompanying due date.
        /// </summary>
        /// <value>The day on which work for this goal begins, or null if the goal has no start date. This takes a date with &#x60;YYYY-MM-DD&#x60; format, and cannot be set unless there is an accompanying due date.</value>
        /* <example>2019-09-14</example> */
        [JsonPropertyName("start_on")]
        public string? StartOn { get { return this.StartOnOption; } set { this.StartOnOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsWorkspaceLevel
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsWorkspaceLevelOption { get; private set; }

        /// <summary>
        /// *Conditional*. This property is only present when the &#x60;workspace&#x60; provided is an organization. Whether the goal belongs to the &#x60;workspace&#x60; (and is listed as part of the workspace’s goals) or not. If it isn’t a workspace-level goal, it is a team-level goal, and is associated with the goal’s team.
        /// </summary>
        /// <value>*Conditional*. This property is only present when the &#x60;workspace&#x60; provided is an organization. Whether the goal belongs to the &#x60;workspace&#x60; (and is listed as part of the workspace’s goals) or not. If it isn’t a workspace-level goal, it is a team-level goal, and is associated with the goal’s team.</value>
        /* <example>true</example> */
        [JsonPropertyName("is_workspace_level")]
        public bool? IsWorkspaceLevel { get { return this.IsWorkspaceLevelOption; } set { this.IsWorkspaceLevelOption = new(value); } }

        /// <summary>
        /// Used to track the state of Liked
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> LikedOption { get; private set; }

        /// <summary>
        /// True if the goal is liked by the authorized user, false if not.
        /// </summary>
        /// <value>True if the goal is liked by the authorized user, false if not.</value>
        /* <example>false</example> */
        [JsonPropertyName("liked")]
        public bool? Liked { get { return this.LikedOption; } set { this.LikedOption = new(value); } }

        /// <summary>
        /// Used to track the state of Team
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TeamOption { get; private set; }

        /// <summary>
        /// *Conditional*. This property is only present when the &#x60;workspace&#x60; provided is an organization.
        /// </summary>
        /// <value>*Conditional*. This property is only present when the &#x60;workspace&#x60; provided is an organization.</value>
        /* <example>12345</example> */
        [JsonPropertyName("team")]
        public string? Team { get { return this.TeamOption; } set { this.TeamOption = new(value); } }

        /// <summary>
        /// Used to track the state of Workspace
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> WorkspaceOption { get; private set; }

        /// <summary>
        /// The &#x60;gid&#x60; of a workspace.
        /// </summary>
        /// <value>The &#x60;gid&#x60; of a workspace.</value>
        /* <example>12345</example> */
        [JsonPropertyName("workspace")]
        public string? Workspace { get { return this.WorkspaceOption; } set { this.WorkspaceOption = new(value); } }

        /// <summary>
        /// Used to track the state of TimePeriod
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TimePeriodOption { get; private set; }

        /// <summary>
        /// The &#x60;gid&#x60; of a time period.
        /// </summary>
        /// <value>The &#x60;gid&#x60; of a time period.</value>
        /* <example>12345</example> */
        [JsonPropertyName("time_period")]
        public string? TimePeriod { get { return this.TimePeriodOption; } set { this.TimePeriodOption = new(value); } }

        /// <summary>
        /// Used to track the state of Owner
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OwnerOption { get; private set; }

        /// <summary>
        /// The &#x60;gid&#x60; of a user.
        /// </summary>
        /// <value>The &#x60;gid&#x60; of a user.</value>
        /* <example>12345</example> */
        [JsonPropertyName("owner")]
        public string? Owner { get { return this.OwnerOption; } set { this.OwnerOption = new(value); } }

        /// <summary>
        /// Used to track the state of Followers
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> FollowersOption { get; private set; }

        /// <summary>
        /// Gets or Sets Followers
        /// </summary>
        /* <example>[&quot;12345&quot;]</example> */
        [JsonPropertyName("followers")]
        public List<string>? Followers { get { return this.FollowersOption; } set { this.FollowersOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GoalRequest {\n");
            sb.Append("  Gid: ").Append(Gid).Append("\n");
            sb.Append("  ResourceType: ").Append(ResourceType).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  HtmlNotes: ").Append(HtmlNotes).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("  DueOn: ").Append(DueOn).Append("\n");
            sb.Append("  StartOn: ").Append(StartOn).Append("\n");
            sb.Append("  IsWorkspaceLevel: ").Append(IsWorkspaceLevel).Append("\n");
            sb.Append("  Liked: ").Append(Liked).Append("\n");
            sb.Append("  Team: ").Append(Team).Append("\n");
            sb.Append("  Workspace: ").Append(Workspace).Append("\n");
            sb.Append("  TimePeriod: ").Append(TimePeriod).Append("\n");
            sb.Append("  Owner: ").Append(Owner).Append("\n");
            sb.Append("  Followers: ").Append(Followers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GoalRequest" />
    /// </summary>
    public class GoalRequestJsonConverter : JsonConverter<GoalRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="GoalRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GoalRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> gid = default;
            Option<string?> resourceType = default;
            Option<string?> name = default;
            Option<string?> htmlNotes = default;
            Option<string?> notes = default;
            Option<string?> dueOn = default;
            Option<string?> startOn = default;
            Option<bool?> isWorkspaceLevel = default;
            Option<bool?> liked = default;
            Option<string?> team = default;
            Option<string?> workspace = default;
            Option<string?> timePeriod = default;
            Option<string?> owner = default;
            Option<List<string>?> followers = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "gid":
                            gid = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "resource_type":
                            resourceType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "html_notes":
                            htmlNotes = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "notes":
                            notes = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "due_on":
                            dueOn = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "start_on":
                            startOn = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "is_workspace_level":
                            isWorkspaceLevel = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "liked":
                            liked = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "team":
                            team = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "workspace":
                            workspace = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "time_period":
                            timePeriod = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "owner":
                            owner = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "followers":
                            followers = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (gid.IsSet && gid.Value == null)
                throw new ArgumentNullException(nameof(gid), "Property is not nullable for class GoalRequest.");

            if (resourceType.IsSet && resourceType.Value == null)
                throw new ArgumentNullException(nameof(resourceType), "Property is not nullable for class GoalRequest.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class GoalRequest.");

            if (htmlNotes.IsSet && htmlNotes.Value == null)
                throw new ArgumentNullException(nameof(htmlNotes), "Property is not nullable for class GoalRequest.");

            if (notes.IsSet && notes.Value == null)
                throw new ArgumentNullException(nameof(notes), "Property is not nullable for class GoalRequest.");

            if (isWorkspaceLevel.IsSet && isWorkspaceLevel.Value == null)
                throw new ArgumentNullException(nameof(isWorkspaceLevel), "Property is not nullable for class GoalRequest.");

            if (liked.IsSet && liked.Value == null)
                throw new ArgumentNullException(nameof(liked), "Property is not nullable for class GoalRequest.");

            if (workspace.IsSet && workspace.Value == null)
                throw new ArgumentNullException(nameof(workspace), "Property is not nullable for class GoalRequest.");

            if (followers.IsSet && followers.Value == null)
                throw new ArgumentNullException(nameof(followers), "Property is not nullable for class GoalRequest.");

            return new GoalRequest(gid, resourceType, name, htmlNotes, notes, dueOn, startOn, isWorkspaceLevel, liked, team, workspace, timePeriod, owner, followers);
        }

        /// <summary>
        /// Serializes a <see cref="GoalRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="goalRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GoalRequest goalRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, goalRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GoalRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="goalRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GoalRequest goalRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (goalRequest.GidOption.IsSet && goalRequest.Gid == null)
                throw new ArgumentNullException(nameof(goalRequest.Gid), "Property is required for class GoalRequest.");

            if (goalRequest.ResourceTypeOption.IsSet && goalRequest.ResourceType == null)
                throw new ArgumentNullException(nameof(goalRequest.ResourceType), "Property is required for class GoalRequest.");

            if (goalRequest.NameOption.IsSet && goalRequest.Name == null)
                throw new ArgumentNullException(nameof(goalRequest.Name), "Property is required for class GoalRequest.");

            if (goalRequest.HtmlNotesOption.IsSet && goalRequest.HtmlNotes == null)
                throw new ArgumentNullException(nameof(goalRequest.HtmlNotes), "Property is required for class GoalRequest.");

            if (goalRequest.NotesOption.IsSet && goalRequest.Notes == null)
                throw new ArgumentNullException(nameof(goalRequest.Notes), "Property is required for class GoalRequest.");

            if (goalRequest.WorkspaceOption.IsSet && goalRequest.Workspace == null)
                throw new ArgumentNullException(nameof(goalRequest.Workspace), "Property is required for class GoalRequest.");

            if (goalRequest.FollowersOption.IsSet && goalRequest.Followers == null)
                throw new ArgumentNullException(nameof(goalRequest.Followers), "Property is required for class GoalRequest.");

            if (goalRequest.GidOption.IsSet)
                writer.WriteString("gid", goalRequest.Gid);

            if (goalRequest.ResourceTypeOption.IsSet)
                writer.WriteString("resource_type", goalRequest.ResourceType);

            if (goalRequest.NameOption.IsSet)
                writer.WriteString("name", goalRequest.Name);

            if (goalRequest.HtmlNotesOption.IsSet)
                writer.WriteString("html_notes", goalRequest.HtmlNotes);

            if (goalRequest.NotesOption.IsSet)
                writer.WriteString("notes", goalRequest.Notes);

            if (goalRequest.DueOnOption.IsSet)
                if (goalRequest.DueOnOption.Value != null)
                    writer.WriteString("due_on", goalRequest.DueOn);
                else
                    writer.WriteNull("due_on");

            if (goalRequest.StartOnOption.IsSet)
                if (goalRequest.StartOnOption.Value != null)
                    writer.WriteString("start_on", goalRequest.StartOn);
                else
                    writer.WriteNull("start_on");

            if (goalRequest.IsWorkspaceLevelOption.IsSet)
                writer.WriteBoolean("is_workspace_level", goalRequest.IsWorkspaceLevelOption.Value!.Value);

            if (goalRequest.LikedOption.IsSet)
                writer.WriteBoolean("liked", goalRequest.LikedOption.Value!.Value);

            if (goalRequest.TeamOption.IsSet)
                if (goalRequest.TeamOption.Value != null)
                    writer.WriteString("team", goalRequest.Team);
                else
                    writer.WriteNull("team");

            if (goalRequest.WorkspaceOption.IsSet)
                writer.WriteString("workspace", goalRequest.Workspace);

            if (goalRequest.TimePeriodOption.IsSet)
                if (goalRequest.TimePeriodOption.Value != null)
                    writer.WriteString("time_period", goalRequest.TimePeriod);
                else
                    writer.WriteNull("time_period");

            if (goalRequest.OwnerOption.IsSet)
                if (goalRequest.OwnerOption.Value != null)
                    writer.WriteString("owner", goalRequest.Owner);
                else
                    writer.WriteNull("owner");

            if (goalRequest.FollowersOption.IsSet)
            {
                writer.WritePropertyName("followers");
                JsonSerializer.Serialize(writer, goalRequest.Followers, jsonSerializerOptions);
            }
        }
    }
}
