// <auto-generated>
/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AsanaApiClient.Client;

namespace AsanaApiClient.Model
{
    /// <summary>
    /// A *graph_export* object represents a request to export the data starting from a parent object
    /// </summary>
    public partial class GraphExportCompact : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GraphExportCompact" /> class.
        /// </summary>
        /// <param name="gid">Globally unique identifier of the resource, as a string.</param>
        /// <param name="resourceType">The base type of this resource.</param>
        /// <param name="createdAt">The time at which this resource was created.</param>
        /// <param name="downloadUrl">Download this URL to retrieve the full export in JSON format. It will be compressed in a gzip (.gz) container.  *Note: May be null if the export is still in progress or failed.  If present, this URL may only be valid for 1 hour from the time of retrieval. You should avoid persisting this URL somewhere and rather refresh on demand to ensure you do not keep stale URLs.*</param>
        /// <param name="completedAt">The time at which this resource was completed.</param>
        [JsonConstructor]
        internal GraphExportCompact(Option<string?> gid = default, Option<string?> resourceType = default, Option<DateTime?> createdAt = default, Option<string?> downloadUrl = default, Option<DateTime?> completedAt = default)
        {
            GidOption = gid;
            ResourceTypeOption = resourceType;
            CreatedAtOption = createdAt;
            DownloadUrlOption = downloadUrl;
            CompletedAtOption = completedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Gid
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> GidOption { get; }

        /// <summary>
        /// Globally unique identifier of the resource, as a string.
        /// </summary>
        /// <value>Globally unique identifier of the resource, as a string.</value>
        /* <example>12345</example> */
        [JsonPropertyName("gid")]
        public string? Gid { get { return this.GidOption; } }

        /// <summary>
        /// Used to track the state of ResourceType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ResourceTypeOption { get; }

        /// <summary>
        /// The base type of this resource.
        /// </summary>
        /// <value>The base type of this resource.</value>
        /* <example>graph_export</example> */
        [JsonPropertyName("resource_type")]
        public string? ResourceType { get { return this.ResourceTypeOption; } }

        /// <summary>
        /// Used to track the state of CreatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> CreatedAtOption { get; }

        /// <summary>
        /// The time at which this resource was created.
        /// </summary>
        /// <value>The time at which this resource was created.</value>
        /* <example>2012-02-22T02:06:58.147Z</example> */
        [JsonPropertyName("created_at")]
        public DateTime? CreatedAt { get { return this.CreatedAtOption; } }

        /// <summary>
        /// Used to track the state of DownloadUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DownloadUrlOption { get; }

        /// <summary>
        /// Download this URL to retrieve the full export in JSON format. It will be compressed in a gzip (.gz) container.  *Note: May be null if the export is still in progress or failed.  If present, this URL may only be valid for 1 hour from the time of retrieval. You should avoid persisting this URL somewhere and rather refresh on demand to ensure you do not keep stale URLs.*
        /// </summary>
        /// <value>Download this URL to retrieve the full export in JSON format. It will be compressed in a gzip (.gz) container.  *Note: May be null if the export is still in progress or failed.  If present, this URL may only be valid for 1 hour from the time of retrieval. You should avoid persisting this URL somewhere and rather refresh on demand to ensure you do not keep stale URLs.*</value>
        /* <example>https://asana-export-us-east-1.s3.us-east-1.amazonaws.com/2563645399633793/domain_export/7588024658887731/download/ domain_export_2563645399633793_7588024658887731_2023018-201726.json.gz?X-Amz-Algorithm&#x3D;AWS4-HMAC-SHA256&amp; X-Amz-Content-Sha256&#x3D;xxxxxxxx&amp;X-Amz-Date&#x3D;xxxxxxxx&amp;X-Amz-Expires&#x3D;300&amp;X-Amz-Security-Token&#x3D;xxxxxxxx&amp; X-Amz-Signature&#x3D;xxxxxxxx&amp;X-Amz-SignedHeaders&#x3D;host&amp;x-id&#x3D;GetObject#_&#x3D;_</example> */
        [JsonPropertyName("download_url")]
        public string? DownloadUrl { get { return this.DownloadUrlOption; } }

        /// <summary>
        /// Used to track the state of CompletedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> CompletedAtOption { get; }

        /// <summary>
        /// The time at which this resource was completed.
        /// </summary>
        /// <value>The time at which this resource was completed.</value>
        /* <example>2012-02-22T03:06:58.147Z</example> */
        [JsonPropertyName("completed_at")]
        public DateTime? CompletedAt { get { return this.CompletedAtOption; } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GraphExportCompact {\n");
            sb.Append("  Gid: ").Append(Gid).Append("\n");
            sb.Append("  ResourceType: ").Append(ResourceType).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  DownloadUrl: ").Append(DownloadUrl).Append("\n");
            sb.Append("  CompletedAt: ").Append(CompletedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GraphExportCompact" />
    /// </summary>
    public class GraphExportCompactJsonConverter : JsonConverter<GraphExportCompact>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize CompletedAt
        /// </summary>
        public static string CompletedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="GraphExportCompact" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GraphExportCompact Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> gid = default;
            Option<string?> resourceType = default;
            Option<DateTime?> createdAt = default;
            Option<string?> downloadUrl = default;
            Option<DateTime?> completedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "gid":
                            gid = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "resource_type":
                            resourceType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "created_at":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "download_url":
                            downloadUrl = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "completed_at":
                            completedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (gid.IsSet && gid.Value == null)
                throw new ArgumentNullException(nameof(gid), "Property is not nullable for class GraphExportCompact.");

            if (resourceType.IsSet && resourceType.Value == null)
                throw new ArgumentNullException(nameof(resourceType), "Property is not nullable for class GraphExportCompact.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class GraphExportCompact.");

            if (completedAt.IsSet && completedAt.Value == null)
                throw new ArgumentNullException(nameof(completedAt), "Property is not nullable for class GraphExportCompact.");

            return new GraphExportCompact(gid, resourceType, createdAt, downloadUrl, completedAt);
        }

        /// <summary>
        /// Serializes a <see cref="GraphExportCompact" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="graphExportCompact"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GraphExportCompact graphExportCompact, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, graphExportCompact, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GraphExportCompact" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="graphExportCompact"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GraphExportCompact graphExportCompact, JsonSerializerOptions jsonSerializerOptions)
        {
            if (graphExportCompact.GidOption.IsSet && graphExportCompact.Gid == null)
                throw new ArgumentNullException(nameof(graphExportCompact.Gid), "Property is required for class GraphExportCompact.");

            if (graphExportCompact.ResourceTypeOption.IsSet && graphExportCompact.ResourceType == null)
                throw new ArgumentNullException(nameof(graphExportCompact.ResourceType), "Property is required for class GraphExportCompact.");

            if (graphExportCompact.GidOption.IsSet)
                writer.WriteString("gid", graphExportCompact.Gid);

            if (graphExportCompact.ResourceTypeOption.IsSet)
                writer.WriteString("resource_type", graphExportCompact.ResourceType);

            if (graphExportCompact.CreatedAtOption.IsSet)
                writer.WriteString("created_at", graphExportCompact.CreatedAtOption.Value!.Value.ToString(CreatedAtFormat));

            if (graphExportCompact.DownloadUrlOption.IsSet)
                if (graphExportCompact.DownloadUrlOption.Value != null)
                    writer.WriteString("download_url", graphExportCompact.DownloadUrl);
                else
                    writer.WriteNull("download_url");

            if (graphExportCompact.CompletedAtOption.IsSet)
                writer.WriteString("completed_at", graphExportCompact.CompletedAtOption.Value!.Value.ToString(CompletedAtFormat));
        }
    }
}
