// <auto-generated>
/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AsanaApiClient.Client;

namespace AsanaApiClient.Model
{
    /// <summary>
    /// A *job* is an object representing a process that handles asynchronous work.
    /// </summary>
    public partial class JobCompact : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JobCompact" /> class.
        /// </summary>
        /// <param name="gid">Globally unique identifier of the resource, as a string.</param>
        /// <param name="resourceType">The base type of this resource.</param>
        /// <param name="resourceSubtype">The subtype of this resource. Different subtypes retain many of the same fields and behavior, but may render differently in Asana or represent resources with different semantic meaning.</param>
        /// <param name="status">The current status of this job.</param>
        /// <param name="newPortfolio">newPortfolio</param>
        /// <param name="newProject">newProject</param>
        /// <param name="newTask">newTask</param>
        /// <param name="newProjectTemplate">newProjectTemplate</param>
        /// <param name="newGraphExport">newGraphExport</param>
        /// <param name="newResourceExport">newResourceExport</param>
        [JsonConstructor]
        public JobCompact(Option<string?> gid = default, Option<string?> resourceType = default, Option<string?> resourceSubtype = default, Option<StatusEnum?> status = default, Option<PortfolioCompact?> newPortfolio = default, Option<ProjectCompact?> newProject = default, Option<JobCompactNewTask?> newTask = default, Option<ProjectTemplateCompact?> newProjectTemplate = default, Option<GraphExportCompact?> newGraphExport = default, Option<ResourceExportCompact?> newResourceExport = default)
        {
            GidOption = gid;
            ResourceTypeOption = resourceType;
            ResourceSubtypeOption = resourceSubtype;
            StatusOption = status;
            NewPortfolioOption = newPortfolio;
            NewProjectOption = newProject;
            NewTaskOption = newTask;
            NewProjectTemplateOption = newProjectTemplate;
            NewGraphExportOption = newGraphExport;
            NewResourceExportOption = newResourceExport;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The current status of this job.
        /// </summary>
        /// <value>The current status of this job.</value>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum NotStarted for value: not_started
            /// </summary>
            NotStarted = 1,

            /// <summary>
            /// Enum InProgress for value: in_progress
            /// </summary>
            InProgress = 2,

            /// <summary>
            /// Enum Succeeded for value: succeeded
            /// </summary>
            Succeeded = 3,

            /// <summary>
            /// Enum Failed for value: failed
            /// </summary>
            Failed = 4
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("not_started"))
                return StatusEnum.NotStarted;

            if (value.Equals("in_progress"))
                return StatusEnum.InProgress;

            if (value.Equals("succeeded"))
                return StatusEnum.Succeeded;

            if (value.Equals("failed"))
                return StatusEnum.Failed;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("not_started"))
                return StatusEnum.NotStarted;

            if (value.Equals("in_progress"))
                return StatusEnum.InProgress;

            if (value.Equals("succeeded"))
                return StatusEnum.Succeeded;

            if (value.Equals("failed"))
                return StatusEnum.Failed;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum? value)
        {
            if (value == StatusEnum.NotStarted)
                return "not_started";

            if (value == StatusEnum.InProgress)
                return "in_progress";

            if (value == StatusEnum.Succeeded)
                return "succeeded";

            if (value == StatusEnum.Failed)
                return "failed";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<StatusEnum?> StatusOption { get; }

        /// <summary>
        /// The current status of this job.
        /// </summary>
        /// <value>The current status of this job.</value>
        /* <example>in_progress</example> */
        [JsonPropertyName("status")]
        public StatusEnum? Status { get { return this.StatusOption; } }

        /// <summary>
        /// Used to track the state of Gid
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> GidOption { get; }

        /// <summary>
        /// Globally unique identifier of the resource, as a string.
        /// </summary>
        /// <value>Globally unique identifier of the resource, as a string.</value>
        /* <example>12345</example> */
        [JsonPropertyName("gid")]
        public string? Gid { get { return this.GidOption; } }

        /// <summary>
        /// Used to track the state of ResourceType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ResourceTypeOption { get; }

        /// <summary>
        /// The base type of this resource.
        /// </summary>
        /// <value>The base type of this resource.</value>
        /* <example>job</example> */
        [JsonPropertyName("resource_type")]
        public string? ResourceType { get { return this.ResourceTypeOption; } }

        /// <summary>
        /// Used to track the state of ResourceSubtype
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ResourceSubtypeOption { get; }

        /// <summary>
        /// The subtype of this resource. Different subtypes retain many of the same fields and behavior, but may render differently in Asana or represent resources with different semantic meaning.
        /// </summary>
        /// <value>The subtype of this resource. Different subtypes retain many of the same fields and behavior, but may render differently in Asana or represent resources with different semantic meaning.</value>
        /* <example>duplicate_task</example> */
        [JsonPropertyName("resource_subtype")]
        public string? ResourceSubtype { get { return this.ResourceSubtypeOption; } }

        /// <summary>
        /// Used to track the state of NewPortfolio
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<PortfolioCompact?> NewPortfolioOption { get; private set; }

        /// <summary>
        /// Gets or Sets NewPortfolio
        /// </summary>
        [JsonPropertyName("new_portfolio")]
        public PortfolioCompact? NewPortfolio { get { return this.NewPortfolioOption; } set { this.NewPortfolioOption = new(value); } }

        /// <summary>
        /// Used to track the state of NewProject
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ProjectCompact?> NewProjectOption { get; private set; }

        /// <summary>
        /// Gets or Sets NewProject
        /// </summary>
        [JsonPropertyName("new_project")]
        public ProjectCompact? NewProject { get { return this.NewProjectOption; } set { this.NewProjectOption = new(value); } }

        /// <summary>
        /// Used to track the state of NewTask
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<JobCompactNewTask?> NewTaskOption { get; private set; }

        /// <summary>
        /// Gets or Sets NewTask
        /// </summary>
        [JsonPropertyName("new_task")]
        public JobCompactNewTask? NewTask { get { return this.NewTaskOption; } set { this.NewTaskOption = new(value); } }

        /// <summary>
        /// Used to track the state of NewProjectTemplate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ProjectTemplateCompact?> NewProjectTemplateOption { get; private set; }

        /// <summary>
        /// Gets or Sets NewProjectTemplate
        /// </summary>
        [JsonPropertyName("new_project_template")]
        public ProjectTemplateCompact? NewProjectTemplate { get { return this.NewProjectTemplateOption; } set { this.NewProjectTemplateOption = new(value); } }

        /// <summary>
        /// Used to track the state of NewGraphExport
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<GraphExportCompact?> NewGraphExportOption { get; private set; }

        /// <summary>
        /// Gets or Sets NewGraphExport
        /// </summary>
        [JsonPropertyName("new_graph_export")]
        public GraphExportCompact? NewGraphExport { get { return this.NewGraphExportOption; } set { this.NewGraphExportOption = new(value); } }

        /// <summary>
        /// Used to track the state of NewResourceExport
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ResourceExportCompact?> NewResourceExportOption { get; private set; }

        /// <summary>
        /// Gets or Sets NewResourceExport
        /// </summary>
        [JsonPropertyName("new_resource_export")]
        public ResourceExportCompact? NewResourceExport { get { return this.NewResourceExportOption; } set { this.NewResourceExportOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JobCompact {\n");
            sb.Append("  Gid: ").Append(Gid).Append("\n");
            sb.Append("  ResourceType: ").Append(ResourceType).Append("\n");
            sb.Append("  ResourceSubtype: ").Append(ResourceSubtype).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  NewPortfolio: ").Append(NewPortfolio).Append("\n");
            sb.Append("  NewProject: ").Append(NewProject).Append("\n");
            sb.Append("  NewTask: ").Append(NewTask).Append("\n");
            sb.Append("  NewProjectTemplate: ").Append(NewProjectTemplate).Append("\n");
            sb.Append("  NewGraphExport: ").Append(NewGraphExport).Append("\n");
            sb.Append("  NewResourceExport: ").Append(NewResourceExport).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="JobCompact" />
    /// </summary>
    public class JobCompactJsonConverter : JsonConverter<JobCompact>
    {
        /// <summary>
        /// Deserializes json to <see cref="JobCompact" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override JobCompact Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> gid = default;
            Option<string?> resourceType = default;
            Option<string?> resourceSubtype = default;
            Option<JobCompact.StatusEnum?> status = default;
            Option<PortfolioCompact?> newPortfolio = default;
            Option<ProjectCompact?> newProject = default;
            Option<JobCompactNewTask?> newTask = default;
            Option<ProjectTemplateCompact?> newProjectTemplate = default;
            Option<GraphExportCompact?> newGraphExport = default;
            Option<ResourceExportCompact?> newResourceExport = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "gid":
                            gid = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "resource_type":
                            resourceType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "resource_subtype":
                            resourceSubtype = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<JobCompact.StatusEnum?>(JobCompact.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        case "new_portfolio":
                            newPortfolio = new Option<PortfolioCompact?>(JsonSerializer.Deserialize<PortfolioCompact>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "new_project":
                            newProject = new Option<ProjectCompact?>(JsonSerializer.Deserialize<ProjectCompact>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "new_task":
                            newTask = new Option<JobCompactNewTask?>(JsonSerializer.Deserialize<JobCompactNewTask>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "new_project_template":
                            newProjectTemplate = new Option<ProjectTemplateCompact?>(JsonSerializer.Deserialize<ProjectTemplateCompact>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "new_graph_export":
                            newGraphExport = new Option<GraphExportCompact?>(JsonSerializer.Deserialize<GraphExportCompact>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "new_resource_export":
                            newResourceExport = new Option<ResourceExportCompact?>(JsonSerializer.Deserialize<ResourceExportCompact>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (gid.IsSet && gid.Value == null)
                throw new ArgumentNullException(nameof(gid), "Property is not nullable for class JobCompact.");

            if (resourceType.IsSet && resourceType.Value == null)
                throw new ArgumentNullException(nameof(resourceType), "Property is not nullable for class JobCompact.");

            if (resourceSubtype.IsSet && resourceSubtype.Value == null)
                throw new ArgumentNullException(nameof(resourceSubtype), "Property is not nullable for class JobCompact.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class JobCompact.");

            if (newPortfolio.IsSet && newPortfolio.Value == null)
                throw new ArgumentNullException(nameof(newPortfolio), "Property is not nullable for class JobCompact.");

            if (newProject.IsSet && newProject.Value == null)
                throw new ArgumentNullException(nameof(newProject), "Property is not nullable for class JobCompact.");

            if (newTask.IsSet && newTask.Value == null)
                throw new ArgumentNullException(nameof(newTask), "Property is not nullable for class JobCompact.");

            if (newProjectTemplate.IsSet && newProjectTemplate.Value == null)
                throw new ArgumentNullException(nameof(newProjectTemplate), "Property is not nullable for class JobCompact.");

            if (newGraphExport.IsSet && newGraphExport.Value == null)
                throw new ArgumentNullException(nameof(newGraphExport), "Property is not nullable for class JobCompact.");

            if (newResourceExport.IsSet && newResourceExport.Value == null)
                throw new ArgumentNullException(nameof(newResourceExport), "Property is not nullable for class JobCompact.");

            return new JobCompact(gid, resourceType, resourceSubtype, status, newPortfolio, newProject, newTask, newProjectTemplate, newGraphExport, newResourceExport);
        }

        /// <summary>
        /// Serializes a <see cref="JobCompact" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="jobCompact"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, JobCompact jobCompact, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, jobCompact, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="JobCompact" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="jobCompact"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, JobCompact jobCompact, JsonSerializerOptions jsonSerializerOptions)
        {
            if (jobCompact.GidOption.IsSet && jobCompact.Gid == null)
                throw new ArgumentNullException(nameof(jobCompact.Gid), "Property is required for class JobCompact.");

            if (jobCompact.ResourceTypeOption.IsSet && jobCompact.ResourceType == null)
                throw new ArgumentNullException(nameof(jobCompact.ResourceType), "Property is required for class JobCompact.");

            if (jobCompact.ResourceSubtypeOption.IsSet && jobCompact.ResourceSubtype == null)
                throw new ArgumentNullException(nameof(jobCompact.ResourceSubtype), "Property is required for class JobCompact.");

            if (jobCompact.NewPortfolioOption.IsSet && jobCompact.NewPortfolio == null)
                throw new ArgumentNullException(nameof(jobCompact.NewPortfolio), "Property is required for class JobCompact.");

            if (jobCompact.NewProjectOption.IsSet && jobCompact.NewProject == null)
                throw new ArgumentNullException(nameof(jobCompact.NewProject), "Property is required for class JobCompact.");

            if (jobCompact.NewTaskOption.IsSet && jobCompact.NewTask == null)
                throw new ArgumentNullException(nameof(jobCompact.NewTask), "Property is required for class JobCompact.");

            if (jobCompact.NewProjectTemplateOption.IsSet && jobCompact.NewProjectTemplate == null)
                throw new ArgumentNullException(nameof(jobCompact.NewProjectTemplate), "Property is required for class JobCompact.");

            if (jobCompact.NewGraphExportOption.IsSet && jobCompact.NewGraphExport == null)
                throw new ArgumentNullException(nameof(jobCompact.NewGraphExport), "Property is required for class JobCompact.");

            if (jobCompact.NewResourceExportOption.IsSet && jobCompact.NewResourceExport == null)
                throw new ArgumentNullException(nameof(jobCompact.NewResourceExport), "Property is required for class JobCompact.");

            if (jobCompact.GidOption.IsSet)
                writer.WriteString("gid", jobCompact.Gid);

            if (jobCompact.ResourceTypeOption.IsSet)
                writer.WriteString("resource_type", jobCompact.ResourceType);

            if (jobCompact.ResourceSubtypeOption.IsSet)
                writer.WriteString("resource_subtype", jobCompact.ResourceSubtype);

            var statusRawValue = JobCompact.StatusEnumToJsonValue(jobCompact.StatusOption.Value!.Value);
            writer.WriteString("status", statusRawValue);
            if (jobCompact.NewPortfolioOption.IsSet)
            {
                writer.WritePropertyName("new_portfolio");
                JsonSerializer.Serialize(writer, jobCompact.NewPortfolio, jsonSerializerOptions);
            }
            if (jobCompact.NewProjectOption.IsSet)
            {
                writer.WritePropertyName("new_project");
                JsonSerializer.Serialize(writer, jobCompact.NewProject, jsonSerializerOptions);
            }
            if (jobCompact.NewTaskOption.IsSet)
            {
                writer.WritePropertyName("new_task");
                JsonSerializer.Serialize(writer, jobCompact.NewTask, jsonSerializerOptions);
            }
            if (jobCompact.NewProjectTemplateOption.IsSet)
            {
                writer.WritePropertyName("new_project_template");
                JsonSerializer.Serialize(writer, jobCompact.NewProjectTemplate, jsonSerializerOptions);
            }
            if (jobCompact.NewGraphExportOption.IsSet)
            {
                writer.WritePropertyName("new_graph_export");
                JsonSerializer.Serialize(writer, jobCompact.NewGraphExport, jsonSerializerOptions);
            }
            if (jobCompact.NewResourceExportOption.IsSet)
            {
                writer.WritePropertyName("new_resource_export");
                JsonSerializer.Serialize(writer, jobCompact.NewResourceExport, jsonSerializerOptions);
            }
        }
    }
}
