// <auto-generated>
/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AsanaApiClient.Client;

namespace AsanaApiClient.Model
{
    /// <summary>
    /// SectionRequest
    /// </summary>
    public partial class SectionRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SectionRequest" /> class.
        /// </summary>
        /// <param name="name">The text to be displayed as the section name. This cannot be an empty string.</param>
        /// <param name="insertBefore">An existing section within this project before which the added section should be inserted. Cannot be provided together with insert_after.</param>
        /// <param name="insertAfter">An existing section within this project after which the added section should be inserted. Cannot be provided together with insert_before.</param>
        [JsonConstructor]
        public SectionRequest(string name, Option<string?> insertBefore = default, Option<string?> insertAfter = default)
        {
            Name = name;
            InsertBeforeOption = insertBefore;
            InsertAfterOption = insertAfter;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The text to be displayed as the section name. This cannot be an empty string.
        /// </summary>
        /// <value>The text to be displayed as the section name. This cannot be an empty string.</value>
        /* <example>Next Actions</example> */
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Used to track the state of InsertBefore
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InsertBeforeOption { get; private set; }

        /// <summary>
        /// An existing section within this project before which the added section should be inserted. Cannot be provided together with insert_after.
        /// </summary>
        /// <value>An existing section within this project before which the added section should be inserted. Cannot be provided together with insert_after.</value>
        /* <example>86420</example> */
        [JsonPropertyName("insert_before")]
        public string? InsertBefore { get { return this.InsertBeforeOption; } set { this.InsertBeforeOption = new(value); } }

        /// <summary>
        /// Used to track the state of InsertAfter
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InsertAfterOption { get; private set; }

        /// <summary>
        /// An existing section within this project after which the added section should be inserted. Cannot be provided together with insert_before.
        /// </summary>
        /// <value>An existing section within this project after which the added section should be inserted. Cannot be provided together with insert_before.</value>
        /* <example>987654</example> */
        [JsonPropertyName("insert_after")]
        public string? InsertAfter { get { return this.InsertAfterOption; } set { this.InsertAfterOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SectionRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  InsertBefore: ").Append(InsertBefore).Append("\n");
            sb.Append("  InsertAfter: ").Append(InsertAfter).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SectionRequest" />
    /// </summary>
    public class SectionRequestJsonConverter : JsonConverter<SectionRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="SectionRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SectionRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> insertBefore = default;
            Option<string?> insertAfter = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "insert_before":
                            insertBefore = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "insert_after":
                            insertAfter = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class SectionRequest.", nameof(name));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class SectionRequest.");

            if (insertBefore.IsSet && insertBefore.Value == null)
                throw new ArgumentNullException(nameof(insertBefore), "Property is not nullable for class SectionRequest.");

            if (insertAfter.IsSet && insertAfter.Value == null)
                throw new ArgumentNullException(nameof(insertAfter), "Property is not nullable for class SectionRequest.");

            return new SectionRequest(name.Value!, insertBefore, insertAfter);
        }

        /// <summary>
        /// Serializes a <see cref="SectionRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sectionRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SectionRequest sectionRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, sectionRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SectionRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sectionRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SectionRequest sectionRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (sectionRequest.Name == null)
                throw new ArgumentNullException(nameof(sectionRequest.Name), "Property is required for class SectionRequest.");

            if (sectionRequest.InsertBeforeOption.IsSet && sectionRequest.InsertBefore == null)
                throw new ArgumentNullException(nameof(sectionRequest.InsertBefore), "Property is required for class SectionRequest.");

            if (sectionRequest.InsertAfterOption.IsSet && sectionRequest.InsertAfter == null)
                throw new ArgumentNullException(nameof(sectionRequest.InsertAfter), "Property is required for class SectionRequest.");

            writer.WriteString("name", sectionRequest.Name);

            if (sectionRequest.InsertBeforeOption.IsSet)
                writer.WriteString("insert_before", sectionRequest.InsertBefore);

            if (sectionRequest.InsertAfterOption.IsSet)
                writer.WriteString("insert_after", sectionRequest.InsertAfter);
        }
    }
}
