// <auto-generated>
/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AsanaApiClient.Client;

namespace AsanaApiClient.Model
{
    /// <summary>
    /// TaskTemplateRecipeCompact
    /// </summary>
    public partial class TaskTemplateRecipeCompact : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TaskTemplateRecipeCompact" /> class.
        /// </summary>
        /// <param name="name">Name of the task that will be created from this template.</param>
        /// <param name="taskResourceSubtype">The subtype of the task that will be created from this template.</param>
        [JsonConstructor]
        public TaskTemplateRecipeCompact(Option<string?> name = default, Option<TaskResourceSubtypeEnum?> taskResourceSubtype = default)
        {
            NameOption = name;
            TaskResourceSubtypeOption = taskResourceSubtype;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The subtype of the task that will be created from this template.
        /// </summary>
        /// <value>The subtype of the task that will be created from this template.</value>
        public enum TaskResourceSubtypeEnum
        {
            /// <summary>
            /// Enum DefaultTask for value: default_task
            /// </summary>
            DefaultTask = 1,

            /// <summary>
            /// Enum MilestoneTask for value: milestone_task
            /// </summary>
            MilestoneTask = 2,

            /// <summary>
            /// Enum ApprovalTask for value: approval_task
            /// </summary>
            ApprovalTask = 3
        }

        /// <summary>
        /// Returns a <see cref="TaskResourceSubtypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TaskResourceSubtypeEnum TaskResourceSubtypeEnumFromString(string value)
        {
            if (value.Equals("default_task"))
                return TaskResourceSubtypeEnum.DefaultTask;

            if (value.Equals("milestone_task"))
                return TaskResourceSubtypeEnum.MilestoneTask;

            if (value.Equals("approval_task"))
                return TaskResourceSubtypeEnum.ApprovalTask;

            throw new NotImplementedException($"Could not convert value to type TaskResourceSubtypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TaskResourceSubtypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TaskResourceSubtypeEnum? TaskResourceSubtypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("default_task"))
                return TaskResourceSubtypeEnum.DefaultTask;

            if (value.Equals("milestone_task"))
                return TaskResourceSubtypeEnum.MilestoneTask;

            if (value.Equals("approval_task"))
                return TaskResourceSubtypeEnum.ApprovalTask;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TaskResourceSubtypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TaskResourceSubtypeEnumToJsonValue(TaskResourceSubtypeEnum? value)
        {
            if (value == TaskResourceSubtypeEnum.DefaultTask)
                return "default_task";

            if (value == TaskResourceSubtypeEnum.MilestoneTask)
                return "milestone_task";

            if (value == TaskResourceSubtypeEnum.ApprovalTask)
                return "approval_task";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of TaskResourceSubtype
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<TaskResourceSubtypeEnum?> TaskResourceSubtypeOption { get; private set; }

        /// <summary>
        /// The subtype of the task that will be created from this template.
        /// </summary>
        /// <value>The subtype of the task that will be created from this template.</value>
        /* <example>default_task</example> */
        [JsonPropertyName("task_resource_subtype")]
        public TaskResourceSubtypeEnum? TaskResourceSubtype { get { return this.TaskResourceSubtypeOption; } set { this.TaskResourceSubtypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Name of the task that will be created from this template.
        /// </summary>
        /// <value>Name of the task that will be created from this template.</value>
        /* <example>Bug Report</example> */
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TaskTemplateRecipeCompact {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  TaskResourceSubtype: ").Append(TaskResourceSubtype).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TaskTemplateRecipeCompact" />
    /// </summary>
    public class TaskTemplateRecipeCompactJsonConverter : JsonConverter<TaskTemplateRecipeCompact>
    {
        /// <summary>
        /// Deserializes json to <see cref="TaskTemplateRecipeCompact" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TaskTemplateRecipeCompact Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<TaskTemplateRecipeCompact.TaskResourceSubtypeEnum?> taskResourceSubtype = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "task_resource_subtype":
                            string? taskResourceSubtypeRawValue = utf8JsonReader.GetString();
                            if (taskResourceSubtypeRawValue != null)
                                taskResourceSubtype = new Option<TaskTemplateRecipeCompact.TaskResourceSubtypeEnum?>(TaskTemplateRecipeCompact.TaskResourceSubtypeEnumFromStringOrDefault(taskResourceSubtypeRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class TaskTemplateRecipeCompact.");

            if (taskResourceSubtype.IsSet && taskResourceSubtype.Value == null)
                throw new ArgumentNullException(nameof(taskResourceSubtype), "Property is not nullable for class TaskTemplateRecipeCompact.");

            return new TaskTemplateRecipeCompact(name, taskResourceSubtype);
        }

        /// <summary>
        /// Serializes a <see cref="TaskTemplateRecipeCompact" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="taskTemplateRecipeCompact"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TaskTemplateRecipeCompact taskTemplateRecipeCompact, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, taskTemplateRecipeCompact, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TaskTemplateRecipeCompact" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="taskTemplateRecipeCompact"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TaskTemplateRecipeCompact taskTemplateRecipeCompact, JsonSerializerOptions jsonSerializerOptions)
        {
            if (taskTemplateRecipeCompact.NameOption.IsSet && taskTemplateRecipeCompact.Name == null)
                throw new ArgumentNullException(nameof(taskTemplateRecipeCompact.Name), "Property is required for class TaskTemplateRecipeCompact.");

            if (taskTemplateRecipeCompact.NameOption.IsSet)
                writer.WriteString("name", taskTemplateRecipeCompact.Name);

            var taskResourceSubtypeRawValue = TaskTemplateRecipeCompact.TaskResourceSubtypeEnumToJsonValue(taskTemplateRecipeCompact.TaskResourceSubtypeOption.Value!.Value);
            writer.WriteString("task_resource_subtype", taskResourceSubtypeRawValue);
        }
    }
}
