// <auto-generated>
/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AsanaApiClient.Client;

namespace AsanaApiClient.Model
{
    /// <summary>
    /// TeamResponse
    /// </summary>
    public partial class TeamResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TeamResponse" /> class.
        /// </summary>
        /// <param name="gid">Globally unique identifier of the resource, as a string.</param>
        /// <param name="resourceType">The base type of this resource.</param>
        /// <param name="name">The name of the team.</param>
        /// <param name="description">[Opt In](/docs/inputoutput-options). The description of the team. </param>
        /// <param name="htmlDescription">[Opt In](/docs/inputoutput-options). The description of the team with formatting as HTML. </param>
        /// <param name="organization">organization</param>
        /// <param name="permalinkUrl">A url that points directly to the object within Asana.</param>
        /// <param name="visibility">The visibility of the team to users in the same organization </param>
        /// <param name="editTeamNameOrDescriptionAccessLevel">Controls who can edit team name and description </param>
        /// <param name="editTeamVisibilityOrTrashTeamAccessLevel">Controls who can edit team visibility and trash teams </param>
        /// <param name="memberInviteManagementAccessLevel">Controls who can accept or deny member invites for a given team </param>
        /// <param name="guestInviteManagementAccessLevel">Controls who can accept or deny guest invites for a given team </param>
        /// <param name="joinRequestManagementAccessLevel">Controls who can accept or deny join team requests for a Membership by Request team. This field can only be updated when the team&#39;s &#x60;visibility&#x60; field is &#x60;request_to_join&#x60;. </param>
        /// <param name="teamMemberRemovalAccessLevel">Controls who can remove team members </param>
        /// <param name="teamContentManagementAccessLevel">Controls who can create and share content with the team </param>
        /// <param name="endorsed">Whether the team has been endorsed </param>
        /// <param name="customFieldSettings">Array of Custom Field Settings applied to the team.</param>
        [JsonConstructor]
        public TeamResponse(Option<string?> gid = default, Option<string?> resourceType = default, Option<string?> name = default, Option<string?> description = default, Option<string?> htmlDescription = default, Option<TeamResponseAllOfOrganization?> organization = default, Option<string?> permalinkUrl = default, Option<VisibilityEnum?> visibility = default, Option<EditTeamNameOrDescriptionAccessLevelEnum?> editTeamNameOrDescriptionAccessLevel = default, Option<EditTeamVisibilityOrTrashTeamAccessLevelEnum?> editTeamVisibilityOrTrashTeamAccessLevel = default, Option<MemberInviteManagementAccessLevelEnum?> memberInviteManagementAccessLevel = default, Option<GuestInviteManagementAccessLevelEnum?> guestInviteManagementAccessLevel = default, Option<JoinRequestManagementAccessLevelEnum?> joinRequestManagementAccessLevel = default, Option<TeamMemberRemovalAccessLevelEnum?> teamMemberRemovalAccessLevel = default, Option<TeamContentManagementAccessLevelEnum?> teamContentManagementAccessLevel = default, Option<bool?> endorsed = default, Option<List<CustomFieldSettingResponse>?> customFieldSettings = default)
        {
            GidOption = gid;
            ResourceTypeOption = resourceType;
            NameOption = name;
            DescriptionOption = description;
            HtmlDescriptionOption = htmlDescription;
            OrganizationOption = organization;
            PermalinkUrlOption = permalinkUrl;
            VisibilityOption = visibility;
            EditTeamNameOrDescriptionAccessLevelOption = editTeamNameOrDescriptionAccessLevel;
            EditTeamVisibilityOrTrashTeamAccessLevelOption = editTeamVisibilityOrTrashTeamAccessLevel;
            MemberInviteManagementAccessLevelOption = memberInviteManagementAccessLevel;
            GuestInviteManagementAccessLevelOption = guestInviteManagementAccessLevel;
            JoinRequestManagementAccessLevelOption = joinRequestManagementAccessLevel;
            TeamMemberRemovalAccessLevelOption = teamMemberRemovalAccessLevel;
            TeamContentManagementAccessLevelOption = teamContentManagementAccessLevel;
            EndorsedOption = endorsed;
            CustomFieldSettingsOption = customFieldSettings;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The visibility of the team to users in the same organization 
        /// </summary>
        /// <value>The visibility of the team to users in the same organization </value>
        public enum VisibilityEnum
        {
            /// <summary>
            /// Enum Secret for value: secret
            /// </summary>
            Secret = 1,

            /// <summary>
            /// Enum RequestToJoin for value: request_to_join
            /// </summary>
            RequestToJoin = 2,

            /// <summary>
            /// Enum Public for value: public
            /// </summary>
            Public = 3
        }

        /// <summary>
        /// Returns a <see cref="VisibilityEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static VisibilityEnum VisibilityEnumFromString(string value)
        {
            if (value.Equals("secret"))
                return VisibilityEnum.Secret;

            if (value.Equals("request_to_join"))
                return VisibilityEnum.RequestToJoin;

            if (value.Equals("public"))
                return VisibilityEnum.Public;

            throw new NotImplementedException($"Could not convert value to type VisibilityEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="VisibilityEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static VisibilityEnum? VisibilityEnumFromStringOrDefault(string value)
        {
            if (value.Equals("secret"))
                return VisibilityEnum.Secret;

            if (value.Equals("request_to_join"))
                return VisibilityEnum.RequestToJoin;

            if (value.Equals("public"))
                return VisibilityEnum.Public;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="VisibilityEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string VisibilityEnumToJsonValue(VisibilityEnum? value)
        {
            if (value == VisibilityEnum.Secret)
                return "secret";

            if (value == VisibilityEnum.RequestToJoin)
                return "request_to_join";

            if (value == VisibilityEnum.Public)
                return "public";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Visibility
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<VisibilityEnum?> VisibilityOption { get; private set; }

        /// <summary>
        /// The visibility of the team to users in the same organization 
        /// </summary>
        /// <value>The visibility of the team to users in the same organization </value>
        [JsonPropertyName("visibility")]
        public VisibilityEnum? Visibility { get { return this.VisibilityOption; } set { this.VisibilityOption = new(value); } }

        /// <summary>
        /// Controls who can edit team name and description 
        /// </summary>
        /// <value>Controls who can edit team name and description </value>
        public enum EditTeamNameOrDescriptionAccessLevelEnum
        {
            /// <summary>
            /// Enum AllTeamMembers for value: all_team_members
            /// </summary>
            AllTeamMembers = 1,

            /// <summary>
            /// Enum OnlyTeamAdmins for value: only_team_admins
            /// </summary>
            OnlyTeamAdmins = 2
        }

        /// <summary>
        /// Returns a <see cref="EditTeamNameOrDescriptionAccessLevelEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static EditTeamNameOrDescriptionAccessLevelEnum EditTeamNameOrDescriptionAccessLevelEnumFromString(string value)
        {
            if (value.Equals("all_team_members"))
                return EditTeamNameOrDescriptionAccessLevelEnum.AllTeamMembers;

            if (value.Equals("only_team_admins"))
                return EditTeamNameOrDescriptionAccessLevelEnum.OnlyTeamAdmins;

            throw new NotImplementedException($"Could not convert value to type EditTeamNameOrDescriptionAccessLevelEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="EditTeamNameOrDescriptionAccessLevelEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static EditTeamNameOrDescriptionAccessLevelEnum? EditTeamNameOrDescriptionAccessLevelEnumFromStringOrDefault(string value)
        {
            if (value.Equals("all_team_members"))
                return EditTeamNameOrDescriptionAccessLevelEnum.AllTeamMembers;

            if (value.Equals("only_team_admins"))
                return EditTeamNameOrDescriptionAccessLevelEnum.OnlyTeamAdmins;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="EditTeamNameOrDescriptionAccessLevelEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string EditTeamNameOrDescriptionAccessLevelEnumToJsonValue(EditTeamNameOrDescriptionAccessLevelEnum? value)
        {
            if (value == EditTeamNameOrDescriptionAccessLevelEnum.AllTeamMembers)
                return "all_team_members";

            if (value == EditTeamNameOrDescriptionAccessLevelEnum.OnlyTeamAdmins)
                return "only_team_admins";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of EditTeamNameOrDescriptionAccessLevel
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<EditTeamNameOrDescriptionAccessLevelEnum?> EditTeamNameOrDescriptionAccessLevelOption { get; private set; }

        /// <summary>
        /// Controls who can edit team name and description 
        /// </summary>
        /// <value>Controls who can edit team name and description </value>
        [JsonPropertyName("edit_team_name_or_description_access_level")]
        public EditTeamNameOrDescriptionAccessLevelEnum? EditTeamNameOrDescriptionAccessLevel { get { return this.EditTeamNameOrDescriptionAccessLevelOption; } set { this.EditTeamNameOrDescriptionAccessLevelOption = new(value); } }

        /// <summary>
        /// Controls who can edit team visibility and trash teams 
        /// </summary>
        /// <value>Controls who can edit team visibility and trash teams </value>
        public enum EditTeamVisibilityOrTrashTeamAccessLevelEnum
        {
            /// <summary>
            /// Enum AllTeamMembers for value: all_team_members
            /// </summary>
            AllTeamMembers = 1,

            /// <summary>
            /// Enum OnlyTeamAdmins for value: only_team_admins
            /// </summary>
            OnlyTeamAdmins = 2
        }

        /// <summary>
        /// Returns a <see cref="EditTeamVisibilityOrTrashTeamAccessLevelEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static EditTeamVisibilityOrTrashTeamAccessLevelEnum EditTeamVisibilityOrTrashTeamAccessLevelEnumFromString(string value)
        {
            if (value.Equals("all_team_members"))
                return EditTeamVisibilityOrTrashTeamAccessLevelEnum.AllTeamMembers;

            if (value.Equals("only_team_admins"))
                return EditTeamVisibilityOrTrashTeamAccessLevelEnum.OnlyTeamAdmins;

            throw new NotImplementedException($"Could not convert value to type EditTeamVisibilityOrTrashTeamAccessLevelEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="EditTeamVisibilityOrTrashTeamAccessLevelEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static EditTeamVisibilityOrTrashTeamAccessLevelEnum? EditTeamVisibilityOrTrashTeamAccessLevelEnumFromStringOrDefault(string value)
        {
            if (value.Equals("all_team_members"))
                return EditTeamVisibilityOrTrashTeamAccessLevelEnum.AllTeamMembers;

            if (value.Equals("only_team_admins"))
                return EditTeamVisibilityOrTrashTeamAccessLevelEnum.OnlyTeamAdmins;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="EditTeamVisibilityOrTrashTeamAccessLevelEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string EditTeamVisibilityOrTrashTeamAccessLevelEnumToJsonValue(EditTeamVisibilityOrTrashTeamAccessLevelEnum? value)
        {
            if (value == EditTeamVisibilityOrTrashTeamAccessLevelEnum.AllTeamMembers)
                return "all_team_members";

            if (value == EditTeamVisibilityOrTrashTeamAccessLevelEnum.OnlyTeamAdmins)
                return "only_team_admins";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of EditTeamVisibilityOrTrashTeamAccessLevel
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<EditTeamVisibilityOrTrashTeamAccessLevelEnum?> EditTeamVisibilityOrTrashTeamAccessLevelOption { get; private set; }

        /// <summary>
        /// Controls who can edit team visibility and trash teams 
        /// </summary>
        /// <value>Controls who can edit team visibility and trash teams </value>
        [JsonPropertyName("edit_team_visibility_or_trash_team_access_level")]
        public EditTeamVisibilityOrTrashTeamAccessLevelEnum? EditTeamVisibilityOrTrashTeamAccessLevel { get { return this.EditTeamVisibilityOrTrashTeamAccessLevelOption; } set { this.EditTeamVisibilityOrTrashTeamAccessLevelOption = new(value); } }

        /// <summary>
        /// Controls who can accept or deny member invites for a given team 
        /// </summary>
        /// <value>Controls who can accept or deny member invites for a given team </value>
        public enum MemberInviteManagementAccessLevelEnum
        {
            /// <summary>
            /// Enum AllTeamMembers for value: all_team_members
            /// </summary>
            AllTeamMembers = 1,

            /// <summary>
            /// Enum OnlyTeamAdmins for value: only_team_admins
            /// </summary>
            OnlyTeamAdmins = 2
        }

        /// <summary>
        /// Returns a <see cref="MemberInviteManagementAccessLevelEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static MemberInviteManagementAccessLevelEnum MemberInviteManagementAccessLevelEnumFromString(string value)
        {
            if (value.Equals("all_team_members"))
                return MemberInviteManagementAccessLevelEnum.AllTeamMembers;

            if (value.Equals("only_team_admins"))
                return MemberInviteManagementAccessLevelEnum.OnlyTeamAdmins;

            throw new NotImplementedException($"Could not convert value to type MemberInviteManagementAccessLevelEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="MemberInviteManagementAccessLevelEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static MemberInviteManagementAccessLevelEnum? MemberInviteManagementAccessLevelEnumFromStringOrDefault(string value)
        {
            if (value.Equals("all_team_members"))
                return MemberInviteManagementAccessLevelEnum.AllTeamMembers;

            if (value.Equals("only_team_admins"))
                return MemberInviteManagementAccessLevelEnum.OnlyTeamAdmins;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="MemberInviteManagementAccessLevelEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string MemberInviteManagementAccessLevelEnumToJsonValue(MemberInviteManagementAccessLevelEnum? value)
        {
            if (value == MemberInviteManagementAccessLevelEnum.AllTeamMembers)
                return "all_team_members";

            if (value == MemberInviteManagementAccessLevelEnum.OnlyTeamAdmins)
                return "only_team_admins";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of MemberInviteManagementAccessLevel
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<MemberInviteManagementAccessLevelEnum?> MemberInviteManagementAccessLevelOption { get; private set; }

        /// <summary>
        /// Controls who can accept or deny member invites for a given team 
        /// </summary>
        /// <value>Controls who can accept or deny member invites for a given team </value>
        [JsonPropertyName("member_invite_management_access_level")]
        public MemberInviteManagementAccessLevelEnum? MemberInviteManagementAccessLevel { get { return this.MemberInviteManagementAccessLevelOption; } set { this.MemberInviteManagementAccessLevelOption = new(value); } }

        /// <summary>
        /// Controls who can accept or deny guest invites for a given team 
        /// </summary>
        /// <value>Controls who can accept or deny guest invites for a given team </value>
        public enum GuestInviteManagementAccessLevelEnum
        {
            /// <summary>
            /// Enum AllTeamMembers for value: all_team_members
            /// </summary>
            AllTeamMembers = 1,

            /// <summary>
            /// Enum OnlyTeamAdmins for value: only_team_admins
            /// </summary>
            OnlyTeamAdmins = 2
        }

        /// <summary>
        /// Returns a <see cref="GuestInviteManagementAccessLevelEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static GuestInviteManagementAccessLevelEnum GuestInviteManagementAccessLevelEnumFromString(string value)
        {
            if (value.Equals("all_team_members"))
                return GuestInviteManagementAccessLevelEnum.AllTeamMembers;

            if (value.Equals("only_team_admins"))
                return GuestInviteManagementAccessLevelEnum.OnlyTeamAdmins;

            throw new NotImplementedException($"Could not convert value to type GuestInviteManagementAccessLevelEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="GuestInviteManagementAccessLevelEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static GuestInviteManagementAccessLevelEnum? GuestInviteManagementAccessLevelEnumFromStringOrDefault(string value)
        {
            if (value.Equals("all_team_members"))
                return GuestInviteManagementAccessLevelEnum.AllTeamMembers;

            if (value.Equals("only_team_admins"))
                return GuestInviteManagementAccessLevelEnum.OnlyTeamAdmins;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="GuestInviteManagementAccessLevelEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string GuestInviteManagementAccessLevelEnumToJsonValue(GuestInviteManagementAccessLevelEnum? value)
        {
            if (value == GuestInviteManagementAccessLevelEnum.AllTeamMembers)
                return "all_team_members";

            if (value == GuestInviteManagementAccessLevelEnum.OnlyTeamAdmins)
                return "only_team_admins";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of GuestInviteManagementAccessLevel
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<GuestInviteManagementAccessLevelEnum?> GuestInviteManagementAccessLevelOption { get; private set; }

        /// <summary>
        /// Controls who can accept or deny guest invites for a given team 
        /// </summary>
        /// <value>Controls who can accept or deny guest invites for a given team </value>
        [JsonPropertyName("guest_invite_management_access_level")]
        public GuestInviteManagementAccessLevelEnum? GuestInviteManagementAccessLevel { get { return this.GuestInviteManagementAccessLevelOption; } set { this.GuestInviteManagementAccessLevelOption = new(value); } }

        /// <summary>
        /// Controls who can accept or deny join team requests for a Membership by Request team. This field can only be updated when the team&#39;s &#x60;visibility&#x60; field is &#x60;request_to_join&#x60;. 
        /// </summary>
        /// <value>Controls who can accept or deny join team requests for a Membership by Request team. This field can only be updated when the team&#39;s &#x60;visibility&#x60; field is &#x60;request_to_join&#x60;. </value>
        public enum JoinRequestManagementAccessLevelEnum
        {
            /// <summary>
            /// Enum AllTeamMembers for value: all_team_members
            /// </summary>
            AllTeamMembers = 1,

            /// <summary>
            /// Enum OnlyTeamAdmins for value: only_team_admins
            /// </summary>
            OnlyTeamAdmins = 2
        }

        /// <summary>
        /// Returns a <see cref="JoinRequestManagementAccessLevelEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static JoinRequestManagementAccessLevelEnum JoinRequestManagementAccessLevelEnumFromString(string value)
        {
            if (value.Equals("all_team_members"))
                return JoinRequestManagementAccessLevelEnum.AllTeamMembers;

            if (value.Equals("only_team_admins"))
                return JoinRequestManagementAccessLevelEnum.OnlyTeamAdmins;

            throw new NotImplementedException($"Could not convert value to type JoinRequestManagementAccessLevelEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="JoinRequestManagementAccessLevelEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static JoinRequestManagementAccessLevelEnum? JoinRequestManagementAccessLevelEnumFromStringOrDefault(string value)
        {
            if (value.Equals("all_team_members"))
                return JoinRequestManagementAccessLevelEnum.AllTeamMembers;

            if (value.Equals("only_team_admins"))
                return JoinRequestManagementAccessLevelEnum.OnlyTeamAdmins;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="JoinRequestManagementAccessLevelEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string JoinRequestManagementAccessLevelEnumToJsonValue(JoinRequestManagementAccessLevelEnum? value)
        {
            if (value == JoinRequestManagementAccessLevelEnum.AllTeamMembers)
                return "all_team_members";

            if (value == JoinRequestManagementAccessLevelEnum.OnlyTeamAdmins)
                return "only_team_admins";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of JoinRequestManagementAccessLevel
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<JoinRequestManagementAccessLevelEnum?> JoinRequestManagementAccessLevelOption { get; private set; }

        /// <summary>
        /// Controls who can accept or deny join team requests for a Membership by Request team. This field can only be updated when the team&#39;s &#x60;visibility&#x60; field is &#x60;request_to_join&#x60;. 
        /// </summary>
        /// <value>Controls who can accept or deny join team requests for a Membership by Request team. This field can only be updated when the team&#39;s &#x60;visibility&#x60; field is &#x60;request_to_join&#x60;. </value>
        [JsonPropertyName("join_request_management_access_level")]
        public JoinRequestManagementAccessLevelEnum? JoinRequestManagementAccessLevel { get { return this.JoinRequestManagementAccessLevelOption; } set { this.JoinRequestManagementAccessLevelOption = new(value); } }

        /// <summary>
        /// Controls who can remove team members 
        /// </summary>
        /// <value>Controls who can remove team members </value>
        public enum TeamMemberRemovalAccessLevelEnum
        {
            /// <summary>
            /// Enum AllTeamMembers for value: all_team_members
            /// </summary>
            AllTeamMembers = 1,

            /// <summary>
            /// Enum OnlyTeamAdmins for value: only_team_admins
            /// </summary>
            OnlyTeamAdmins = 2
        }

        /// <summary>
        /// Returns a <see cref="TeamMemberRemovalAccessLevelEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TeamMemberRemovalAccessLevelEnum TeamMemberRemovalAccessLevelEnumFromString(string value)
        {
            if (value.Equals("all_team_members"))
                return TeamMemberRemovalAccessLevelEnum.AllTeamMembers;

            if (value.Equals("only_team_admins"))
                return TeamMemberRemovalAccessLevelEnum.OnlyTeamAdmins;

            throw new NotImplementedException($"Could not convert value to type TeamMemberRemovalAccessLevelEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TeamMemberRemovalAccessLevelEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TeamMemberRemovalAccessLevelEnum? TeamMemberRemovalAccessLevelEnumFromStringOrDefault(string value)
        {
            if (value.Equals("all_team_members"))
                return TeamMemberRemovalAccessLevelEnum.AllTeamMembers;

            if (value.Equals("only_team_admins"))
                return TeamMemberRemovalAccessLevelEnum.OnlyTeamAdmins;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TeamMemberRemovalAccessLevelEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TeamMemberRemovalAccessLevelEnumToJsonValue(TeamMemberRemovalAccessLevelEnum? value)
        {
            if (value == TeamMemberRemovalAccessLevelEnum.AllTeamMembers)
                return "all_team_members";

            if (value == TeamMemberRemovalAccessLevelEnum.OnlyTeamAdmins)
                return "only_team_admins";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of TeamMemberRemovalAccessLevel
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<TeamMemberRemovalAccessLevelEnum?> TeamMemberRemovalAccessLevelOption { get; private set; }

        /// <summary>
        /// Controls who can remove team members 
        /// </summary>
        /// <value>Controls who can remove team members </value>
        [JsonPropertyName("team_member_removal_access_level")]
        public TeamMemberRemovalAccessLevelEnum? TeamMemberRemovalAccessLevel { get { return this.TeamMemberRemovalAccessLevelOption; } set { this.TeamMemberRemovalAccessLevelOption = new(value); } }

        /// <summary>
        /// Controls who can create and share content with the team 
        /// </summary>
        /// <value>Controls who can create and share content with the team </value>
        public enum TeamContentManagementAccessLevelEnum
        {
            /// <summary>
            /// Enum NoRestriction for value: no_restriction
            /// </summary>
            NoRestriction = 1,

            /// <summary>
            /// Enum OnlyTeamAdmins for value: only_team_admins
            /// </summary>
            OnlyTeamAdmins = 2
        }

        /// <summary>
        /// Returns a <see cref="TeamContentManagementAccessLevelEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TeamContentManagementAccessLevelEnum TeamContentManagementAccessLevelEnumFromString(string value)
        {
            if (value.Equals("no_restriction"))
                return TeamContentManagementAccessLevelEnum.NoRestriction;

            if (value.Equals("only_team_admins"))
                return TeamContentManagementAccessLevelEnum.OnlyTeamAdmins;

            throw new NotImplementedException($"Could not convert value to type TeamContentManagementAccessLevelEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TeamContentManagementAccessLevelEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TeamContentManagementAccessLevelEnum? TeamContentManagementAccessLevelEnumFromStringOrDefault(string value)
        {
            if (value.Equals("no_restriction"))
                return TeamContentManagementAccessLevelEnum.NoRestriction;

            if (value.Equals("only_team_admins"))
                return TeamContentManagementAccessLevelEnum.OnlyTeamAdmins;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TeamContentManagementAccessLevelEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TeamContentManagementAccessLevelEnumToJsonValue(TeamContentManagementAccessLevelEnum? value)
        {
            if (value == TeamContentManagementAccessLevelEnum.NoRestriction)
                return "no_restriction";

            if (value == TeamContentManagementAccessLevelEnum.OnlyTeamAdmins)
                return "only_team_admins";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of TeamContentManagementAccessLevel
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<TeamContentManagementAccessLevelEnum?> TeamContentManagementAccessLevelOption { get; private set; }

        /// <summary>
        /// Controls who can create and share content with the team 
        /// </summary>
        /// <value>Controls who can create and share content with the team </value>
        [JsonPropertyName("team_content_management_access_level")]
        public TeamContentManagementAccessLevelEnum? TeamContentManagementAccessLevel { get { return this.TeamContentManagementAccessLevelOption; } set { this.TeamContentManagementAccessLevelOption = new(value); } }

        /// <summary>
        /// Used to track the state of Gid
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> GidOption { get; }

        /// <summary>
        /// Globally unique identifier of the resource, as a string.
        /// </summary>
        /// <value>Globally unique identifier of the resource, as a string.</value>
        /* <example>12345</example> */
        [JsonPropertyName("gid")]
        public string? Gid { get { return this.GidOption; } }

        /// <summary>
        /// Used to track the state of ResourceType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ResourceTypeOption { get; }

        /// <summary>
        /// The base type of this resource.
        /// </summary>
        /// <value>The base type of this resource.</value>
        /* <example>team</example> */
        [JsonPropertyName("resource_type")]
        public string? ResourceType { get { return this.ResourceTypeOption; } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// The name of the team.
        /// </summary>
        /// <value>The name of the team.</value>
        /* <example>Marketing</example> */
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// [Opt In](/docs/inputoutput-options). The description of the team. 
        /// </summary>
        /// <value>[Opt In](/docs/inputoutput-options). The description of the team. </value>
        /* <example>All developers should be members of this team.</example> */
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of HtmlDescription
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> HtmlDescriptionOption { get; private set; }

        /// <summary>
        /// [Opt In](/docs/inputoutput-options). The description of the team with formatting as HTML. 
        /// </summary>
        /// <value>[Opt In](/docs/inputoutput-options). The description of the team with formatting as HTML. </value>
        /* <example>&lt;body&gt;&lt;em&gt;All&lt;/em&gt; developers should be members of this team.&lt;/body&gt;</example> */
        [JsonPropertyName("html_description")]
        public string? HtmlDescription { get { return this.HtmlDescriptionOption; } set { this.HtmlDescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Organization
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<TeamResponseAllOfOrganization?> OrganizationOption { get; private set; }

        /// <summary>
        /// Gets or Sets Organization
        /// </summary>
        [JsonPropertyName("organization")]
        public TeamResponseAllOfOrganization? Organization { get { return this.OrganizationOption; } set { this.OrganizationOption = new(value); } }

        /// <summary>
        /// Used to track the state of PermalinkUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PermalinkUrlOption { get; }

        /// <summary>
        /// A url that points directly to the object within Asana.
        /// </summary>
        /// <value>A url that points directly to the object within Asana.</value>
        /* <example>https://app.asana.com/0/resource/123456789/list</example> */
        [JsonPropertyName("permalink_url")]
        public string? PermalinkUrl { get { return this.PermalinkUrlOption; } }

        /// <summary>
        /// Used to track the state of Endorsed
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EndorsedOption { get; private set; }

        /// <summary>
        /// Whether the team has been endorsed 
        /// </summary>
        /// <value>Whether the team has been endorsed </value>
        /* <example>false</example> */
        [JsonPropertyName("endorsed")]
        public bool? Endorsed { get { return this.EndorsedOption; } set { this.EndorsedOption = new(value); } }

        /// <summary>
        /// Used to track the state of CustomFieldSettings
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CustomFieldSettingResponse>?> CustomFieldSettingsOption { get; private set; }

        /// <summary>
        /// Array of Custom Field Settings applied to the team.
        /// </summary>
        /// <value>Array of Custom Field Settings applied to the team.</value>
        [JsonPropertyName("custom_field_settings")]
        public List<CustomFieldSettingResponse>? CustomFieldSettings { get { return this.CustomFieldSettingsOption; } set { this.CustomFieldSettingsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TeamResponse {\n");
            sb.Append("  Gid: ").Append(Gid).Append("\n");
            sb.Append("  ResourceType: ").Append(ResourceType).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  HtmlDescription: ").Append(HtmlDescription).Append("\n");
            sb.Append("  Organization: ").Append(Organization).Append("\n");
            sb.Append("  PermalinkUrl: ").Append(PermalinkUrl).Append("\n");
            sb.Append("  Visibility: ").Append(Visibility).Append("\n");
            sb.Append("  EditTeamNameOrDescriptionAccessLevel: ").Append(EditTeamNameOrDescriptionAccessLevel).Append("\n");
            sb.Append("  EditTeamVisibilityOrTrashTeamAccessLevel: ").Append(EditTeamVisibilityOrTrashTeamAccessLevel).Append("\n");
            sb.Append("  MemberInviteManagementAccessLevel: ").Append(MemberInviteManagementAccessLevel).Append("\n");
            sb.Append("  GuestInviteManagementAccessLevel: ").Append(GuestInviteManagementAccessLevel).Append("\n");
            sb.Append("  JoinRequestManagementAccessLevel: ").Append(JoinRequestManagementAccessLevel).Append("\n");
            sb.Append("  TeamMemberRemovalAccessLevel: ").Append(TeamMemberRemovalAccessLevel).Append("\n");
            sb.Append("  TeamContentManagementAccessLevel: ").Append(TeamContentManagementAccessLevel).Append("\n");
            sb.Append("  Endorsed: ").Append(Endorsed).Append("\n");
            sb.Append("  CustomFieldSettings: ").Append(CustomFieldSettings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TeamResponse" />
    /// </summary>
    public class TeamResponseJsonConverter : JsonConverter<TeamResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="TeamResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TeamResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> gid = default;
            Option<string?> resourceType = default;
            Option<string?> name = default;
            Option<string?> description = default;
            Option<string?> htmlDescription = default;
            Option<TeamResponseAllOfOrganization?> organization = default;
            Option<string?> permalinkUrl = default;
            Option<TeamResponse.VisibilityEnum?> visibility = default;
            Option<TeamResponse.EditTeamNameOrDescriptionAccessLevelEnum?> editTeamNameOrDescriptionAccessLevel = default;
            Option<TeamResponse.EditTeamVisibilityOrTrashTeamAccessLevelEnum?> editTeamVisibilityOrTrashTeamAccessLevel = default;
            Option<TeamResponse.MemberInviteManagementAccessLevelEnum?> memberInviteManagementAccessLevel = default;
            Option<TeamResponse.GuestInviteManagementAccessLevelEnum?> guestInviteManagementAccessLevel = default;
            Option<TeamResponse.JoinRequestManagementAccessLevelEnum?> joinRequestManagementAccessLevel = default;
            Option<TeamResponse.TeamMemberRemovalAccessLevelEnum?> teamMemberRemovalAccessLevel = default;
            Option<TeamResponse.TeamContentManagementAccessLevelEnum?> teamContentManagementAccessLevel = default;
            Option<bool?> endorsed = default;
            Option<List<CustomFieldSettingResponse>?> customFieldSettings = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "gid":
                            gid = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "resource_type":
                            resourceType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "html_description":
                            htmlDescription = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "organization":
                            organization = new Option<TeamResponseAllOfOrganization?>(JsonSerializer.Deserialize<TeamResponseAllOfOrganization>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "permalink_url":
                            permalinkUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "visibility":
                            string? visibilityRawValue = utf8JsonReader.GetString();
                            if (visibilityRawValue != null)
                                visibility = new Option<TeamResponse.VisibilityEnum?>(TeamResponse.VisibilityEnumFromStringOrDefault(visibilityRawValue));
                            break;
                        case "edit_team_name_or_description_access_level":
                            string? editTeamNameOrDescriptionAccessLevelRawValue = utf8JsonReader.GetString();
                            if (editTeamNameOrDescriptionAccessLevelRawValue != null)
                                editTeamNameOrDescriptionAccessLevel = new Option<TeamResponse.EditTeamNameOrDescriptionAccessLevelEnum?>(TeamResponse.EditTeamNameOrDescriptionAccessLevelEnumFromStringOrDefault(editTeamNameOrDescriptionAccessLevelRawValue));
                            break;
                        case "edit_team_visibility_or_trash_team_access_level":
                            string? editTeamVisibilityOrTrashTeamAccessLevelRawValue = utf8JsonReader.GetString();
                            if (editTeamVisibilityOrTrashTeamAccessLevelRawValue != null)
                                editTeamVisibilityOrTrashTeamAccessLevel = new Option<TeamResponse.EditTeamVisibilityOrTrashTeamAccessLevelEnum?>(TeamResponse.EditTeamVisibilityOrTrashTeamAccessLevelEnumFromStringOrDefault(editTeamVisibilityOrTrashTeamAccessLevelRawValue));
                            break;
                        case "member_invite_management_access_level":
                            string? memberInviteManagementAccessLevelRawValue = utf8JsonReader.GetString();
                            if (memberInviteManagementAccessLevelRawValue != null)
                                memberInviteManagementAccessLevel = new Option<TeamResponse.MemberInviteManagementAccessLevelEnum?>(TeamResponse.MemberInviteManagementAccessLevelEnumFromStringOrDefault(memberInviteManagementAccessLevelRawValue));
                            break;
                        case "guest_invite_management_access_level":
                            string? guestInviteManagementAccessLevelRawValue = utf8JsonReader.GetString();
                            if (guestInviteManagementAccessLevelRawValue != null)
                                guestInviteManagementAccessLevel = new Option<TeamResponse.GuestInviteManagementAccessLevelEnum?>(TeamResponse.GuestInviteManagementAccessLevelEnumFromStringOrDefault(guestInviteManagementAccessLevelRawValue));
                            break;
                        case "join_request_management_access_level":
                            string? joinRequestManagementAccessLevelRawValue = utf8JsonReader.GetString();
                            if (joinRequestManagementAccessLevelRawValue != null)
                                joinRequestManagementAccessLevel = new Option<TeamResponse.JoinRequestManagementAccessLevelEnum?>(TeamResponse.JoinRequestManagementAccessLevelEnumFromStringOrDefault(joinRequestManagementAccessLevelRawValue));
                            break;
                        case "team_member_removal_access_level":
                            string? teamMemberRemovalAccessLevelRawValue = utf8JsonReader.GetString();
                            if (teamMemberRemovalAccessLevelRawValue != null)
                                teamMemberRemovalAccessLevel = new Option<TeamResponse.TeamMemberRemovalAccessLevelEnum?>(TeamResponse.TeamMemberRemovalAccessLevelEnumFromStringOrDefault(teamMemberRemovalAccessLevelRawValue));
                            break;
                        case "team_content_management_access_level":
                            string? teamContentManagementAccessLevelRawValue = utf8JsonReader.GetString();
                            if (teamContentManagementAccessLevelRawValue != null)
                                teamContentManagementAccessLevel = new Option<TeamResponse.TeamContentManagementAccessLevelEnum?>(TeamResponse.TeamContentManagementAccessLevelEnumFromStringOrDefault(teamContentManagementAccessLevelRawValue));
                            break;
                        case "endorsed":
                            endorsed = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "custom_field_settings":
                            customFieldSettings = new Option<List<CustomFieldSettingResponse>?>(JsonSerializer.Deserialize<List<CustomFieldSettingResponse>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (gid.IsSet && gid.Value == null)
                throw new ArgumentNullException(nameof(gid), "Property is not nullable for class TeamResponse.");

            if (resourceType.IsSet && resourceType.Value == null)
                throw new ArgumentNullException(nameof(resourceType), "Property is not nullable for class TeamResponse.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class TeamResponse.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class TeamResponse.");

            if (htmlDescription.IsSet && htmlDescription.Value == null)
                throw new ArgumentNullException(nameof(htmlDescription), "Property is not nullable for class TeamResponse.");

            if (organization.IsSet && organization.Value == null)
                throw new ArgumentNullException(nameof(organization), "Property is not nullable for class TeamResponse.");

            if (permalinkUrl.IsSet && permalinkUrl.Value == null)
                throw new ArgumentNullException(nameof(permalinkUrl), "Property is not nullable for class TeamResponse.");

            if (visibility.IsSet && visibility.Value == null)
                throw new ArgumentNullException(nameof(visibility), "Property is not nullable for class TeamResponse.");

            if (editTeamNameOrDescriptionAccessLevel.IsSet && editTeamNameOrDescriptionAccessLevel.Value == null)
                throw new ArgumentNullException(nameof(editTeamNameOrDescriptionAccessLevel), "Property is not nullable for class TeamResponse.");

            if (editTeamVisibilityOrTrashTeamAccessLevel.IsSet && editTeamVisibilityOrTrashTeamAccessLevel.Value == null)
                throw new ArgumentNullException(nameof(editTeamVisibilityOrTrashTeamAccessLevel), "Property is not nullable for class TeamResponse.");

            if (memberInviteManagementAccessLevel.IsSet && memberInviteManagementAccessLevel.Value == null)
                throw new ArgumentNullException(nameof(memberInviteManagementAccessLevel), "Property is not nullable for class TeamResponse.");

            if (guestInviteManagementAccessLevel.IsSet && guestInviteManagementAccessLevel.Value == null)
                throw new ArgumentNullException(nameof(guestInviteManagementAccessLevel), "Property is not nullable for class TeamResponse.");

            if (joinRequestManagementAccessLevel.IsSet && joinRequestManagementAccessLevel.Value == null)
                throw new ArgumentNullException(nameof(joinRequestManagementAccessLevel), "Property is not nullable for class TeamResponse.");

            if (teamMemberRemovalAccessLevel.IsSet && teamMemberRemovalAccessLevel.Value == null)
                throw new ArgumentNullException(nameof(teamMemberRemovalAccessLevel), "Property is not nullable for class TeamResponse.");

            if (teamContentManagementAccessLevel.IsSet && teamContentManagementAccessLevel.Value == null)
                throw new ArgumentNullException(nameof(teamContentManagementAccessLevel), "Property is not nullable for class TeamResponse.");

            if (endorsed.IsSet && endorsed.Value == null)
                throw new ArgumentNullException(nameof(endorsed), "Property is not nullable for class TeamResponse.");

            if (customFieldSettings.IsSet && customFieldSettings.Value == null)
                throw new ArgumentNullException(nameof(customFieldSettings), "Property is not nullable for class TeamResponse.");

            return new TeamResponse(gid, resourceType, name, description, htmlDescription, organization, permalinkUrl, visibility, editTeamNameOrDescriptionAccessLevel, editTeamVisibilityOrTrashTeamAccessLevel, memberInviteManagementAccessLevel, guestInviteManagementAccessLevel, joinRequestManagementAccessLevel, teamMemberRemovalAccessLevel, teamContentManagementAccessLevel, endorsed, customFieldSettings);
        }

        /// <summary>
        /// Serializes a <see cref="TeamResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="teamResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TeamResponse teamResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, teamResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TeamResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="teamResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TeamResponse teamResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (teamResponse.GidOption.IsSet && teamResponse.Gid == null)
                throw new ArgumentNullException(nameof(teamResponse.Gid), "Property is required for class TeamResponse.");

            if (teamResponse.ResourceTypeOption.IsSet && teamResponse.ResourceType == null)
                throw new ArgumentNullException(nameof(teamResponse.ResourceType), "Property is required for class TeamResponse.");

            if (teamResponse.NameOption.IsSet && teamResponse.Name == null)
                throw new ArgumentNullException(nameof(teamResponse.Name), "Property is required for class TeamResponse.");

            if (teamResponse.DescriptionOption.IsSet && teamResponse.Description == null)
                throw new ArgumentNullException(nameof(teamResponse.Description), "Property is required for class TeamResponse.");

            if (teamResponse.HtmlDescriptionOption.IsSet && teamResponse.HtmlDescription == null)
                throw new ArgumentNullException(nameof(teamResponse.HtmlDescription), "Property is required for class TeamResponse.");

            if (teamResponse.OrganizationOption.IsSet && teamResponse.Organization == null)
                throw new ArgumentNullException(nameof(teamResponse.Organization), "Property is required for class TeamResponse.");

            if (teamResponse.PermalinkUrlOption.IsSet && teamResponse.PermalinkUrl == null)
                throw new ArgumentNullException(nameof(teamResponse.PermalinkUrl), "Property is required for class TeamResponse.");

            if (teamResponse.CustomFieldSettingsOption.IsSet && teamResponse.CustomFieldSettings == null)
                throw new ArgumentNullException(nameof(teamResponse.CustomFieldSettings), "Property is required for class TeamResponse.");

            if (teamResponse.GidOption.IsSet)
                writer.WriteString("gid", teamResponse.Gid);

            if (teamResponse.ResourceTypeOption.IsSet)
                writer.WriteString("resource_type", teamResponse.ResourceType);

            if (teamResponse.NameOption.IsSet)
                writer.WriteString("name", teamResponse.Name);

            if (teamResponse.DescriptionOption.IsSet)
                writer.WriteString("description", teamResponse.Description);

            if (teamResponse.HtmlDescriptionOption.IsSet)
                writer.WriteString("html_description", teamResponse.HtmlDescription);

            if (teamResponse.OrganizationOption.IsSet)
            {
                writer.WritePropertyName("organization");
                JsonSerializer.Serialize(writer, teamResponse.Organization, jsonSerializerOptions);
            }
            if (teamResponse.PermalinkUrlOption.IsSet)
                writer.WriteString("permalink_url", teamResponse.PermalinkUrl);

            var visibilityRawValue = TeamResponse.VisibilityEnumToJsonValue(teamResponse.VisibilityOption.Value!.Value);
            writer.WriteString("visibility", visibilityRawValue);
            var editTeamNameOrDescriptionAccessLevelRawValue = TeamResponse.EditTeamNameOrDescriptionAccessLevelEnumToJsonValue(teamResponse.EditTeamNameOrDescriptionAccessLevelOption.Value!.Value);
            writer.WriteString("edit_team_name_or_description_access_level", editTeamNameOrDescriptionAccessLevelRawValue);
            var editTeamVisibilityOrTrashTeamAccessLevelRawValue = TeamResponse.EditTeamVisibilityOrTrashTeamAccessLevelEnumToJsonValue(teamResponse.EditTeamVisibilityOrTrashTeamAccessLevelOption.Value!.Value);
            writer.WriteString("edit_team_visibility_or_trash_team_access_level", editTeamVisibilityOrTrashTeamAccessLevelRawValue);
            var memberInviteManagementAccessLevelRawValue = TeamResponse.MemberInviteManagementAccessLevelEnumToJsonValue(teamResponse.MemberInviteManagementAccessLevelOption.Value!.Value);
            writer.WriteString("member_invite_management_access_level", memberInviteManagementAccessLevelRawValue);
            var guestInviteManagementAccessLevelRawValue = TeamResponse.GuestInviteManagementAccessLevelEnumToJsonValue(teamResponse.GuestInviteManagementAccessLevelOption.Value!.Value);
            writer.WriteString("guest_invite_management_access_level", guestInviteManagementAccessLevelRawValue);
            var joinRequestManagementAccessLevelRawValue = TeamResponse.JoinRequestManagementAccessLevelEnumToJsonValue(teamResponse.JoinRequestManagementAccessLevelOption.Value!.Value);
            writer.WriteString("join_request_management_access_level", joinRequestManagementAccessLevelRawValue);
            var teamMemberRemovalAccessLevelRawValue = TeamResponse.TeamMemberRemovalAccessLevelEnumToJsonValue(teamResponse.TeamMemberRemovalAccessLevelOption.Value!.Value);
            writer.WriteString("team_member_removal_access_level", teamMemberRemovalAccessLevelRawValue);
            var teamContentManagementAccessLevelRawValue = TeamResponse.TeamContentManagementAccessLevelEnumToJsonValue(teamResponse.TeamContentManagementAccessLevelOption.Value!.Value);
            writer.WriteString("team_content_management_access_level", teamContentManagementAccessLevelRawValue);
            if (teamResponse.EndorsedOption.IsSet)
                writer.WriteBoolean("endorsed", teamResponse.EndorsedOption.Value!.Value);

            if (teamResponse.CustomFieldSettingsOption.IsSet)
            {
                writer.WritePropertyName("custom_field_settings");
                JsonSerializer.Serialize(writer, teamResponse.CustomFieldSettings, jsonSerializerOptions);
            }
        }
    }
}
