// <auto-generated>
/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AsanaApiClient.Client;

namespace AsanaApiClient.Model
{
    /// <summary>
    /// Webhook objects represent the state of an active subscription for a server to be updated with information from Asana. This schema represents the subscription itself, not the objects that are sent to the server. For information on those please refer to the [event](/reference/events) schema.
    /// </summary>
    public partial class WebhookCompact : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WebhookCompact" /> class.
        /// </summary>
        /// <param name="gid">Globally unique identifier of the resource, as a string.</param>
        /// <param name="resourceType">The base type of this resource.</param>
        /// <param name="active">If true, the webhook will send events - if false it is considered inactive and will not generate events.</param>
        /// <param name="resource">resource</param>
        /// <param name="target">The URL to receive the HTTP POST.</param>
        [JsonConstructor]
        public WebhookCompact(Option<string?> gid = default, Option<string?> resourceType = default, Option<bool?> active = default, Option<AsanaNamedResource?> resource = default, Option<string?> target = default)
        {
            GidOption = gid;
            ResourceTypeOption = resourceType;
            ActiveOption = active;
            ResourceOption = resource;
            TargetOption = target;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Gid
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> GidOption { get; }

        /// <summary>
        /// Globally unique identifier of the resource, as a string.
        /// </summary>
        /// <value>Globally unique identifier of the resource, as a string.</value>
        /* <example>12345</example> */
        [JsonPropertyName("gid")]
        public string? Gid { get { return this.GidOption; } }

        /// <summary>
        /// Used to track the state of ResourceType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ResourceTypeOption { get; }

        /// <summary>
        /// The base type of this resource.
        /// </summary>
        /// <value>The base type of this resource.</value>
        /* <example>webhook</example> */
        [JsonPropertyName("resource_type")]
        public string? ResourceType { get { return this.ResourceTypeOption; } }

        /// <summary>
        /// Used to track the state of Active
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ActiveOption { get; }

        /// <summary>
        /// If true, the webhook will send events - if false it is considered inactive and will not generate events.
        /// </summary>
        /// <value>If true, the webhook will send events - if false it is considered inactive and will not generate events.</value>
        /* <example>false</example> */
        [JsonPropertyName("active")]
        public bool? Active { get { return this.ActiveOption; } }

        /// <summary>
        /// Used to track the state of Resource
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<AsanaNamedResource?> ResourceOption { get; private set; }

        /// <summary>
        /// Gets or Sets Resource
        /// </summary>
        [JsonPropertyName("resource")]
        public AsanaNamedResource? Resource { get { return this.ResourceOption; } set { this.ResourceOption = new(value); } }

        /// <summary>
        /// Used to track the state of Target
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TargetOption { get; }

        /// <summary>
        /// The URL to receive the HTTP POST.
        /// </summary>
        /// <value>The URL to receive the HTTP POST.</value>
        /* <example>https://example.com/receive-webhook/7654</example> */
        [JsonPropertyName("target")]
        public string? Target { get { return this.TargetOption; } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WebhookCompact {\n");
            sb.Append("  Gid: ").Append(Gid).Append("\n");
            sb.Append("  ResourceType: ").Append(ResourceType).Append("\n");
            sb.Append("  Active: ").Append(Active).Append("\n");
            sb.Append("  Resource: ").Append(Resource).Append("\n");
            sb.Append("  Target: ").Append(Target).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WebhookCompact" />
    /// </summary>
    public class WebhookCompactJsonConverter : JsonConverter<WebhookCompact>
    {
        /// <summary>
        /// Deserializes json to <see cref="WebhookCompact" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WebhookCompact Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> gid = default;
            Option<string?> resourceType = default;
            Option<bool?> active = default;
            Option<AsanaNamedResource?> resource = default;
            Option<string?> target = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "gid":
                            gid = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "resource_type":
                            resourceType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "active":
                            active = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "resource":
                            resource = new Option<AsanaNamedResource?>(JsonSerializer.Deserialize<AsanaNamedResource>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "target":
                            target = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (gid.IsSet && gid.Value == null)
                throw new ArgumentNullException(nameof(gid), "Property is not nullable for class WebhookCompact.");

            if (resourceType.IsSet && resourceType.Value == null)
                throw new ArgumentNullException(nameof(resourceType), "Property is not nullable for class WebhookCompact.");

            if (active.IsSet && active.Value == null)
                throw new ArgumentNullException(nameof(active), "Property is not nullable for class WebhookCompact.");

            if (resource.IsSet && resource.Value == null)
                throw new ArgumentNullException(nameof(resource), "Property is not nullable for class WebhookCompact.");

            if (target.IsSet && target.Value == null)
                throw new ArgumentNullException(nameof(target), "Property is not nullable for class WebhookCompact.");

            return new WebhookCompact(gid, resourceType, active, resource, target);
        }

        /// <summary>
        /// Serializes a <see cref="WebhookCompact" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="webhookCompact"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, WebhookCompact webhookCompact, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, webhookCompact, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WebhookCompact" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="webhookCompact"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, WebhookCompact webhookCompact, JsonSerializerOptions jsonSerializerOptions)
        {
            if (webhookCompact.GidOption.IsSet && webhookCompact.Gid == null)
                throw new ArgumentNullException(nameof(webhookCompact.Gid), "Property is required for class WebhookCompact.");

            if (webhookCompact.ResourceTypeOption.IsSet && webhookCompact.ResourceType == null)
                throw new ArgumentNullException(nameof(webhookCompact.ResourceType), "Property is required for class WebhookCompact.");

            if (webhookCompact.ResourceOption.IsSet && webhookCompact.Resource == null)
                throw new ArgumentNullException(nameof(webhookCompact.Resource), "Property is required for class WebhookCompact.");

            if (webhookCompact.TargetOption.IsSet && webhookCompact.Target == null)
                throw new ArgumentNullException(nameof(webhookCompact.Target), "Property is required for class WebhookCompact.");

            if (webhookCompact.GidOption.IsSet)
                writer.WriteString("gid", webhookCompact.Gid);

            if (webhookCompact.ResourceTypeOption.IsSet)
                writer.WriteString("resource_type", webhookCompact.ResourceType);

            if (webhookCompact.ActiveOption.IsSet)
                writer.WriteBoolean("active", webhookCompact.ActiveOption.Value!.Value);

            if (webhookCompact.ResourceOption.IsSet)
            {
                writer.WritePropertyName("resource");
                JsonSerializer.Serialize(writer, webhookCompact.Resource, jsonSerializerOptions);
            }
            if (webhookCompact.TargetOption.IsSet)
                writer.WriteString("target", webhookCompact.Target);
        }
    }
}
