// <auto-generated>
/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AsanaApiClient.Client;

namespace AsanaApiClient.Model
{
    /// <summary>
    /// WorkspaceResponse
    /// </summary>
    public partial class WorkspaceResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkspaceResponse" /> class.
        /// </summary>
        /// <param name="gid">Globally unique identifier of the resource, as a string.</param>
        /// <param name="resourceType">The base type of this resource.</param>
        /// <param name="name">The name of the workspace.</param>
        /// <param name="emailDomains">The email domains that are associated with this workspace.</param>
        /// <param name="isOrganization">Whether the workspace is an *organization*.</param>
        [JsonConstructor]
        public WorkspaceResponse(Option<string?> gid = default, Option<string?> resourceType = default, Option<string?> name = default, Option<List<string>?> emailDomains = default, Option<bool?> isOrganization = default)
        {
            GidOption = gid;
            ResourceTypeOption = resourceType;
            NameOption = name;
            EmailDomainsOption = emailDomains;
            IsOrganizationOption = isOrganization;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Gid
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> GidOption { get; }

        /// <summary>
        /// Globally unique identifier of the resource, as a string.
        /// </summary>
        /// <value>Globally unique identifier of the resource, as a string.</value>
        /* <example>12345</example> */
        [JsonPropertyName("gid")]
        public string? Gid { get { return this.GidOption; } }

        /// <summary>
        /// Used to track the state of ResourceType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ResourceTypeOption { get; }

        /// <summary>
        /// The base type of this resource.
        /// </summary>
        /// <value>The base type of this resource.</value>
        /* <example>workspace</example> */
        [JsonPropertyName("resource_type")]
        public string? ResourceType { get { return this.ResourceTypeOption; } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// The name of the workspace.
        /// </summary>
        /// <value>The name of the workspace.</value>
        /* <example>My Company Workspace</example> */
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of EmailDomains
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> EmailDomainsOption { get; private set; }

        /// <summary>
        /// The email domains that are associated with this workspace.
        /// </summary>
        /// <value>The email domains that are associated with this workspace.</value>
        /* <example>[&quot;asana.com&quot;]</example> */
        [JsonPropertyName("email_domains")]
        public List<string>? EmailDomains { get { return this.EmailDomainsOption; } set { this.EmailDomainsOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsOrganization
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsOrganizationOption { get; private set; }

        /// <summary>
        /// Whether the workspace is an *organization*.
        /// </summary>
        /// <value>Whether the workspace is an *organization*.</value>
        /* <example>false</example> */
        [JsonPropertyName("is_organization")]
        public bool? IsOrganization { get { return this.IsOrganizationOption; } set { this.IsOrganizationOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkspaceResponse {\n");
            sb.Append("  Gid: ").Append(Gid).Append("\n");
            sb.Append("  ResourceType: ").Append(ResourceType).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  EmailDomains: ").Append(EmailDomains).Append("\n");
            sb.Append("  IsOrganization: ").Append(IsOrganization).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WorkspaceResponse" />
    /// </summary>
    public class WorkspaceResponseJsonConverter : JsonConverter<WorkspaceResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="WorkspaceResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WorkspaceResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> gid = default;
            Option<string?> resourceType = default;
            Option<string?> name = default;
            Option<List<string>?> emailDomains = default;
            Option<bool?> isOrganization = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "gid":
                            gid = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "resource_type":
                            resourceType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "email_domains":
                            emailDomains = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "is_organization":
                            isOrganization = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (gid.IsSet && gid.Value == null)
                throw new ArgumentNullException(nameof(gid), "Property is not nullable for class WorkspaceResponse.");

            if (resourceType.IsSet && resourceType.Value == null)
                throw new ArgumentNullException(nameof(resourceType), "Property is not nullable for class WorkspaceResponse.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class WorkspaceResponse.");

            if (emailDomains.IsSet && emailDomains.Value == null)
                throw new ArgumentNullException(nameof(emailDomains), "Property is not nullable for class WorkspaceResponse.");

            if (isOrganization.IsSet && isOrganization.Value == null)
                throw new ArgumentNullException(nameof(isOrganization), "Property is not nullable for class WorkspaceResponse.");

            return new WorkspaceResponse(gid, resourceType, name, emailDomains, isOrganization);
        }

        /// <summary>
        /// Serializes a <see cref="WorkspaceResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="workspaceResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, WorkspaceResponse workspaceResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, workspaceResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WorkspaceResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="workspaceResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, WorkspaceResponse workspaceResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (workspaceResponse.GidOption.IsSet && workspaceResponse.Gid == null)
                throw new ArgumentNullException(nameof(workspaceResponse.Gid), "Property is required for class WorkspaceResponse.");

            if (workspaceResponse.ResourceTypeOption.IsSet && workspaceResponse.ResourceType == null)
                throw new ArgumentNullException(nameof(workspaceResponse.ResourceType), "Property is required for class WorkspaceResponse.");

            if (workspaceResponse.NameOption.IsSet && workspaceResponse.Name == null)
                throw new ArgumentNullException(nameof(workspaceResponse.Name), "Property is required for class WorkspaceResponse.");

            if (workspaceResponse.EmailDomainsOption.IsSet && workspaceResponse.EmailDomains == null)
                throw new ArgumentNullException(nameof(workspaceResponse.EmailDomains), "Property is required for class WorkspaceResponse.");

            if (workspaceResponse.GidOption.IsSet)
                writer.WriteString("gid", workspaceResponse.Gid);

            if (workspaceResponse.ResourceTypeOption.IsSet)
                writer.WriteString("resource_type", workspaceResponse.ResourceType);

            if (workspaceResponse.NameOption.IsSet)
                writer.WriteString("name", workspaceResponse.Name);

            if (workspaceResponse.EmailDomainsOption.IsSet)
            {
                writer.WritePropertyName("email_domains");
                JsonSerializer.Serialize(writer, workspaceResponse.EmailDomains, jsonSerializerOptions);
            }
            if (workspaceResponse.IsOrganizationOption.IsSet)
                writer.WriteBoolean("is_organization", workspaceResponse.IsOrganizationOption.Value!.Value);
        }
    }
}
