/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AsanaApiClient.Model;
using AsanaApiClient.Client;
using System.Reflection;

namespace AsanaApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing AuditLogEventDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuditLogEventDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuditLogEventDetails
        //private AuditLogEventDetails instance;

        public AuditLogEventDetailsTests()
        {
            // TODO uncomment below to create an instance of AuditLogEventDetails
            //instance = new AuditLogEventDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuditLogEventDetails
        /// </summary>
        [Fact]
        public void AuditLogEventDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" AuditLogEventDetails
            //Assert.IsType<AuditLogEventDetails>(instance);
        }

        /// <summary>
        /// Test the property 'OldValue'
        /// </summary>
        [Fact]
        public void OldValueTest()
        {
            // TODO unit test for the property 'OldValue'
        }

        /// <summary>
        /// Test the property 'NewValue'
        /// </summary>
        [Fact]
        public void NewValueTest()
        {
            // TODO unit test for the property 'NewValue'
        }

        /// <summary>
        /// Test the property 'Group'
        /// </summary>
        [Fact]
        public void GroupTest()
        {
            // TODO unit test for the property 'Group'
        }

        /// <summary>
        /// Test the property 'SamlResponse'
        /// </summary>
        [Fact]
        public void SamlResponseTest()
        {
            // TODO unit test for the property 'SamlResponse'
        }
    }
}
