/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AsanaApiClient.Model;
using AsanaApiClient.Client;
using System.Reflection;

namespace AsanaApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CreatePortfolio201Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreatePortfolio201ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreatePortfolio201Response
        //private CreatePortfolio201Response instance;

        public CreatePortfolio201ResponseTests()
        {
            // TODO uncomment below to create an instance of CreatePortfolio201Response
            //instance = new CreatePortfolio201Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreatePortfolio201Response
        /// </summary>
        [Fact]
        public void CreatePortfolio201ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreatePortfolio201Response
            //Assert.IsType<CreatePortfolio201Response>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
