/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AsanaApiClient.Model;
using AsanaApiClient.Client;
using System.Reflection;

namespace AsanaApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CustomFieldSettingCompact
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomFieldSettingCompactTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomFieldSettingCompact
        //private CustomFieldSettingCompact instance;

        public CustomFieldSettingCompactTests()
        {
            // TODO uncomment below to create an instance of CustomFieldSettingCompact
            //instance = new CustomFieldSettingCompact();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomFieldSettingCompact
        /// </summary>
        [Fact]
        public void CustomFieldSettingCompactInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomFieldSettingCompact
            //Assert.IsType<CustomFieldSettingCompact>(instance);
        }

        /// <summary>
        /// Test the property 'Gid'
        /// </summary>
        [Fact]
        public void GidTest()
        {
            // TODO unit test for the property 'Gid'
        }

        /// <summary>
        /// Test the property 'ResourceType'
        /// </summary>
        [Fact]
        public void ResourceTypeTest()
        {
            // TODO unit test for the property 'ResourceType'
        }
    }
}
