/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AsanaApiClient.Model;
using AsanaApiClient.Client;
using System.Reflection;

namespace AsanaApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing GetEvents412Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetEvents412ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetEvents412Response
        //private GetEvents412Response instance;

        public GetEvents412ResponseTests()
        {
            // TODO uncomment below to create an instance of GetEvents412Response
            //instance = new GetEvents412Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetEvents412Response
        /// </summary>
        [Fact]
        public void GetEvents412ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetEvents412Response
            //Assert.IsType<GetEvents412Response>(instance);
        }

        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }

        /// <summary>
        /// Test the property 'Sync'
        /// </summary>
        [Fact]
        public void SyncTest()
        {
            // TODO unit test for the property 'Sync'
        }
    }
}
