/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AsanaApiClient.Model;
using AsanaApiClient.Client;
using System.Reflection;

namespace AsanaApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing GetFavoritesForUser200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetFavoritesForUser200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetFavoritesForUser200Response
        //private GetFavoritesForUser200Response instance;

        public GetFavoritesForUser200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetFavoritesForUser200Response
            //instance = new GetFavoritesForUser200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetFavoritesForUser200Response
        /// </summary>
        [Fact]
        public void GetFavoritesForUser200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetFavoritesForUser200Response
            //Assert.IsType<GetFavoritesForUser200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Fact]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }
    }
}
