/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AsanaApiClient.Model;
using AsanaApiClient.Client;
using System.Reflection;

namespace AsanaApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TaskTemplateResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaskTemplateResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TaskTemplateResponse
        //private TaskTemplateResponse instance;

        public TaskTemplateResponseTests()
        {
            // TODO uncomment below to create an instance of TaskTemplateResponse
            //instance = new TaskTemplateResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TaskTemplateResponse
        /// </summary>
        [Fact]
        public void TaskTemplateResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TaskTemplateResponse
            //Assert.IsType<TaskTemplateResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Gid'
        /// </summary>
        [Fact]
        public void GidTest()
        {
            // TODO unit test for the property 'Gid'
        }

        /// <summary>
        /// Test the property 'ResourceType'
        /// </summary>
        [Fact]
        public void ResourceTypeTest()
        {
            // TODO unit test for the property 'ResourceType'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Project'
        /// </summary>
        [Fact]
        public void ProjectTest()
        {
            // TODO unit test for the property 'Project'
        }

        /// <summary>
        /// Test the property 'Template'
        /// </summary>
        [Fact]
        public void TemplateTest()
        {
            // TODO unit test for the property 'Template'
        }

        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Fact]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
    }
}
