/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AsanaApiClient.Model;
using AsanaApiClient.Client;
using System.Reflection;

namespace AsanaApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TaskCountResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaskCountResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TaskCountResponse
        //private TaskCountResponse instance;

        public TaskCountResponseTests()
        {
            // TODO uncomment below to create an instance of TaskCountResponse
            //instance = new TaskCountResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TaskCountResponse
        /// </summary>
        [Fact]
        public void TaskCountResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TaskCountResponse
            //Assert.IsType<TaskCountResponse>(instance);
        }

        /// <summary>
        /// Test the property 'NumTasks'
        /// </summary>
        [Fact]
        public void NumTasksTest()
        {
            // TODO unit test for the property 'NumTasks'
        }

        /// <summary>
        /// Test the property 'NumIncompleteTasks'
        /// </summary>
        [Fact]
        public void NumIncompleteTasksTest()
        {
            // TODO unit test for the property 'NumIncompleteTasks'
        }

        /// <summary>
        /// Test the property 'NumCompletedTasks'
        /// </summary>
        [Fact]
        public void NumCompletedTasksTest()
        {
            // TODO unit test for the property 'NumCompletedTasks'
        }

        /// <summary>
        /// Test the property 'NumMilestones'
        /// </summary>
        [Fact]
        public void NumMilestonesTest()
        {
            // TODO unit test for the property 'NumMilestones'
        }

        /// <summary>
        /// Test the property 'NumIncompleteMilestones'
        /// </summary>
        [Fact]
        public void NumIncompleteMilestonesTest()
        {
            // TODO unit test for the property 'NumIncompleteMilestones'
        }

        /// <summary>
        /// Test the property 'NumCompletedMilestones'
        /// </summary>
        [Fact]
        public void NumCompletedMilestonesTest()
        {
            // TODO unit test for the property 'NumCompletedMilestones'
        }
    }
}
