/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AsanaApiClient.Model;
using AsanaApiClient.Client;
using System.Reflection;

namespace AsanaApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing WorkspaceMembershipResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkspaceMembershipResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkspaceMembershipResponse
        //private WorkspaceMembershipResponse instance;

        public WorkspaceMembershipResponseTests()
        {
            // TODO uncomment below to create an instance of WorkspaceMembershipResponse
            //instance = new WorkspaceMembershipResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkspaceMembershipResponse
        /// </summary>
        [Fact]
        public void WorkspaceMembershipResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkspaceMembershipResponse
            //Assert.IsType<WorkspaceMembershipResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Gid'
        /// </summary>
        [Fact]
        public void GidTest()
        {
            // TODO unit test for the property 'Gid'
        }

        /// <summary>
        /// Test the property 'ResourceType'
        /// </summary>
        [Fact]
        public void ResourceTypeTest()
        {
            // TODO unit test for the property 'ResourceType'
        }

        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }

        /// <summary>
        /// Test the property 'Workspace'
        /// </summary>
        [Fact]
        public void WorkspaceTest()
        {
            // TODO unit test for the property 'Workspace'
        }

        /// <summary>
        /// Test the property 'UserTaskList'
        /// </summary>
        [Fact]
        public void UserTaskListTest()
        {
            // TODO unit test for the property 'UserTaskList'
        }

        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }

        /// <summary>
        /// Test the property 'IsAdmin'
        /// </summary>
        [Fact]
        public void IsAdminTest()
        {
            // TODO unit test for the property 'IsAdmin'
        }

        /// <summary>
        /// Test the property 'IsGuest'
        /// </summary>
        [Fact]
        public void IsGuestTest()
        {
            // TODO unit test for the property 'IsGuest'
        }

        /// <summary>
        /// Test the property 'IsViewOnly'
        /// </summary>
        [Fact]
        public void IsViewOnlyTest()
        {
            // TODO unit test for the property 'IsViewOnly'
        }

        /// <summary>
        /// Test the property 'VacationDates'
        /// </summary>
        [Fact]
        public void VacationDatesTest()
        {
            // TODO unit test for the property 'VacationDates'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
    }
}
