/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.IO;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using AsanaApiClient.Model;
using System.Runtime.CompilerServices;
using System.Net.Http.Headers;

[assembly: InternalsVisibleTo("AsanaApiClient.Test")]

namespace AsanaApiClient.Client
{
    /// <summary>
    /// Utility functions providing some benefit to API client consumers.
    /// </summary>
    public static partial class ClientUtils
    {

        /// <summary>
        /// A delegate for events.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        /// <returns></returns>
        public delegate void EventHandler<T>(object sender, T e) where T : EventArgs;

        /// <summary>
        /// Returns true when deserialization succeeds.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="json"></param>
        /// <param name="options"></param>
        /// <param name="result"></param>
        /// <returns></returns>
        public static bool TryDeserialize<T>(string json, JsonSerializerOptions options, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out T? result)
        {
            try
            {
                result = JsonSerializer.Deserialize<T>(json, options);
                return result != null;
            }
            catch (Exception)
            {
                result = default;
                return false;
            }
        }

        /// <summary>
        /// Returns true when deserialization succeeds.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="reader"></param>
        /// <param name="options"></param>
        /// <param name="result"></param>
        /// <returns></returns>
        public static bool TryDeserialize<T>(ref Utf8JsonReader reader, JsonSerializerOptions options, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out T? result)
        {
            try
            {
                result = JsonSerializer.Deserialize<T>(ref reader, options);
                return result != null;
            }
            catch (Exception)
            {
                result = default;
                return false;
            }
        }

        /// <summary>
        /// If parameter is DateTime, output in a formatted string (default ISO 8601), customizable with Configuration.DateTime.
        /// If parameter is a list, join the list with ",".
        /// Otherwise just return the string.
        /// </summary>
        /// <param name="obj">The parameter (header, path, query, form).</param>
        /// <param name="format">The DateTime serialization format.</param>
        /// <returns>Formatted string.</returns>
        public static string? ParameterToString(object? obj, string? format = ISO8601_DATETIME_FORMAT)
        {
            if (obj is DateTime dateTime)
                // Return a formatted date string - Can be customized with Configuration.DateTimeFormat
                // Defaults to an ISO 8601, using the known as a Round-trip date/time pattern ("o")
                // https://msdn.microsoft.com/en-us/library/az4se3k1(v=vs.110).aspx#Anchor_8
                // For example: 2009-06-15T13:45:30.0000000
                return dateTime.ToString(format);
            if (obj is DateTimeOffset dateTimeOffset)
                // Return a formatted date string - Can be customized with Configuration.DateTimeFormat
                // Defaults to an ISO 8601, using the known as a Round-trip date/time pattern ("o")
                // https://msdn.microsoft.com/en-us/library/az4se3k1(v=vs.110).aspx#Anchor_8
                // For example: 2009-06-15T13:45:30.0000000
                return dateTimeOffset.ToString(format);
            if (obj is DateOnly dateOnly)
                return dateOnly.ToString(format);
            if (obj is bool boolean)
                return boolean
                    ? "true"
                    : "false";
            if (obj is AccessRequestResponse.ApprovalStatusEnum accessRequestResponseApprovalStatusEnum)
                return AccessRequestResponse.ApprovalStatusEnumToJsonValue(accessRequestResponseApprovalStatusEnum);
            if (obj is AllocationBaseEffort.TypeEnum allocationBaseEffortTypeEnum)
                return AllocationBaseEffort.TypeEnumToJsonValue(allocationBaseEffortTypeEnum);
            if (obj is AuditLogEventActor.ActorTypeEnum auditLogEventActorActorTypeEnum)
                return AuditLogEventActor.ActorTypeEnumToJsonValue(auditLogEventActorActorTypeEnum);
            if (obj is AuditLogEventContext.ContextTypeEnum auditLogEventContextContextTypeEnum)
                return AuditLogEventContext.ContextTypeEnumToJsonValue(auditLogEventContextContextTypeEnum);
            if (obj is AuditLogEventContext.ApiAuthenticationMethodEnum auditLogEventContextApiAuthenticationMethodEnum)
                return AuditLogEventContext.ApiAuthenticationMethodEnumToJsonValue(auditLogEventContextApiAuthenticationMethodEnum);
            if (obj is BatchRequestAction.MethodEnum batchRequestActionMethodEnum)
                return BatchRequestAction.MethodEnumToJsonValue(batchRequestActionMethodEnum);
            if (obj is BudgetActualRequest.BillableStatusFilterEnum budgetActualRequestBillableStatusFilterEnum)
                return BudgetActualRequest.BillableStatusFilterEnumToJsonValue(budgetActualRequestBillableStatusFilterEnum);
            if (obj is BudgetActualResponse.BillableStatusFilterEnum budgetActualResponseBillableStatusFilterEnum)
                return BudgetActualResponse.BillableStatusFilterEnumToJsonValue(budgetActualResponseBillableStatusFilterEnum);
            if (obj is BudgetCompact.BudgetTypeEnum budgetCompactBudgetTypeEnum)
                return BudgetCompact.BudgetTypeEnumToJsonValue(budgetCompactBudgetTypeEnum);
            if (obj is BudgetEstimateRequest.BillableStatusFilterEnum budgetEstimateRequestBillableStatusFilterEnum)
                return BudgetEstimateRequest.BillableStatusFilterEnumToJsonValue(budgetEstimateRequestBillableStatusFilterEnum);
            if (obj is BudgetEstimateRequest.SourceEnum budgetEstimateRequestSourceEnum)
                return BudgetEstimateRequest.SourceEnumToJsonValue(budgetEstimateRequestSourceEnum);
            if (obj is BudgetEstimateResponse.BillableStatusFilterEnum budgetEstimateResponseBillableStatusFilterEnum)
                return BudgetEstimateResponse.BillableStatusFilterEnumToJsonValue(budgetEstimateResponseBillableStatusFilterEnum);
            if (obj is BudgetEstimateResponse.SourceEnum budgetEstimateResponseSourceEnum)
                return BudgetEstimateResponse.SourceEnumToJsonValue(budgetEstimateResponseSourceEnum);
            if (obj is BudgetRequest.BudgetTypeEnum budgetRequestBudgetTypeEnum)
                return BudgetRequest.BudgetTypeEnumToJsonValue(budgetRequestBudgetTypeEnum);
            if (obj is BudgetResponse.BudgetTypeEnum budgetResponseBudgetTypeEnum)
                return BudgetResponse.BudgetTypeEnumToJsonValue(budgetResponseBudgetTypeEnum);
            if (obj is CustomFieldBase.TypeEnum customFieldBaseTypeEnum)
                return CustomFieldBase.TypeEnumToJsonValue(customFieldBaseTypeEnum);
            if (obj is CustomFieldBase.RepresentationTypeEnum customFieldBaseRepresentationTypeEnum)
                return CustomFieldBase.RepresentationTypeEnumToJsonValue(customFieldBaseRepresentationTypeEnum);
            if (obj is CustomFieldBase.FormatEnum customFieldBaseFormatEnum)
                return CustomFieldBase.FormatEnumToJsonValue(customFieldBaseFormatEnum);
            if (obj is CustomFieldBase.CustomLabelPositionEnum customFieldBaseCustomLabelPositionEnum)
                return CustomFieldBase.CustomLabelPositionEnumToJsonValue(customFieldBaseCustomLabelPositionEnum);
            if (obj is CustomFieldBase.AsanaCreatedFieldEnum customFieldBaseAsanaCreatedFieldEnum)
                return CustomFieldBase.AsanaCreatedFieldEnumToJsonValue(customFieldBaseAsanaCreatedFieldEnum);
            if (obj is CustomFieldCompact.TypeEnum customFieldCompactTypeEnum)
                return CustomFieldCompact.TypeEnumToJsonValue(customFieldCompactTypeEnum);
            if (obj is CustomFieldCompact.RepresentationTypeEnum customFieldCompactRepresentationTypeEnum)
                return CustomFieldCompact.RepresentationTypeEnumToJsonValue(customFieldCompactRepresentationTypeEnum);
            if (obj is CustomFieldCreateRequest.ResourceSubtypeEnum customFieldCreateRequestResourceSubtypeEnum)
                return CustomFieldCreateRequest.ResourceSubtypeEnumToJsonValue(customFieldCreateRequestResourceSubtypeEnum);
            if (obj is CustomFieldCreateRequest.TypeEnum customFieldCreateRequestTypeEnum)
                return CustomFieldCreateRequest.TypeEnumToJsonValue(customFieldCreateRequestTypeEnum);
            if (obj is CustomFieldCreateRequest.RepresentationTypeEnum customFieldCreateRequestRepresentationTypeEnum)
                return CustomFieldCreateRequest.RepresentationTypeEnumToJsonValue(customFieldCreateRequestRepresentationTypeEnum);
            if (obj is CustomFieldCreateRequest.FormatEnum customFieldCreateRequestFormatEnum)
                return CustomFieldCreateRequest.FormatEnumToJsonValue(customFieldCreateRequestFormatEnum);
            if (obj is CustomFieldCreateRequest.CustomLabelPositionEnum customFieldCreateRequestCustomLabelPositionEnum)
                return CustomFieldCreateRequest.CustomLabelPositionEnumToJsonValue(customFieldCreateRequestCustomLabelPositionEnum);
            if (obj is CustomFieldCreateRequest.AsanaCreatedFieldEnum customFieldCreateRequestAsanaCreatedFieldEnum)
                return CustomFieldCreateRequest.AsanaCreatedFieldEnumToJsonValue(customFieldCreateRequestAsanaCreatedFieldEnum);
            if (obj is CustomFieldMembershipCompact.AccessLevelEnum customFieldMembershipCompactAccessLevelEnum)
                return CustomFieldMembershipCompact.AccessLevelEnumToJsonValue(customFieldMembershipCompactAccessLevelEnum);
            if (obj is CustomFieldRequest.TypeEnum customFieldRequestTypeEnum)
                return CustomFieldRequest.TypeEnumToJsonValue(customFieldRequestTypeEnum);
            if (obj is CustomFieldRequest.RepresentationTypeEnum customFieldRequestRepresentationTypeEnum)
                return CustomFieldRequest.RepresentationTypeEnumToJsonValue(customFieldRequestRepresentationTypeEnum);
            if (obj is CustomFieldRequest.FormatEnum customFieldRequestFormatEnum)
                return CustomFieldRequest.FormatEnumToJsonValue(customFieldRequestFormatEnum);
            if (obj is CustomFieldRequest.CustomLabelPositionEnum customFieldRequestCustomLabelPositionEnum)
                return CustomFieldRequest.CustomLabelPositionEnumToJsonValue(customFieldRequestCustomLabelPositionEnum);
            if (obj is CustomFieldRequest.AsanaCreatedFieldEnum customFieldRequestAsanaCreatedFieldEnum)
                return CustomFieldRequest.AsanaCreatedFieldEnumToJsonValue(customFieldRequestAsanaCreatedFieldEnum);
            if (obj is CustomFieldResponse.TypeEnum customFieldResponseTypeEnum)
                return CustomFieldResponse.TypeEnumToJsonValue(customFieldResponseTypeEnum);
            if (obj is CustomFieldResponse.RepresentationTypeEnum customFieldResponseRepresentationTypeEnum)
                return CustomFieldResponse.RepresentationTypeEnumToJsonValue(customFieldResponseRepresentationTypeEnum);
            if (obj is CustomFieldResponse.FormatEnum customFieldResponseFormatEnum)
                return CustomFieldResponse.FormatEnumToJsonValue(customFieldResponseFormatEnum);
            if (obj is CustomFieldResponse.CustomLabelPositionEnum customFieldResponseCustomLabelPositionEnum)
                return CustomFieldResponse.CustomLabelPositionEnumToJsonValue(customFieldResponseCustomLabelPositionEnum);
            if (obj is CustomFieldResponse.AsanaCreatedFieldEnum customFieldResponseAsanaCreatedFieldEnum)
                return CustomFieldResponse.AsanaCreatedFieldEnumToJsonValue(customFieldResponseAsanaCreatedFieldEnum);
            if (obj is CustomFieldResponse.PrivacySettingEnum customFieldResponsePrivacySettingEnum)
                return CustomFieldResponse.PrivacySettingEnumToJsonValue(customFieldResponsePrivacySettingEnum);
            if (obj is CustomFieldResponse.DefaultAccessLevelEnum customFieldResponseDefaultAccessLevelEnum)
                return CustomFieldResponse.DefaultAccessLevelEnumToJsonValue(customFieldResponseDefaultAccessLevelEnum);
            if (obj is CustomFieldResponse.ResourceSubtypeEnum customFieldResponseResourceSubtypeEnum)
                return CustomFieldResponse.ResourceSubtypeEnumToJsonValue(customFieldResponseResourceSubtypeEnum);
            if (obj is CustomFieldSettingResponseAllOfCustomField.TypeEnum customFieldSettingResponseAllOfCustomFieldTypeEnum)
                return CustomFieldSettingResponseAllOfCustomField.TypeEnumToJsonValue(customFieldSettingResponseAllOfCustomFieldTypeEnum);
            if (obj is CustomFieldSettingResponseAllOfCustomField.RepresentationTypeEnum customFieldSettingResponseAllOfCustomFieldRepresentationTypeEnum)
                return CustomFieldSettingResponseAllOfCustomField.RepresentationTypeEnumToJsonValue(customFieldSettingResponseAllOfCustomFieldRepresentationTypeEnum);
            if (obj is CustomFieldSettingResponseAllOfCustomField.FormatEnum customFieldSettingResponseAllOfCustomFieldFormatEnum)
                return CustomFieldSettingResponseAllOfCustomField.FormatEnumToJsonValue(customFieldSettingResponseAllOfCustomFieldFormatEnum);
            if (obj is CustomFieldSettingResponseAllOfCustomField.CustomLabelPositionEnum customFieldSettingResponseAllOfCustomFieldCustomLabelPositionEnum)
                return CustomFieldSettingResponseAllOfCustomField.CustomLabelPositionEnumToJsonValue(customFieldSettingResponseAllOfCustomFieldCustomLabelPositionEnum);
            if (obj is CustomFieldSettingResponseAllOfCustomField.AsanaCreatedFieldEnum customFieldSettingResponseAllOfCustomFieldAsanaCreatedFieldEnum)
                return CustomFieldSettingResponseAllOfCustomField.AsanaCreatedFieldEnumToJsonValue(customFieldSettingResponseAllOfCustomFieldAsanaCreatedFieldEnum);
            if (obj is CustomFieldSettingResponseAllOfCustomField.PrivacySettingEnum customFieldSettingResponseAllOfCustomFieldPrivacySettingEnum)
                return CustomFieldSettingResponseAllOfCustomField.PrivacySettingEnumToJsonValue(customFieldSettingResponseAllOfCustomFieldPrivacySettingEnum);
            if (obj is CustomFieldSettingResponseAllOfCustomField.DefaultAccessLevelEnum customFieldSettingResponseAllOfCustomFieldDefaultAccessLevelEnum)
                return CustomFieldSettingResponseAllOfCustomField.DefaultAccessLevelEnumToJsonValue(customFieldSettingResponseAllOfCustomFieldDefaultAccessLevelEnum);
            if (obj is CustomFieldSettingResponseAllOfCustomField.ResourceSubtypeEnum customFieldSettingResponseAllOfCustomFieldResourceSubtypeEnum)
                return CustomFieldSettingResponseAllOfCustomField.ResourceSubtypeEnumToJsonValue(customFieldSettingResponseAllOfCustomFieldResourceSubtypeEnum);
            if (obj is CustomTypeMembershipCompact.AccessLevelEnum customTypeMembershipCompactAccessLevelEnum)
                return CustomTypeMembershipCompact.AccessLevelEnumToJsonValue(customTypeMembershipCompactAccessLevelEnum);
            if (obj is DeprecatedPortfolioMembershipCompact.AccessLevelEnum deprecatedPortfolioMembershipCompactAccessLevelEnum)
                return DeprecatedPortfolioMembershipCompact.AccessLevelEnumToJsonValue(deprecatedPortfolioMembershipCompactAccessLevelEnum);
            if (obj is GoalMembershipBase.RoleEnum goalMembershipBaseRoleEnum)
                return GoalMembershipBase.RoleEnumToJsonValue(goalMembershipBaseRoleEnum);
            if (obj is GoalMembershipBase.AccessLevelEnum goalMembershipBaseAccessLevelEnum)
                return GoalMembershipBase.AccessLevelEnumToJsonValue(goalMembershipBaseAccessLevelEnum);
            if (obj is GoalMembershipCompact.RoleEnum goalMembershipCompactRoleEnum)
                return GoalMembershipCompact.RoleEnumToJsonValue(goalMembershipCompactRoleEnum);
            if (obj is GoalMembershipCompact.AccessLevelEnum goalMembershipCompactAccessLevelEnum)
                return GoalMembershipCompact.AccessLevelEnumToJsonValue(goalMembershipCompactAccessLevelEnum);
            if (obj is GoalMembershipResponse.RoleEnum goalMembershipResponseRoleEnum)
                return GoalMembershipResponse.RoleEnumToJsonValue(goalMembershipResponseRoleEnum);
            if (obj is GoalMembershipResponse.AccessLevelEnum goalMembershipResponseAccessLevelEnum)
                return GoalMembershipResponse.AccessLevelEnumToJsonValue(goalMembershipResponseAccessLevelEnum);
            if (obj is GoalMetricBase.ResourceSubtypeEnum goalMetricBaseResourceSubtypeEnum)
                return GoalMetricBase.ResourceSubtypeEnumToJsonValue(goalMetricBaseResourceSubtypeEnum);
            if (obj is GoalMetricBase.UnitEnum goalMetricBaseUnitEnum)
                return GoalMetricBase.UnitEnumToJsonValue(goalMetricBaseUnitEnum);
            if (obj is GoalMetricBase.ProgressSourceEnum goalMetricBaseProgressSourceEnum)
                return GoalMetricBase.ProgressSourceEnumToJsonValue(goalMetricBaseProgressSourceEnum);
            if (obj is GoalRelationshipBase.ResourceSubtypeEnum goalRelationshipBaseResourceSubtypeEnum)
                return GoalRelationshipBase.ResourceSubtypeEnumToJsonValue(goalRelationshipBaseResourceSubtypeEnum);
            if (obj is GoalRelationshipCompact.ResourceSubtypeEnum goalRelationshipCompactResourceSubtypeEnum)
                return GoalRelationshipCompact.ResourceSubtypeEnumToJsonValue(goalRelationshipCompactResourceSubtypeEnum);
            if (obj is GoalRelationshipRequest.ResourceSubtypeEnum goalRelationshipRequestResourceSubtypeEnum)
                return GoalRelationshipRequest.ResourceSubtypeEnumToJsonValue(goalRelationshipRequestResourceSubtypeEnum);
            if (obj is GoalRelationshipResponse.ResourceSubtypeEnum goalRelationshipResponseResourceSubtypeEnum)
                return GoalRelationshipResponse.ResourceSubtypeEnumToJsonValue(goalRelationshipResponseResourceSubtypeEnum);
            if (obj is GoalResponseAllOfMetric.ResourceSubtypeEnum goalResponseAllOfMetricResourceSubtypeEnum)
                return GoalResponseAllOfMetric.ResourceSubtypeEnumToJsonValue(goalResponseAllOfMetricResourceSubtypeEnum);
            if (obj is GoalResponseAllOfMetric.UnitEnum goalResponseAllOfMetricUnitEnum)
                return GoalResponseAllOfMetric.UnitEnumToJsonValue(goalResponseAllOfMetricUnitEnum);
            if (obj is GoalResponseAllOfMetric.ProgressSourceEnum goalResponseAllOfMetricProgressSourceEnum)
                return GoalResponseAllOfMetric.ProgressSourceEnumToJsonValue(goalResponseAllOfMetricProgressSourceEnum);
            if (obj is GoalResponseAllOfTimePeriod.PeriodEnum goalResponseAllOfTimePeriodPeriodEnum)
                return GoalResponseAllOfTimePeriod.PeriodEnumToJsonValue(goalResponseAllOfTimePeriodPeriodEnum);
            if (obj is GraphExportResponse.StatusEnum graphExportResponseStatusEnum)
                return GraphExportResponse.StatusEnumToJsonValue(graphExportResponseStatusEnum);
            if (obj is JobCompact.StatusEnum jobCompactStatusEnum)
                return JobCompact.StatusEnumToJsonValue(jobCompactStatusEnum);
            if (obj is JobCompactNewTask.ResourceSubtypeEnum jobCompactNewTaskResourceSubtypeEnum)
                return JobCompactNewTask.ResourceSubtypeEnumToJsonValue(jobCompactNewTaskResourceSubtypeEnum);
            if (obj is OrganizationExportCompact.StateEnum organizationExportCompactStateEnum)
                return OrganizationExportCompact.StateEnumToJsonValue(organizationExportCompactStateEnum);
            if (obj is PortfolioBase.ColorEnum portfolioBaseColorEnum)
                return PortfolioBase.ColorEnumToJsonValue(portfolioBaseColorEnum);
            if (obj is PortfolioBase.DefaultAccessLevelEnum portfolioBaseDefaultAccessLevelEnum)
                return PortfolioBase.DefaultAccessLevelEnumToJsonValue(portfolioBaseDefaultAccessLevelEnum);
            if (obj is PortfolioMembershipCompact.AccessLevelEnum portfolioMembershipCompactAccessLevelEnum)
                return PortfolioMembershipCompact.AccessLevelEnumToJsonValue(portfolioMembershipCompactAccessLevelEnum);
            if (obj is PortfolioMembershipCompactResponse.AccessLevelEnum portfolioMembershipCompactResponseAccessLevelEnum)
                return PortfolioMembershipCompactResponse.AccessLevelEnumToJsonValue(portfolioMembershipCompactResponseAccessLevelEnum);
            if (obj is PortfolioRequest.ColorEnum portfolioRequestColorEnum)
                return PortfolioRequest.ColorEnumToJsonValue(portfolioRequestColorEnum);
            if (obj is PortfolioRequest.DefaultAccessLevelEnum portfolioRequestDefaultAccessLevelEnum)
                return PortfolioRequest.DefaultAccessLevelEnumToJsonValue(portfolioRequestDefaultAccessLevelEnum);
            if (obj is PortfolioResponse.ColorEnum portfolioResponseColorEnum)
                return PortfolioResponse.ColorEnumToJsonValue(portfolioResponseColorEnum);
            if (obj is PortfolioResponse.DefaultAccessLevelEnum portfolioResponseDefaultAccessLevelEnum)
                return PortfolioResponse.DefaultAccessLevelEnumToJsonValue(portfolioResponseDefaultAccessLevelEnum);
            if (obj is PortfolioResponse.PrivacySettingEnum portfolioResponsePrivacySettingEnum)
                return PortfolioResponse.PrivacySettingEnumToJsonValue(portfolioResponsePrivacySettingEnum);
            if (obj is PortfolioUpdateRequest.ColorEnum portfolioUpdateRequestColorEnum)
                return PortfolioUpdateRequest.ColorEnumToJsonValue(portfolioUpdateRequestColorEnum);
            if (obj is PortfolioUpdateRequest.DefaultAccessLevelEnum portfolioUpdateRequestDefaultAccessLevelEnum)
                return PortfolioUpdateRequest.DefaultAccessLevelEnumToJsonValue(portfolioUpdateRequestDefaultAccessLevelEnum);
            if (obj is ProjectBase.ColorEnum projectBaseColorEnum)
                return ProjectBase.ColorEnumToJsonValue(projectBaseColorEnum);
            if (obj is ProjectBase.IconEnum projectBaseIconEnum)
                return ProjectBase.IconEnumToJsonValue(projectBaseIconEnum);
            if (obj is ProjectBase.DefaultViewEnum projectBaseDefaultViewEnum)
                return ProjectBase.DefaultViewEnumToJsonValue(projectBaseDefaultViewEnum);
            if (obj is ProjectBase.PrivacySettingEnum projectBasePrivacySettingEnum)
                return ProjectBase.PrivacySettingEnumToJsonValue(projectBasePrivacySettingEnum);
            if (obj is ProjectBase.DefaultAccessLevelEnum projectBaseDefaultAccessLevelEnum)
                return ProjectBase.DefaultAccessLevelEnumToJsonValue(projectBaseDefaultAccessLevelEnum);
            if (obj is ProjectBase.MinimumAccessLevelForCustomizationEnum projectBaseMinimumAccessLevelForCustomizationEnum)
                return ProjectBase.MinimumAccessLevelForCustomizationEnumToJsonValue(projectBaseMinimumAccessLevelForCustomizationEnum);
            if (obj is ProjectBase.MinimumAccessLevelForSharingEnum projectBaseMinimumAccessLevelForSharingEnum)
                return ProjectBase.MinimumAccessLevelForSharingEnumToJsonValue(projectBaseMinimumAccessLevelForSharingEnum);
            if (obj is ProjectBaseAllOfCurrentStatus.ColorEnum projectBaseAllOfCurrentStatusColorEnum)
                return ProjectBaseAllOfCurrentStatus.ColorEnumToJsonValue(projectBaseAllOfCurrentStatusColorEnum);
            if (obj is ProjectBaseAllOfCurrentStatusUpdate.ResourceSubtypeEnum projectBaseAllOfCurrentStatusUpdateResourceSubtypeEnum)
                return ProjectBaseAllOfCurrentStatusUpdate.ResourceSubtypeEnumToJsonValue(projectBaseAllOfCurrentStatusUpdateResourceSubtypeEnum);
            if (obj is ProjectMembershipCompact.AccessLevelEnum projectMembershipCompactAccessLevelEnum)
                return ProjectMembershipCompact.AccessLevelEnumToJsonValue(projectMembershipCompactAccessLevelEnum);
            if (obj is ProjectMembershipCompactResponse.AccessLevelEnum projectMembershipCompactResponseAccessLevelEnum)
                return ProjectMembershipCompactResponse.AccessLevelEnumToJsonValue(projectMembershipCompactResponseAccessLevelEnum);
            if (obj is ProjectMembershipNormalResponse.AccessLevelEnum projectMembershipNormalResponseAccessLevelEnum)
                return ProjectMembershipNormalResponse.AccessLevelEnumToJsonValue(projectMembershipNormalResponseAccessLevelEnum);
            if (obj is ProjectMembershipNormalResponse.WriteAccessEnum projectMembershipNormalResponseWriteAccessEnum)
                return ProjectMembershipNormalResponse.WriteAccessEnumToJsonValue(projectMembershipNormalResponseWriteAccessEnum);
            if (obj is ProjectRequest.ColorEnum projectRequestColorEnum)
                return ProjectRequest.ColorEnumToJsonValue(projectRequestColorEnum);
            if (obj is ProjectRequest.IconEnum projectRequestIconEnum)
                return ProjectRequest.IconEnumToJsonValue(projectRequestIconEnum);
            if (obj is ProjectRequest.DefaultViewEnum projectRequestDefaultViewEnum)
                return ProjectRequest.DefaultViewEnumToJsonValue(projectRequestDefaultViewEnum);
            if (obj is ProjectRequest.PrivacySettingEnum projectRequestPrivacySettingEnum)
                return ProjectRequest.PrivacySettingEnumToJsonValue(projectRequestPrivacySettingEnum);
            if (obj is ProjectRequest.DefaultAccessLevelEnum projectRequestDefaultAccessLevelEnum)
                return ProjectRequest.DefaultAccessLevelEnumToJsonValue(projectRequestDefaultAccessLevelEnum);
            if (obj is ProjectRequest.MinimumAccessLevelForCustomizationEnum projectRequestMinimumAccessLevelForCustomizationEnum)
                return ProjectRequest.MinimumAccessLevelForCustomizationEnumToJsonValue(projectRequestMinimumAccessLevelForCustomizationEnum);
            if (obj is ProjectRequest.MinimumAccessLevelForSharingEnum projectRequestMinimumAccessLevelForSharingEnum)
                return ProjectRequest.MinimumAccessLevelForSharingEnumToJsonValue(projectRequestMinimumAccessLevelForSharingEnum);
            if (obj is ProjectResponse.ColorEnum projectResponseColorEnum)
                return ProjectResponse.ColorEnumToJsonValue(projectResponseColorEnum);
            if (obj is ProjectResponse.IconEnum projectResponseIconEnum)
                return ProjectResponse.IconEnumToJsonValue(projectResponseIconEnum);
            if (obj is ProjectResponse.DefaultViewEnum projectResponseDefaultViewEnum)
                return ProjectResponse.DefaultViewEnumToJsonValue(projectResponseDefaultViewEnum);
            if (obj is ProjectResponse.PrivacySettingEnum projectResponsePrivacySettingEnum)
                return ProjectResponse.PrivacySettingEnumToJsonValue(projectResponsePrivacySettingEnum);
            if (obj is ProjectResponse.DefaultAccessLevelEnum projectResponseDefaultAccessLevelEnum)
                return ProjectResponse.DefaultAccessLevelEnumToJsonValue(projectResponseDefaultAccessLevelEnum);
            if (obj is ProjectResponse.MinimumAccessLevelForCustomizationEnum projectResponseMinimumAccessLevelForCustomizationEnum)
                return ProjectResponse.MinimumAccessLevelForCustomizationEnumToJsonValue(projectResponseMinimumAccessLevelForCustomizationEnum);
            if (obj is ProjectResponse.MinimumAccessLevelForSharingEnum projectResponseMinimumAccessLevelForSharingEnum)
                return ProjectResponse.MinimumAccessLevelForSharingEnumToJsonValue(projectResponseMinimumAccessLevelForSharingEnum);
            if (obj is ProjectStatusBase.ColorEnum projectStatusBaseColorEnum)
                return ProjectStatusBase.ColorEnumToJsonValue(projectStatusBaseColorEnum);
            if (obj is ProjectStatusResponse.ColorEnum projectStatusResponseColorEnum)
                return ProjectStatusResponse.ColorEnumToJsonValue(projectStatusResponseColorEnum);
            if (obj is ProjectTemplateBase.ColorEnum projectTemplateBaseColorEnum)
                return ProjectTemplateBase.ColorEnumToJsonValue(projectTemplateBaseColorEnum);
            if (obj is ProjectTemplateInstantiateProjectRequest.PrivacySettingEnum projectTemplateInstantiateProjectRequestPrivacySettingEnum)
                return ProjectTemplateInstantiateProjectRequest.PrivacySettingEnumToJsonValue(projectTemplateInstantiateProjectRequestPrivacySettingEnum);
            if (obj is ProjectTemplateResponse.ColorEnum projectTemplateResponseColorEnum)
                return ProjectTemplateResponse.ColorEnumToJsonValue(projectTemplateResponseColorEnum);
            if (obj is ProjectUpdateRequest.ColorEnum projectUpdateRequestColorEnum)
                return ProjectUpdateRequest.ColorEnumToJsonValue(projectUpdateRequestColorEnum);
            if (obj is ProjectUpdateRequest.IconEnum projectUpdateRequestIconEnum)
                return ProjectUpdateRequest.IconEnumToJsonValue(projectUpdateRequestIconEnum);
            if (obj is ProjectUpdateRequest.DefaultViewEnum projectUpdateRequestDefaultViewEnum)
                return ProjectUpdateRequest.DefaultViewEnumToJsonValue(projectUpdateRequestDefaultViewEnum);
            if (obj is ProjectUpdateRequest.PrivacySettingEnum projectUpdateRequestPrivacySettingEnum)
                return ProjectUpdateRequest.PrivacySettingEnumToJsonValue(projectUpdateRequestPrivacySettingEnum);
            if (obj is ProjectUpdateRequest.DefaultAccessLevelEnum projectUpdateRequestDefaultAccessLevelEnum)
                return ProjectUpdateRequest.DefaultAccessLevelEnumToJsonValue(projectUpdateRequestDefaultAccessLevelEnum);
            if (obj is ProjectUpdateRequest.MinimumAccessLevelForCustomizationEnum projectUpdateRequestMinimumAccessLevelForCustomizationEnum)
                return ProjectUpdateRequest.MinimumAccessLevelForCustomizationEnumToJsonValue(projectUpdateRequestMinimumAccessLevelForCustomizationEnum);
            if (obj is ProjectUpdateRequest.MinimumAccessLevelForSharingEnum projectUpdateRequestMinimumAccessLevelForSharingEnum)
                return ProjectUpdateRequest.MinimumAccessLevelForSharingEnumToJsonValue(projectUpdateRequestMinimumAccessLevelForSharingEnum);
            if (obj is RbacRoleBase.BaseRoleTypeEnum rbacRoleBaseBaseRoleTypeEnum)
                return RbacRoleBase.BaseRoleTypeEnumToJsonValue(rbacRoleBaseBaseRoleTypeEnum);
            if (obj is RbacRoleBaseAllOfPermissions.TaskDeletionPolicyEnum rbacRoleBaseAllOfPermissionsTaskDeletionPolicyEnum)
                return RbacRoleBaseAllOfPermissions.TaskDeletionPolicyEnumToJsonValue(rbacRoleBaseAllOfPermissionsTaskDeletionPolicyEnum);
            if (obj is RbacRoleBaseAllOfPermissions.AllowedGuestInvitesEnum rbacRoleBaseAllOfPermissionsAllowedGuestInvitesEnum)
                return RbacRoleBaseAllOfPermissions.AllowedGuestInvitesEnumToJsonValue(rbacRoleBaseAllOfPermissionsAllowedGuestInvitesEnum);
            if (obj is RbacRoleRequest.BaseRoleTypeEnum rbacRoleRequestBaseRoleTypeEnum)
                return RbacRoleRequest.BaseRoleTypeEnumToJsonValue(rbacRoleRequestBaseRoleTypeEnum);
            if (obj is RbacRoleResponse.BaseRoleTypeEnum rbacRoleResponseBaseRoleTypeEnum)
                return RbacRoleResponse.BaseRoleTypeEnumToJsonValue(rbacRoleResponseBaseRoleTypeEnum);
            if (obj is RbacRoleUpdateRequest.BaseRoleTypeEnum rbacRoleUpdateRequestBaseRoleTypeEnum)
                return RbacRoleUpdateRequest.BaseRoleTypeEnumToJsonValue(rbacRoleUpdateRequestBaseRoleTypeEnum);
            if (obj is ResourceExportResponse.StatusEnum resourceExportResponseStatusEnum)
                return ResourceExportResponse.StatusEnumToJsonValue(resourceExportResponseStatusEnum);
            if (obj is StatusUpdateBase.StatusTypeEnum statusUpdateBaseStatusTypeEnum)
                return StatusUpdateBase.StatusTypeEnumToJsonValue(statusUpdateBaseStatusTypeEnum);
            if (obj is StatusUpdateBase.ResourceSubtypeEnum statusUpdateBaseResourceSubtypeEnum)
                return StatusUpdateBase.ResourceSubtypeEnumToJsonValue(statusUpdateBaseResourceSubtypeEnum);
            if (obj is StatusUpdateCompact.ResourceSubtypeEnum statusUpdateCompactResourceSubtypeEnum)
                return StatusUpdateCompact.ResourceSubtypeEnumToJsonValue(statusUpdateCompactResourceSubtypeEnum);
            if (obj is StatusUpdateRequest.StatusTypeEnum statusUpdateRequestStatusTypeEnum)
                return StatusUpdateRequest.StatusTypeEnumToJsonValue(statusUpdateRequestStatusTypeEnum);
            if (obj is StatusUpdateRequest.ResourceSubtypeEnum statusUpdateRequestResourceSubtypeEnum)
                return StatusUpdateRequest.ResourceSubtypeEnumToJsonValue(statusUpdateRequestResourceSubtypeEnum);
            if (obj is StatusUpdateResponse.StatusTypeEnum statusUpdateResponseStatusTypeEnum)
                return StatusUpdateResponse.StatusTypeEnumToJsonValue(statusUpdateResponseStatusTypeEnum);
            if (obj is StatusUpdateResponse.ResourceSubtypeEnum statusUpdateResponseResourceSubtypeEnum)
                return StatusUpdateResponse.ResourceSubtypeEnumToJsonValue(statusUpdateResponseResourceSubtypeEnum);
            if (obj is StoryBase.StickerNameEnum storyBaseStickerNameEnum)
                return StoryBase.StickerNameEnumToJsonValue(storyBaseStickerNameEnum);
            if (obj is StoryResponse.StickerNameEnum storyResponseStickerNameEnum)
                return StoryResponse.StickerNameEnumToJsonValue(storyResponseStickerNameEnum);
            if (obj is StoryResponse.TypeEnum storyResponseTypeEnum)
                return StoryResponse.TypeEnumToJsonValue(storyResponseTypeEnum);
            if (obj is StoryResponse.SourceEnum storyResponseSourceEnum)
                return StoryResponse.SourceEnumToJsonValue(storyResponseSourceEnum);
            if (obj is StoryResponseAllOfTarget.ResourceSubtypeEnum storyResponseAllOfTargetResourceSubtypeEnum)
                return StoryResponseAllOfTarget.ResourceSubtypeEnumToJsonValue(storyResponseAllOfTargetResourceSubtypeEnum);
            if (obj is TagBase.ColorEnum tagBaseColorEnum)
                return TagBase.ColorEnumToJsonValue(tagBaseColorEnum);
            if (obj is TagCreateRequest.ColorEnum tagCreateRequestColorEnum)
                return TagCreateRequest.ColorEnumToJsonValue(tagCreateRequestColorEnum);
            if (obj is TagCreateTagForWorkspaceRequest.ColorEnum tagCreateTagForWorkspaceRequestColorEnum)
                return TagCreateTagForWorkspaceRequest.ColorEnumToJsonValue(tagCreateTagForWorkspaceRequestColorEnum);
            if (obj is TagResponse.ColorEnum tagResponseColorEnum)
                return TagResponse.ColorEnumToJsonValue(tagResponseColorEnum);
            if (obj is TaskBase.ResourceSubtypeEnum taskBaseResourceSubtypeEnum)
                return TaskBase.ResourceSubtypeEnumToJsonValue(taskBaseResourceSubtypeEnum);
            if (obj is TaskBase.ApprovalStatusEnum taskBaseApprovalStatusEnum)
                return TaskBase.ApprovalStatusEnumToJsonValue(taskBaseApprovalStatusEnum);
            if (obj is TaskBase.AssigneeStatusEnum taskBaseAssigneeStatusEnum)
                return TaskBase.AssigneeStatusEnumToJsonValue(taskBaseAssigneeStatusEnum);
            if (obj is TaskCompact.ResourceSubtypeEnum taskCompactResourceSubtypeEnum)
                return TaskCompact.ResourceSubtypeEnumToJsonValue(taskCompactResourceSubtypeEnum);
            if (obj is TaskRequest.ResourceSubtypeEnum taskRequestResourceSubtypeEnum)
                return TaskRequest.ResourceSubtypeEnumToJsonValue(taskRequestResourceSubtypeEnum);
            if (obj is TaskRequest.ApprovalStatusEnum taskRequestApprovalStatusEnum)
                return TaskRequest.ApprovalStatusEnumToJsonValue(taskRequestApprovalStatusEnum);
            if (obj is TaskRequest.AssigneeStatusEnum taskRequestAssigneeStatusEnum)
                return TaskRequest.AssigneeStatusEnumToJsonValue(taskRequestAssigneeStatusEnum);
            if (obj is TaskResponse.ResourceSubtypeEnum taskResponseResourceSubtypeEnum)
                return TaskResponse.ResourceSubtypeEnumToJsonValue(taskResponseResourceSubtypeEnum);
            if (obj is TaskResponse.ApprovalStatusEnum taskResponseApprovalStatusEnum)
                return TaskResponse.ApprovalStatusEnumToJsonValue(taskResponseApprovalStatusEnum);
            if (obj is TaskResponse.AssigneeStatusEnum taskResponseAssigneeStatusEnum)
                return TaskResponse.AssigneeStatusEnumToJsonValue(taskResponseAssigneeStatusEnum);
            if (obj is TaskResponseAllOfParent.ResourceSubtypeEnum taskResponseAllOfParentResourceSubtypeEnum)
                return TaskResponseAllOfParent.ResourceSubtypeEnumToJsonValue(taskResponseAllOfParentResourceSubtypeEnum);
            if (obj is TaskTemplateRecipe.TaskResourceSubtypeEnum taskTemplateRecipeTaskResourceSubtypeEnum)
                return TaskTemplateRecipe.TaskResourceSubtypeEnumToJsonValue(taskTemplateRecipeTaskResourceSubtypeEnum);
            if (obj is TaskTemplateRecipeCompact.TaskResourceSubtypeEnum taskTemplateRecipeCompactTaskResourceSubtypeEnum)
                return TaskTemplateRecipeCompact.TaskResourceSubtypeEnumToJsonValue(taskTemplateRecipeCompactTaskResourceSubtypeEnum);
            if (obj is TeamRequest.VisibilityEnum teamRequestVisibilityEnum)
                return TeamRequest.VisibilityEnumToJsonValue(teamRequestVisibilityEnum);
            if (obj is TeamRequest.EditTeamNameOrDescriptionAccessLevelEnum teamRequestEditTeamNameOrDescriptionAccessLevelEnum)
                return TeamRequest.EditTeamNameOrDescriptionAccessLevelEnumToJsonValue(teamRequestEditTeamNameOrDescriptionAccessLevelEnum);
            if (obj is TeamRequest.EditTeamVisibilityOrTrashTeamAccessLevelEnum teamRequestEditTeamVisibilityOrTrashTeamAccessLevelEnum)
                return TeamRequest.EditTeamVisibilityOrTrashTeamAccessLevelEnumToJsonValue(teamRequestEditTeamVisibilityOrTrashTeamAccessLevelEnum);
            if (obj is TeamRequest.MemberInviteManagementAccessLevelEnum teamRequestMemberInviteManagementAccessLevelEnum)
                return TeamRequest.MemberInviteManagementAccessLevelEnumToJsonValue(teamRequestMemberInviteManagementAccessLevelEnum);
            if (obj is TeamRequest.GuestInviteManagementAccessLevelEnum teamRequestGuestInviteManagementAccessLevelEnum)
                return TeamRequest.GuestInviteManagementAccessLevelEnumToJsonValue(teamRequestGuestInviteManagementAccessLevelEnum);
            if (obj is TeamRequest.JoinRequestManagementAccessLevelEnum teamRequestJoinRequestManagementAccessLevelEnum)
                return TeamRequest.JoinRequestManagementAccessLevelEnumToJsonValue(teamRequestJoinRequestManagementAccessLevelEnum);
            if (obj is TeamRequest.TeamMemberRemovalAccessLevelEnum teamRequestTeamMemberRemovalAccessLevelEnum)
                return TeamRequest.TeamMemberRemovalAccessLevelEnumToJsonValue(teamRequestTeamMemberRemovalAccessLevelEnum);
            if (obj is TeamRequest.TeamContentManagementAccessLevelEnum teamRequestTeamContentManagementAccessLevelEnum)
                return TeamRequest.TeamContentManagementAccessLevelEnumToJsonValue(teamRequestTeamContentManagementAccessLevelEnum);
            if (obj is TeamResponse.VisibilityEnum teamResponseVisibilityEnum)
                return TeamResponse.VisibilityEnumToJsonValue(teamResponseVisibilityEnum);
            if (obj is TeamResponse.EditTeamNameOrDescriptionAccessLevelEnum teamResponseEditTeamNameOrDescriptionAccessLevelEnum)
                return TeamResponse.EditTeamNameOrDescriptionAccessLevelEnumToJsonValue(teamResponseEditTeamNameOrDescriptionAccessLevelEnum);
            if (obj is TeamResponse.EditTeamVisibilityOrTrashTeamAccessLevelEnum teamResponseEditTeamVisibilityOrTrashTeamAccessLevelEnum)
                return TeamResponse.EditTeamVisibilityOrTrashTeamAccessLevelEnumToJsonValue(teamResponseEditTeamVisibilityOrTrashTeamAccessLevelEnum);
            if (obj is TeamResponse.MemberInviteManagementAccessLevelEnum teamResponseMemberInviteManagementAccessLevelEnum)
                return TeamResponse.MemberInviteManagementAccessLevelEnumToJsonValue(teamResponseMemberInviteManagementAccessLevelEnum);
            if (obj is TeamResponse.GuestInviteManagementAccessLevelEnum teamResponseGuestInviteManagementAccessLevelEnum)
                return TeamResponse.GuestInviteManagementAccessLevelEnumToJsonValue(teamResponseGuestInviteManagementAccessLevelEnum);
            if (obj is TeamResponse.JoinRequestManagementAccessLevelEnum teamResponseJoinRequestManagementAccessLevelEnum)
                return TeamResponse.JoinRequestManagementAccessLevelEnumToJsonValue(teamResponseJoinRequestManagementAccessLevelEnum);
            if (obj is TeamResponse.TeamMemberRemovalAccessLevelEnum teamResponseTeamMemberRemovalAccessLevelEnum)
                return TeamResponse.TeamMemberRemovalAccessLevelEnumToJsonValue(teamResponseTeamMemberRemovalAccessLevelEnum);
            if (obj is TeamResponse.TeamContentManagementAccessLevelEnum teamResponseTeamContentManagementAccessLevelEnum)
                return TeamResponse.TeamContentManagementAccessLevelEnumToJsonValue(teamResponseTeamContentManagementAccessLevelEnum);
            if (obj is TimePeriodBase.PeriodEnum timePeriodBasePeriodEnum)
                return TimePeriodBase.PeriodEnumToJsonValue(timePeriodBasePeriodEnum);
            if (obj is TimePeriodCompact.PeriodEnum timePeriodCompactPeriodEnum)
                return TimePeriodCompact.PeriodEnumToJsonValue(timePeriodCompactPeriodEnum);
            if (obj is TimeTrackingEntryBase.ApprovalStatusEnum timeTrackingEntryBaseApprovalStatusEnum)
                return TimeTrackingEntryBase.ApprovalStatusEnumToJsonValue(timeTrackingEntryBaseApprovalStatusEnum);
            if (obj is TimeTrackingEntryBase.BillableStatusEnum timeTrackingEntryBaseBillableStatusEnum)
                return TimeTrackingEntryBase.BillableStatusEnumToJsonValue(timeTrackingEntryBaseBillableStatusEnum);
            if (obj is ICollection collection)
            {
                List<string?> entries = new();
                foreach (var entry in collection)
                    entries.Add(ParameterToString(entry));
                return string.Join(",", entries);
            }

            return Convert.ToString(obj, System.Globalization.CultureInfo.InvariantCulture);
        }

        /// <summary>
        /// URL encode a string
        /// Credit/Ref: https://github.com/restsharp/RestSharp/blob/master/RestSharp/Extensions/StringExtensions.cs#L50
        /// </summary>
        /// <param name="input">string to be URL encoded</param>
        /// <returns>Byte array</returns>
        public static string UrlEncode(string input)
        {
            const int maxLength = 32766;

            if (input == null)
            {
                throw new ArgumentNullException("input");
            }

            if (input.Length <= maxLength)
            {
                return Uri.EscapeDataString(input);
            }

            StringBuilder sb = new StringBuilder(input.Length * 2);
            int index = 0;

            while (index < input.Length)
            {
                int length = Math.Min(input.Length - index, maxLength);
                string subString = input.Substring(index, length);

                sb.Append(Uri.EscapeDataString(subString));
                index += subString.Length;
            }

            return sb.ToString();
        }

        /// <summary>
        /// Encode string in base64 format.
        /// </summary>
        /// <param name="text">string to be encoded.</param>
        /// <returns>Encoded string.</returns>
        public static string Base64Encode(string text)
        {
            return Convert.ToBase64String(global::System.Text.Encoding.UTF8.GetBytes(text));
        }

        /// <summary>
        /// Convert stream to byte array
        /// </summary>
        /// <param name="inputStream">Input stream to be converted</param>
        /// <returns>Byte array</returns>
        public static byte[] ReadAsBytes(Stream inputStream)
        {
            using (var ms = new MemoryStream())
            {
                inputStream.CopyTo(ms);
                return ms.ToArray();
            }
        }

        /// <summary>
        /// Select the Content-Type header's value from the given content-type array:
        /// if JSON type exists in the given array, use it;
        /// otherwise use the first one defined in 'consumes'
        /// </summary>
        /// <param name="contentTypes">The Content-Type array to select from.</param>
        /// <returns>The Content-Type header to use.</returns>
        public static string? SelectHeaderContentType(string[] contentTypes)
        {
            if (contentTypes.Length == 0)
                return null;

            foreach (var contentType in contentTypes)
            {
                if (IsJsonMime(contentType))
                    return contentType;
            }

            return contentTypes[0]; // use the first content type specified in 'consumes'
        }

        /// <summary>
        /// Select the Accept header's value from the given accepts array:
        /// if JSON exists in the given array, use it;
        /// otherwise use all of them (joining into a string)
        /// </summary>
        /// <param name="accepts">The accepts array to select from.</param>
        /// <returns>The Accept header to use.</returns>
        public static string? SelectHeaderAccept(string[] accepts)
        {
            if (accepts.Length == 0)
                return null;

            if (accepts.Contains("application/json", StringComparer.OrdinalIgnoreCase))
                return "application/json";

            return string.Join(",", accepts);
        }

        

        /// <summary>
        /// Select the Accept header's value from the given accepts array:
        /// if JSON exists in the given array, use it;
        /// otherwise use all of them.
        /// </summary>
        /// <param name="accepts">The accepts array to select from.</param>
        /// <returns>The Accept header values to use.</returns>
        public static IEnumerable<MediaTypeWithQualityHeaderValue> SelectHeaderAcceptArray(string[] accepts)
        {
            if (accepts.Length == 0)
                    return [];

            if (accepts.Contains("application/json", StringComparer.OrdinalIgnoreCase))
                    return [MediaTypeWithQualityHeaderValue.Parse("application/json")];

            return accepts.Select(MediaTypeWithQualityHeaderValue.Parse);
        }

        /// <summary>
        /// Provides a case-insensitive check that a provided content type is a known JSON-like content type.
        /// </summary>
        [GeneratedRegex("(?i)^(application/json|[^;/ \t]+/[^;/ \t]+[+]json)[ \t]*(;.*)?$")]
        private static partial Regex JsonRegex();

        /// <summary>
        /// Check if the given MIME is a JSON MIME.
        /// JSON MIME examples:
        ///    application/json
        ///    application/json; charset=UTF8
        ///    APPLICATION/JSON
        ///    application/vnd.company+json
        /// </summary>
        /// <param name="mime">MIME</param>
        /// <returns>Returns True if MIME type is json.</returns>
        public static bool IsJsonMime(string mime)
        {
            if (string.IsNullOrWhiteSpace(mime)) return false;

            return JsonRegex().IsMatch(mime) || mime.Equals("application/json-patch+json");
        }

        /// <summary>
        /// Get the discriminator
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="discriminator"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public static string? GetDiscriminator(Utf8JsonReader utf8JsonReader, string discriminator)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    if (localVarJsonPropertyName != null && localVarJsonPropertyName.Equals(discriminator))
                        return utf8JsonReader.GetString();
                }
            }

            throw new JsonException("The specified discriminator was not found.");
        }

        /// <summary>
        /// The base path of the API
        /// </summary>
        public const string BASE_ADDRESS = "https://app.asana.com/api/1.0";

        /// <summary>
        /// The scheme of the API
        /// </summary>
        public const string SCHEME = "https";

        /// <summary>
        /// The context path of the API
        /// </summary>
        public const string CONTEXT_PATH = "/api/1.0";

        /// <summary>
        /// The host of the API
        /// </summary>
        public const string HOST = "app.asana.com";

        /// <summary>
        /// The format to use for DateTime serialization
        /// </summary>
        public const string ISO8601_DATETIME_FORMAT = "o";
    }
}
