/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using AsanaApiClient.Api;
using AsanaApiClient.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace AsanaApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing GoalsApi
    /// </summary>
    public sealed class GoalsApiTests : ApiTestsBase
    {
        private readonly IGoalsApi _instance;

        public GoalsApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IGoalsApi>();
        }

        /// <summary>
        /// Test AddCustomFieldSettingForGoal
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AddCustomFieldSettingForGoalAsyncTest()
        {
            string goalGid = default!;
            AddCustomFieldSettingForGoalRequest addCustomFieldSettingForGoalRequest = default!;
            Client.Option<bool> optPretty = default!;
            var response = await _instance.AddCustomFieldSettingForGoalAsync(goalGid, addCustomFieldSettingForGoalRequest, optPretty);
            var model = response.Ok();
            Assert.IsType<AddCustomFieldSettingForGoal200Response>(model);
        }

        /// <summary>
        /// Test AddFollowers
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AddFollowersAsyncTest()
        {
            string goalGid = default!;
            AddFollowersRequest addFollowersRequest = default!;
            Client.Option<bool> optPretty = default!;
            Client.Option<List<string>> optFields = default!;
            var response = await _instance.AddFollowersAsync(goalGid, addFollowersRequest, optPretty, optFields);
            var model = response.Ok();
            Assert.IsType<GetGoal200Response>(model);
        }

        /// <summary>
        /// Test CreateGoal
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateGoalAsyncTest()
        {
            CreateGoalRequest createGoalRequest = default!;
            Client.Option<bool> optPretty = default!;
            Client.Option<List<string>> optFields = default!;
            var response = await _instance.CreateGoalAsync(createGoalRequest, optPretty, optFields);
            var model = response.Created();
            Assert.IsType<GetGoal200Response>(model);
        }

        /// <summary>
        /// Test CreateGoalMetric
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateGoalMetricAsyncTest()
        {
            string goalGid = default!;
            CreateGoalMetricRequest createGoalMetricRequest = default!;
            Client.Option<bool> optPretty = default!;
            Client.Option<List<string>> optFields = default!;
            var response = await _instance.CreateGoalMetricAsync(goalGid, createGoalMetricRequest, optPretty, optFields);
            var model = response.Ok();
            Assert.IsType<GetGoal200Response>(model);
        }

        /// <summary>
        /// Test DeleteGoal
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteGoalAsyncTest()
        {
            string goalGid = default!;
            Client.Option<bool> optPretty = default!;
            var response = await _instance.DeleteGoalAsync(goalGid, optPretty);
            var model = response.Ok();
            Assert.IsType<ApproveAccessRequest200Response>(model);
        }

        /// <summary>
        /// Test GetGoal
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetGoalAsyncTest()
        {
            string goalGid = default!;
            Client.Option<bool> optPretty = default!;
            Client.Option<List<string>> optFields = default!;
            var response = await _instance.GetGoalAsync(goalGid, optPretty, optFields);
            var model = response.Ok();
            Assert.IsType<GetGoal200Response>(model);
        }

        /// <summary>
        /// Test GetGoals
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetGoalsAsyncTest()
        {
            Client.Option<bool> optPretty = default!;
            Client.Option<string> portfolio = default!;
            Client.Option<string> project = default!;
            Client.Option<string> task = default!;
            Client.Option<bool> isWorkspaceLevel = default!;
            Client.Option<string> team = default!;
            Client.Option<string> workspace = default!;
            Client.Option<List<string>> timePeriods = default!;
            Client.Option<int> limit = default!;
            Client.Option<string> offset = default!;
            Client.Option<List<string>> optFields = default!;
            var response = await _instance.GetGoalsAsync(optPretty, portfolio, project, task, isWorkspaceLevel, team, workspace, timePeriods, limit, offset, optFields);
            var model = response.Ok();
            Assert.IsType<GetGoals200Response>(model);
        }

        /// <summary>
        /// Test GetParentGoalsForGoal
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetParentGoalsForGoalAsyncTest()
        {
            string goalGid = default!;
            Client.Option<bool> optPretty = default!;
            Client.Option<List<string>> optFields = default!;
            var response = await _instance.GetParentGoalsForGoalAsync(goalGid, optPretty, optFields);
            var model = response.Ok();
            Assert.IsType<GetParentGoalsForGoal200Response>(model);
        }

        /// <summary>
        /// Test RemoveCustomFieldSettingForGoal
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RemoveCustomFieldSettingForGoalAsyncTest()
        {
            string goalGid = default!;
            RemoveCustomFieldSettingForGoalRequest removeCustomFieldSettingForGoalRequest = default!;
            Client.Option<bool> optPretty = default!;
            var response = await _instance.RemoveCustomFieldSettingForGoalAsync(goalGid, removeCustomFieldSettingForGoalRequest, optPretty);
            var model = response.Ok();
            Assert.IsType<ApproveAccessRequest200Response>(model);
        }

        /// <summary>
        /// Test RemoveFollowers
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RemoveFollowersAsyncTest()
        {
            string goalGid = default!;
            AddFollowersRequest addFollowersRequest = default!;
            Client.Option<bool> optPretty = default!;
            Client.Option<List<string>> optFields = default!;
            var response = await _instance.RemoveFollowersAsync(goalGid, addFollowersRequest, optPretty, optFields);
            var model = response.Ok();
            Assert.IsType<GetGoal200Response>(model);
        }

        /// <summary>
        /// Test UpdateGoal
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateGoalAsyncTest()
        {
            string goalGid = default!;
            UpdateGoalRequest updateGoalRequest = default!;
            Client.Option<bool> optPretty = default!;
            Client.Option<List<string>> optFields = default!;
            var response = await _instance.UpdateGoalAsync(goalGid, updateGoalRequest, optPretty, optFields);
            var model = response.Ok();
            Assert.IsType<GetGoal200Response>(model);
        }

        /// <summary>
        /// Test UpdateGoalMetric
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateGoalMetricAsyncTest()
        {
            string goalGid = default!;
            UpdateGoalMetricRequest updateGoalMetricRequest = default!;
            Client.Option<bool> optPretty = default!;
            Client.Option<List<string>> optFields = default!;
            var response = await _instance.UpdateGoalMetricAsync(goalGid, updateGoalMetricRequest, optPretty, optFields);
            var model = response.Ok();
            Assert.IsType<GetGoal200Response>(model);
        }
    }
}
