/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using AsanaApiClient.Api;
using AsanaApiClient.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace AsanaApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing ProjectBriefsApi
    /// </summary>
    public sealed class ProjectBriefsApiTests : ApiTestsBase
    {
        private readonly IProjectBriefsApi _instance;

        public ProjectBriefsApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IProjectBriefsApi>();
        }

        /// <summary>
        /// Test CreateProjectBrief
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateProjectBriefAsyncTest()
        {
            string projectGid = default!;
            UpdateProjectBriefRequest updateProjectBriefRequest = default!;
            Client.Option<bool> optPretty = default!;
            Client.Option<List<string>> optFields = default!;
            var response = await _instance.CreateProjectBriefAsync(projectGid, updateProjectBriefRequest, optPretty, optFields);
            var model = response.Created();
            Assert.IsType<GetProjectBrief200Response>(model);
        }

        /// <summary>
        /// Test DeleteProjectBrief
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteProjectBriefAsyncTest()
        {
            string projectBriefGid = default!;
            Client.Option<bool> optPretty = default!;
            var response = await _instance.DeleteProjectBriefAsync(projectBriefGid, optPretty);
            var model = response.Ok();
            Assert.IsType<ApproveAccessRequest200Response>(model);
        }

        /// <summary>
        /// Test GetProjectBrief
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetProjectBriefAsyncTest()
        {
            string projectBriefGid = default!;
            Client.Option<bool> optPretty = default!;
            Client.Option<List<string>> optFields = default!;
            var response = await _instance.GetProjectBriefAsync(projectBriefGid, optPretty, optFields);
            var model = response.Ok();
            Assert.IsType<GetProjectBrief200Response>(model);
        }

        /// <summary>
        /// Test UpdateProjectBrief
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateProjectBriefAsyncTest()
        {
            string projectBriefGid = default!;
            UpdateProjectBriefRequest updateProjectBriefRequest = default!;
            Client.Option<bool> optPretty = default!;
            Client.Option<List<string>> optFields = default!;
            var response = await _instance.UpdateProjectBriefAsync(projectBriefGid, updateProjectBriefRequest, optPretty, optFields);
            var model = response.Ok();
            Assert.IsType<GetProjectBrief200Response>(model);
        }
    }
}
