/*
 * Asana
 *
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using AsanaApiClient.Api;
using AsanaApiClient.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace AsanaApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing UserTaskListsApi
    /// </summary>
    public sealed class UserTaskListsApiTests : ApiTestsBase
    {
        private readonly IUserTaskListsApi _instance;

        public UserTaskListsApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IUserTaskListsApi>();
        }

        /// <summary>
        /// Test GetUserTaskList
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetUserTaskListAsyncTest()
        {
            string userTaskListGid = default!;
            Client.Option<bool> optPretty = default!;
            Client.Option<List<string>> optFields = default!;
            var response = await _instance.GetUserTaskListAsync(userTaskListGid, optPretty, optFields);
            var model = response.Ok();
            Assert.IsType<GetUserTaskList200Response>(model);
        }

        /// <summary>
        /// Test GetUserTaskListForUser
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetUserTaskListForUserAsyncTest()
        {
            string userGid = default!;
            string workspace = default!;
            Client.Option<bool> optPretty = default!;
            Client.Option<List<string>> optFields = default!;
            var response = await _instance.GetUserTaskListForUserAsync(userGid, workspace, optPretty, optFields);
            var model = response.Ok();
            Assert.IsType<GetUserTaskList200Response>(model);
        }
    }
}
